### ISSUE TITLE
深渊记录似乎有问题？

### ISSUE THREAD

**Issue by TheTychoStar** [xunkong/xunkong#103]
今天发现有深渊记录功能就刷新了一下，发现没有4月上的数据，而3月上和下的数据都有错误（实际都是满星，但是寻空显示3月上69星，3月下34星，伤害数据这些也对不上）。
因为米游社只能看到当期和最近一期的记录，且5月和4月下这两期寻空读取到的数据是正确的，是否深渊记录是只能获取到本期和上期的记录？可是我的寻空里有3月上下的记录，唯独少了4月上，而我印象中之前是没有用过深渊记录这个功能的。

这是寻空读取到的记录：
![image](https://user-images.githubusercontent.com/75252778/168477186-50326d1a-10ea-4bf9-aea3-4297b744251e.png)
这是游戏里查询到的记录：
![image](https://user-images.githubusercontent.com/75252778/168477239-0a04cf34-d1ea-4a12-837b-27fba855d057.png)

**Comment by Scighost** [comment]
很明显打通深渊后没有重新获取深渊的数据，或获取时深渊数据还没刷新。

**Comment by TheTychoStar** [comment]
我也想过，但是我印象中之前是没有获取过深渊数据的，昨天应该是我第一次用这个功能。程序是会在后台自动刷新深渊数据吗，如果是自动刷新那4月上的数据又没有。还有3月上获取到的数据是69星，这个感觉也不太正常的样子。
