### ISSUE TITLE
祈愿Json导入机制对uid和lang缺失的处理有问题

### ISSUE THREAD

**Issue by TremblingMoeNew** [xunkong/xunkong#104]
### 问题描述

在json仅在info域注明uid和lang而在祈愿项中没有的情况下，寻空无法正确从info读取到uid与lang。
此时若未在导入时指定uid和lang，寻空会提示uid为0以及lang为空；如果指定了，不管输的什么、是否与info中的一致，寻空都会直接用指定的那个

### 复现步骤

```plain text
1. 找一个UIGF Json格式导出记录文件，把祈愿项中的uid和lang全删了，只保留info里的
2. 在寻空中尝试导入，导入时不指定uid与lang，导入将失败
3. 在寻空中尝试导入，导入时指定错误的uid与lang，寻空将按错误值进行导入
```

### 寻空版本

0.2.0.0

**Comment by TremblingMoeNew** [comment]
@Scighost

**Comment by Scighost** [comment]
我选择删除校验，来着不拒。
