### ISSUE TITLE
打开祈愿记录界面卡死

### ISSUE THREAD

**Issue by leirunze119** [xunkong/xunkong#105]
### 问题描述

与以下三个现有issue现象相似，但程序版本不同：
（0.1.4.1）https://github.com/xunkong/desktop/issues/60
（0.1.7.0）https://github.com/xunkong/desktop/issues/77
（0.2.0.0）https://github.com/xunkong/desktop/issues/93

问题描述：
使用0.2.0.1版本打开祈愿记录界面有一定概率卡死，且会持续占用大量的CPU和内存资源。应该可以确定不是我的电脑性能导致加载太慢的问题，因为我在那个页面等了半个小时也没有加载出来，任务管理器始终显示未响应。

补充信息：
以前用的是0.1.2.0的版本，似乎没有遇到过这个问题？更新了一下就遇到了这个问题，详情见下方复现步骤描述。
以下给出了两份日志文件，分别是正常查看祈愿页面和查看祈愿页面时异常卡死的。出于隐私考虑，日志文件和截图中部分文件路径及UID已做模糊处理，应该不影响日志和截图内容的有效性。（其实两份日志没啥区别，似乎看不出来问题）

### 复现步骤

```plain text
我也不知道这个bug要怎么样才能触发，所以就详细描述一下我使用程序、遇到问题并尝试解决的全过程吧……（可能会比较冗长，希望能给开发者提供一些线索）
以下出现异常的步骤以*记号表示：
1.先前使用的版本是0.1.2.0（中间很久没用过了，也没有更新），查看了一下祈愿记录，一切正常，发现有新版本可以更新
2.将程序更新至0.2.0.1版本
3.在祈愿记录页面更新了最新的祈愿数据
4.在工具箱页面导出了祈愿记录的excel表格
*5.返回祈愿记录页面，卡死
*6.关闭程序并重新启动，进入祈愿记录页面，卡死；重复3次，每次都卡死
*7.在win10设置的“应用和功能”菜单中分别对“寻空”使用修复和重置，并启动程序，两次都在祈愿页面卡死
*8.卸载“寻空”，并重新安装0.2.0.1版本，启动程序，在祈愿页面卡死
9.将Documents文件夹下的Xunkong文件夹删除，启动程序，正常进入祈愿页面（无数据），并可以正常更新和显示祈愿数据
*10.在工具箱中导入此前备份的Wishlog的excel文件，并点击祈愿页面，在祈愿页面卡死
11.再次删除Xunkong文件夹，打开程序，可以正常进入祈愿页面（无数据），在工具箱中导入Wishlog，返回祈愿页面，可以正常显示导入的数据
*12.再次使用工具箱导出祈愿记录的excel文件，返回祈愿页面，卡死。重复关闭并重新启动程序，每次都在进入祈愿页面时卡死
13.重复步骤11，无异常出现。反复关闭程序并重新启动，进入祈愿页面，显示正常，未出现卡死现象
*14.点击任意其他界面（例如角色信息），再点击祈愿页面，卡死，且在重复步骤11之前，每次进入祈愿页面都卡死，无论是否点击过其他界面。重复步骤11和14，反复触发卡死
15.再次执行步骤13，一切正常，祈愿页面可以正常显示，来github写issue
*16.当我写完上面的步骤15之后，再次尝试打开程序的祈愿页面，卡死，反复退出程序并启动，进入祈愿界面一定概率卡死，但也有一定概率正常显示

总结一下我遇到的卡死现象的规律：
a.每次在卡死现象出现后，通常只有删除Xunkong数据文件夹才能消除卡死现象，否则无论重启、重装程序多少次，卡死现象通常会继续存在（疑似是数据文件出现问题？不过也不一定，也遇到过几次只重启程序而没有删除数据文件就恢复正常的）
b.以上的第10/12/14步每次都是在操作了一些其他功能后返回祈愿页面时发生的卡死问题，似乎和前置操作有关？如果在启动程序后不点击任何其他地方，直接进入祈愿页面，则有较大的概率可以正常显示。
c.如果在卡死状态下放置不管，CPU占用率一直很高，且程序的内存占用会从正常使用时的100M左右持续上升到数个G，并且一直增加。在我等待时间最长的一次中，程序占掉了4G多的内存，然后我将其强制结束掉了……或许可以推测程序是在运行到某个需要申请内存资源的步骤时卡住了？
```

### 截图

![xunkong_bug_censored](https://user-images.githubusercontent.com/38918175/173177937-bcba0319-e5b9-4977-be23-1a98cc53316e.png)

### 系统版本

Windows 10 21H2

### 寻空版本

0.2.0.1

### 日志

[log_20220611_135745_正常.txt](https://github.com/xunkong/desktop/files/8883408/log_20220611_135745_.txt)
[log_20220611_135331_异常.txt](https://github.com/xunkong/desktop/files/8883409/log_20220611_135331_.txt)

**Comment by paim0e** [comment]
@leirunze119 
最新版也有同样的问题 
尝试了很多次，主页→祈愿记录|主页→相册→祈愿记录|主页→角色信息→祈愿记录|主页→旅行礼记→祈愿记录
基本都会卡死 只有切到网页小工具再切祈愿记录不会卡死
先随便添加个网页小工具凑合一下吧

**Comment by Shanwer** [comment]
> @leirunze119 最新版也有同样的问题 而且卡死的状态下内存越吃越多 尝试了很多次，主页→祈愿记录|主页→相册→祈愿记录|主页→角色信息→祈愿记录|主页→旅行礼记→祈愿记录 基本都会卡死 只有切到网页小工具再切祈愿记录不会卡死 先随便添加个网页小工具凑合一下吧

+1 今天更新了新版本迁移数据后也有同样的问题，而且添加不了网页小工具（）

**Comment by Shanwer** [comment]
今天更新了新版本，已经解决了√

**Comment by Scighost** [comment]
> 今天更新了新版本，已经解决了√

还是有概率会卡死。。。

**Comment by Shanwer** [comment]
> > 今天更新了新版本，已经解决了√
> 
> 还是有概率会卡死。。。

额，我现在的情况是，打开应用后直接点击祈愿记录或者先点其它的再回去点祈愿记录都不会卡死，记录有600抽左右

**Comment by zhang121z** [comment]
最新版1.03更新之后打开祈愿记录也会卡死
