### ISSUE TITLE
关于祈愿记录界面缩放和功能

### ISSUE THREAD

**Issue by Jsffyayoi** [xunkong/xunkong#106]
### 你的建议

  祈愿记录界面图标太小显示出来会有白色毛边，建议增加自行选择缩放比例

  然后寻空无法做到点击角色/武器查看历史在哪个卡池出货，这个功能我还挺喜欢的，希望作者能早日实现，谢谢！

2k分辨率下角色图像如下
![Z A8S8NKVM_PL5@V`T9V@QT](https://user-images.githubusercontent.com/33521701/174301425-9829b91e-eff0-47d2-8175-df61731fb5f5.png)

**Comment by Scighost** [comment]
不是很懂你说的**白色毛边**是什么，如果是指图片锯齿的话，这个问题前几天才被解决 feab56f8817403be9015b9d8188d583cf5965636
