### ISSUE TITLE
建议祈愿记录总览页面里增加非祈愿人物和武器

### ISSUE THREAD

**Issue by crlf0710** [xunkong/xunkong#107]
### 你的建议

非祈愿人物包括，芭芭拉x1，香菱x1，埃洛伊x1

非祈愿武器包括各种任务武器等

可以默认选中状态纳入统计范围。这样可以很方便的查看自己角色总表和武器总表。谢谢！

**Comment by Scighost** [comment]
不行，该页面展示的内容全部基于你的抽卡数据，抽卡数据以外的获得渠道不会纳入统计。
