### ISSUE TITLE
寻空无法打开

### ISSUE THREAD

**Issue by mizukaiyo** [xunkong/xunkong#109]
### 问题描述

点击图标之后，会弹出一个黑色小窗口，然后就没了

### 复现步骤

```plain text
点击图标后，就弹出黑色小窗口，然后消失
```

### 截图

![QQ图片20220630232126](
https://user-images.githubusercontent.com/96719252/176715578-803b3931-8f16-41fb-a009-d4b5728d364b.mp4
)

### 系统版本

Windows 10 21H2（操作系统内部版本19044.1766）

### 寻空版本

0.2.0.2

**Comment by LuXv233** [comment]
一样
