### ISSUE TITLE
寻空是否支持导入刻记牛杂店的祈愿数据？

### ISSUE THREAD

**Issue by yeqiugt** [xunkong/xunkong#116]
### 问题描述

导入本地祈愿数据的入口没找到

### 复现步骤

```plain text
如上
```

### 系统版本

win10

### 寻空版本

1.00

**Comment by smallg0at** [comment]
之前试过，云数据是通用的。也就是说如果在刻记牛杂店上传了记录，在寻空应该能在记录备份下载到同样的数据。

**Comment by Scighost** [comment]
1.0.0 版本的部分功能尚未迁移完成，现在可以导入了。
