### ISSUE TITLE
更新1.01版本出现80073CF3错误

### ISSUE THREAD

**Issue by Fnvelope** [xunkong/xunkong#123]
### 问题描述

运行更新文件就提示这个

### 复现步骤

```plain text
直接点开就出错，卸载之后重装才行
```

### 截图

![微信截图_20220716114224](https://user-images.githubusercontent.com/54101846/179337776-ed11a871-efbb-457c-b4e8-b3d5fa93e828.png)

### 系统版本

Windows 10 21H2

### 寻空版本

1.0.0.0

### 日志

无

### 备注

无

**Comment by Scighost** [comment]
已不再帮助解决侧载版的安装问题，请安装商店版。
