### ISSUE TITLE
显示COMExeption

### ISSUE THREAD

**Issue by yvfeng123** [xunkong/xunkong#124]
### 问题描述

1.启动时会显示“     COMExeption  组件初始化失败。（0x88982F8B）     ”点到其他页面，再点到主页页面时，同样会显示上述问题。
![微信图片_20220716173244](https://user-images.githubusercontent.com/88815425/179349316-48154423-3772-4f0d-b3d6-f22ae0fd8e98.png)

2.点击主界面的保存壁纸按钮：
![微信图片_20220716173540](https://user-images.githubusercontent.com/88815425/179349375-e34912dc-12c3-40be-9467-680cb7b4f278.png)
也会显示类似的提示：
![微信图片_20220716173300](https://user-images.githubusercontent.com/88815425/179349390-29002129-7bce-40f2-8ffa-9ed59f5b9bd7.png)
并且主界面不显示壁纸，因为访问P站似乎需要梯子或加速器，希望可以选择镜像站或其他替代站如：
1.https://www.vilipix.com/
2.https://pixivel.moe/

### 复现步骤

```plain text
1.启动时会显示“ COMExeption 组件初始化失败。（0x88982F8B） “点到其他页面，再点到主页页面时，同样会显示上述问题。

2.点击主界面的保存壁纸按钮：

https://user-images.githubusercontent.com/88815425/179349375-e34912dc-12c3-40be-9467-680cb7b4f278.png
```

### 系统版本

Windows 11专业版 21H2 22000.194

### 寻空版本

侧载版 1.0.1.0

**Comment by Patrick-Ze** [comment]
我也遇到了这个问题，现象和 @yvfeng123 描述的一样。我的系统版本是 `Windows 10 LTSC 10.0.19044.1586`

`

**Comment by Scighost** [comment]
第一个 ComException 的原因未知，可能是系统的问题，下个版本使用无**透明度渐变**的图片代替；
第二个 ComException 将在下个版本修复。

**Comment by Scighost** [comment]
视觉效果会差一些

![有透明度](https://user-images.githubusercontent.com/61003590/179404692-cb9aefd7-46bc-4c27-8375-a7746559804f.png)

![无透明度](https://user-images.githubusercontent.com/61003590/179404735-623dc36e-8005-497a-8724-60b6a31a85e9.png)

**Comment by Scighost** [comment]
图片下载源是 cloudflare 不是 pixiv，不需要切换为镜像站。

**Comment by yvfeng123** [comment]
> 图片下载源是 cloudflare 不是 pixiv，不需要切换为镜像站。

图片照样显示不了

**Comment by Scighost** [comment]
此版本已不是最新版本，如果还有问题，请重新发布新 issue。
