### ISSUE TITLE
更新的问题。

### ISSUE THREAD

**Issue by huabozahuopu** [xunkong/xunkong#137]
### 问题描述

更新不了

### 复现步骤

下载之后正常点击Xunkong.Desktop.Package_1.0.3.0_x64.msixbundle 然后就显示安装失败。

### 截图

![图片](https://user-images.githubusercontent.com/100459013/180651324-0bbdd201-cdad-4c33-99ba-e62f3336e9b1.png)

### 系统版本

win11

### 寻空版本

1.0.2

**Comment by Scighost** [comment]
Release 页面下载压缩包，里面有相关依赖项 dependency/x64/...

**Comment by Scighost** [comment]
已上架微软商店，如果再出现安装问题请下载商店版。
