### ISSUE TITLE
寻空快速启动游戏功能报错

### ISSUE THREAD

**Issue by pbxs666** [xunkong/xunkong#142]
### 问题描述

以前用的好好地，今天突然成这样了，用寻空里的快速启动游戏功能时（不论是软件里点击启动游戏按钮，还是在磁贴上右键启动游戏），系统会提示错误信息。软件重装了也没用。

### 复现步骤

从今早开始，只要快速启动游戏就报错，其他功能正常无误。

### 截图

错误信息如下：
![图片1](https://user-images.githubusercontent.com/47630168/182009215-9db088bb-885c-4f6e-adb2-e84ca7285b0e.png)

看到有“fpsunlock”字样，但是解锁帧数上限功能我没开启

### 系统版本

Windows10 20H2

### 寻空版本

侧载版1.0.3.0

### 备注

昨晚逛Github还发现一个类似的软件，叫“GDP.Genshin”
https://github.com/DGP-Studio/Snap.Genshin
里面也有类似的快速启动游戏，会不会跟这个有冲突？我尝试过卸载该软件，可寻空快速启动游戏功能依旧报错。

**Comment by Scighost** [comment]
> 看到有“fpsunlock”字样，但是解锁帧数上限功能我没开启

现在这个版本不管开不开解锁帧都会从fpsunlock启动游戏。

> 昨晚逛Github还发现一个类似的软件，叫“GDP.Genshin”

寻空和SnapGenshin不会有冲突，你也可以使用他家的软件。

抱歉暂时没有办法解决这个问题。
