### ISSUE TITLE
米游社签到会失败并返回 -10001

### ISSUE THREAD

**Issue by smallg0at** [xunkong/xunkong#143]
### 问题描述

从 8 月 5 日开始，寻空的自动米游社签到会返回以下 Response：
```
{"data":null,"message":"invalid request","retcode":-10001}
```

在米游社查看数据，确认会签到失败，但可以在米游社正常签到。
即便生成并添加新的 Cookie，也不能解决此问题。
尚未测试在寻空内浏览器添加的账号是否可用。

### 复现步骤

1. 进行一次自动签到

### 系统版本

Windows 11 Build 25174

### 寻空版本

1.0.3

**Comment by PurBlu** [comment]
+1
![image](https://user-images.githubusercontent.com/74239692/182988113-2feff1f4-b35b-4839-88cb-51da78321ac0.png)

**Comment by Myriab** [comment]
测试了寻空的最新版本和0.2.0版本，以及刻晴牛杂，都是一样的问题。

**Comment by Scighost** [comment]
米游社接口更新了，之前写的签到功能全部失效，晚上再修。

**Comment by Ashatear** [comment]
既然有人提交了我就不交了

**Comment by smallg0at** [comment]
确认 1.0.5 版本修复了此问题，close 了。感谢。
