### ISSUE TITLE
1.0.5.0无法使用寻空启动游戏

### ISSUE THREAD

**Issue by Samonyoge** [xunkong/xunkong#146]
### 问题描述

1.0.5.0无法使用寻空启动游戏，右键图标和软件内启动按钮都无任何反应。
重装1.0.3.0版本可正常启动。
另外不同账号的快速切换功能还会回归吗？谢谢

### 复现步骤

每次都无法启动，点击后无任何反应。

### 系统版本

Windows 10 21H2

### 寻空版本

1.0.5.0

**Comment by Scighost** [comment]
确实，我也复现成功了，明天再仔细看看。

切换账号功能不会再加入，这个功能大概率不能通过商店的审核。
