### ISSUE TITLE
1.0.5.0打开角色信息，点击更新元数据就崩溃

### ISSUE THREAD

**Issue by bingyang2000** [xunkong/xunkong#147]
### 问题描述

国内上网，1.0.5.0打开角色信息，点击更新元数据就崩溃

### 复现步骤

未挂梯子时，打开寻空侧载板，点击左侧角色信息，点击更新元数据，就会未响应

### 截图

![$CJ_%U{)Q636M Z0}6_ATL1](https://user-images.githubusercontent.com/73159426/183242084-1b4f9a8e-a54d-411c-baf4-4fe41b108beb.png)

### 系统版本

Win10 20H2

### 寻空版本

1.0.5.0

### 备注

但是挂上梯子后就没有问题

**Comment by Scighost** [comment]
我测试了很多次，只成功复现过一次，确实没办法找到原因。
建议把域名 `api.xunkong.cc` 加到代理列表里。
