### ISSUE TITLE
希望能加入开机自动启动功能！

### ISSUE THREAD

**Issue by Jsffyayoi** [xunkong/xunkong#149]
### 你的建议

如果可以的话希望能加入自动启动功能，找了一圈在测载版里面没有相关选项。

之前牛杂店开机自动启动然后签到一气呵成用习惯了，再也不能没有这个功能了。
球球辣，加上吧大佬
砰砰砰磕头

**Comment by oxygen-dioxide** [comment]
可以用以下方式手动添加：
打开两个文件管理器窗口，在地址栏分别输入`shell:appsfolder`和`shell-startup`
然后，在shell:appsfolder中找到寻空，拖动到shell-startup里面去
![image](https://user-images.githubusercontent.com/54425948/184542741-7c4660c2-4977-471b-8115-81b1129c8202.png)
这样可以将任意软件设置为开机自启动。

**Comment by Scighost** [comment]
原来是这样解决的吗，太厉害了！
