### ISSUE TITLE
角色信息和深境螺旋页面HoyolabException （10103）错误，提取不到信息

### ISSUE THREAD

**Issue by DXH88** [xunkong/xunkong#150]
### 问题描述

RT，在账号登录正常，主页面，祈愿记录及旅行札记都正常的情况下，角色信息和深境螺旋页面会显示HoyoloabException - 初始化角色信息页面 （10103）和HoyoloabException - 获取深渊数据 （10103）错误信息

该问题从使用寻空开始就存在，直至更新1.0及更新至最新1.0.6.0版、切换为商店版均未解决

![WeChat Image_20220810213242](https://user-images.githubusercontent.com/73939838/183917263-925abf9b-11ce-46d5-8be3-b86eb9a3a6b5.png)

### 复现步骤

尝试过删除程序、删除C:\Users\**\Documents\Xunkong数据重新登录并载入等手段，每次刷新依然会复现该问题，且从来读不出这两个模块的数据

### 截图

![WeChat Image_20220810213242](https://user-images.githubusercontent.com/73939838/183918960-149a5784-d736-478a-bb7e-84814b9d109f.png)

### 系统版本

Windows 10 pro 21H2

### 寻空版本

1.0.6.0

### 备注

谢谢

**Comment by JuLi-C** [comment]
我登录第二个账号就显示这个

**Comment by Scighost** [comment]
HoyolabException 指米游社返回了错误的内容，你需要检查账号有没有问题。
