### ISSUE TITLE
1.1.0.0 快速启动不能切换账号？

### ISSUE THREAD

**Issue by 0vvO** [xunkong/xunkong#152]
### 你的建议

问题描述
Win10 寻空从0.2.0.2升级到1.1.0.0版本后磁贴的快速启动不能切换账号了吗？是这个功能被删掉还是我的配置有问题？

复现步骤
--------
截图
![image](https://user-images.githubusercontent.com/33773085/184594725-a9ef90ea-71e1-492e-bc72-befe837ec2ff.png)

系统版本
Windows 10

寻空版本
1.1.0.0

日志
--------

备注
--------

**Comment by Scighost** [comment]
暂时不会恢复这个功能，一是因为框架的限制，无法直接写注册表，需要用其他手段绕过，二是不知道能不能过微软商店的审核。
