### ISSUE TITLE
深境螺旋页面账号切换问题

### ISSUE THREAD

**Issue by qakcn** [xunkong/xunkong#153]
切换账号后，页面不会自动刷新，要点右上角的刷新数据。
如果点开了某一期数据查看，然后再切换账号，右侧的战斗数据也会出现问题。要么不更新还是之前的数据，要么直接没有任何显示。

**Comment by Scighost** [comment]
> 切换账号后，页面不会自动刷新，要点右上角的刷新数据。

是的

> 如果点开了某一期数据查看，然后再切换账号，右侧的战斗数据也会出现问题。要么不更新还是之前的数据，要么直接没有任何显示。

点击刷新按键

**Comment by qakcn** [comment]
就是，有时候刷新没用。
我理解可能是获取到的数据就有问题，可这种时候应该提示错误或者不显示，而不是显示错误的数据。
请看下图的情况：
![out](https://user-images.githubusercontent.com/1809188/184809514-cd2c8587-24fa-4012-98bf-9a9a41471a15.gif)

**Comment by Scighost** [comment]
看懂了。

首先，有一个客观存在的问题，每次打完新的一期深渊之后，战斗统计（出战次数、战斗数据）和战斗记录不是同步出现的，统计稍落后于记录，这是米游社的问题。
其次，深境螺旋的界面设计中也存在一个问题，当被点击的期数中没有战斗数据时，这一栏应该是空白的，但是并没有。
二者结合产生了你遇到的这种情况，因为账号一的第50期，账号三的第51期没有战斗统计的数据，查看数据库也能印证这一点。
