### ISSUE TITLE
寻空侧载版安装失败 版本: 1.1.0.0

### ISSUE THREAD

**Issue by Guducat** [xunkong/xunkong#154]
### 你的建议

寻空侧载版安装失败
应用安装程序无法安装应用包相关项。请向开发人员索要应用包。

图示：
[https://guducat.cn/files/pic/Failed-to-install-Xunkong.png](url)

**Comment by Scighost** [comment]
已不再帮助解决侧载版安装失败的问题，请等待商店版更新。
