### ISSUE TITLE
寻空的后台定时自动签到无效

### ISSUE THREAD

**Issue by Klamist** [xunkong/xunkong#155]
启动时签到、后台定时签到都打开了，启动签到能成功，但后台自动签到一直没效果。
WIN10最新版系统，1.1.0.0-x64寻空（使用zip里ps1安装的）。
电脑是24小时开机的。
需要额外设置什么内容吗？

**Comment by Scighost** [comment]
在 win10 系统上，1.x 版本无法运行后台任务，原因不明，无法解决。
