### ISSUE TITLE
寻空侧载版1.1.0.0安装失败

### ISSUE THREAD

**Issue by 1498551989** [xunkong/xunkong#156]
### 问题描述

点击更新后安装失败报错 应用安装程序无法安装应用包相关项。请向开发人员索要  应用包。

### 复现步骤

我尝试过直接更新也试过卸载后重新安装，两个版本的安装包都提示这个错误，然后压缩包内的也提示这个错误。

### 截图

![QQ截图20220816144643](https://user-images.githubusercontent.com/43911343/184815094-d6e598d7-55fe-4325-9baa-081fd3953342.png)

### 系统版本

Windows 10 专业版 21H2

### 寻空版本

1.1.0.0

### 日志

安装失败没有日志吧，我没看到今天日期的log。

**Comment by Scighost** [comment]
已不再帮助解决侧载版安装失败的问题，请等待商店版更新。
