### ISSUE TITLE
你的标题1.1版本侧载版安装失败

### ISSUE THREAD

**Issue by zgh323** [xunkong/xunkong#157]
### 问题描述

旧版本为1.0.6.0，N卡，intel i7，下载的[Xunkong.Desktop.Package_1.1.0.0_x64.msixbundle]文件进行安装，但是安装失败

### 复现步骤

下载，双击，安装，失败

### 截图

![image](https://user-images.githubusercontent.com/46866448/184842445-08156ca6-71d1-457a-bd65-62c9a33aecac.png)

### 系统版本

windows 10 21H1

**Comment by Scighost** [comment]
重复 #156
