### ISSUE TITLE
使用成就系统后提示账号风险控制，无法自动签到

### ISSUE THREAD

**Issue by Askwind** [xunkong/xunkong#159]
### 问题描述

提示 “账号受到 风险限制，请到米游社手动签到（375）”。
退出账号重新登陆xunkong也无法恢复，请问除了手动签到，有何恢复的方法吗？

### 复现步骤

1.更新到最新的侧载版（1.1.0.0）
2.使用“成就管理”的获取功能
3.再次进入寻空就不能自动签到了

**Comment by Scighost** [comment]
签到风控和成就没有任何关系，没有办法恢复。

**Comment by Askwind** [comment]
那签到风控是啥原因引起的呢？只能去找mhy客服处理咯
