### ISSUE TITLE
希望启动游戏按钮能在寻空程序的第一个界面出现

### ISSUE THREAD

**Issue by ataravarice** [xunkong/xunkong#162]
### 你的建议

希望启动游戏的按钮不放在次级菜单里，而是放在主页的每日一图的下面，这样就能把寻空变成能自动签到的启动器

**Comment by Askwind** [comment]
这个确实是个好的建议，附议！启动键 应该放到首页的某个显眼的位置

**Comment by Scighost** [comment]
https://github.com/xunkong/xunkong/releases/tag/1.1.3
