### ISSUE TITLE
无法从日志中获取祈愿记录网址

### ISSUE THREAD

**Issue by Scighost** [xunkong/xunkong#165]
3.0 版本之前在游戏中打开祈愿记录后，会把记录页面的网址写入到日志文件 `AppData\LocalLow\miHoYo\原神\output_log.txt`，此次更新后不再有写入日志的操作。

接下来会尝试使用代理并抓包的方式获取该网址。

**Comment by LilligantMatsuri** [comment]
目前 Paimon.moe 提供了两种新的祈愿记录获取方式：https://paimon.moe/wish/import

- **方法一**
从游戏数据文件夹的 webCaches 中获取祈愿记录地址，由 Paimon.moe 用户 jogerj 提供。
```
https://gist.github.com/jogerj/0339e61a92e0de2e360c5212a94854e8
```
最终能够得到 `https://hk4e-api-os.hoyoverse.com/event/gacha_info/api/getGachaLog` 开头的地址。
- **方法二**
从剪贴板获取了游戏内 webview 打开的祈愿记录展示页地址 `https://webstatic-sea.hoyoverse.com/genshin/event/e20190909gacha-v2/index.html`，这个方法来自 EnderSyth 的 [Genshin-Wish-Export](https://github.com/EnderSyth/Genshin-Wish-Export)

寻空不妨参考一下以上方法。
