### ISSUE TITLE
关于登录多个账号

### ISSUE THREAD

**Issue by JuLi-C** [xunkong/xunkong#166]
### 问题描述

登录多个账号后，祈愿记录怎么添加别的账号的uid，等了好久也不刷新，也没有添加的按钮，是不能添加吗。

### 复现步骤

重启多次还是这样

### 系统版本

win11

### 寻空版本

1.1.5.0

**Comment by Scighost** [comment]
确实没有仔细考虑这个问题，你可以等24小时，当前网址过期后，再次获取。

**Comment by JuLi-C** [comment]
> 确实没有仔细考虑这个问题，你可以等24小时，当前网址过期后，再次获取。

好滴

**Comment by Scighost** [comment]
https://github.com/xunkong/xunkong/releases/tag/1.1.6
