### ISSUE TITLE
1.1.5版本支持国际服祈愿记录获取吗？

### ISSUE THREAD

**Issue by TheTychoStar** [xunkong/xunkong#168]
### 问题描述

目前国服可以正常获取，但是国际服启动代理后，在游戏中重新开启历史记录页面寻空无法获取到网址。

### 复现步骤

点击获取记录-提示网址过期-启动代理-返回游戏重新打开历史记录页面-返回寻空查看-没有获取到网址的提示-再次点击获取记录-弹出提示网址过期的对话框，一直循环。

### 系统版本

Windows 11

### 寻空版本

1.1.5

**Comment by Scighost** [comment]
理论上支持，但是我没办法测试真实情况，你可以自己抓包看一下网址。

**Comment by TheTychoStar** [comment]
国际服和国服应该是不一样了，我看Genshin-Wish-Export也单独为国际服更新了一个版本。1.1.6版用寻空的代理功能还是无法获取到网址，但用我自己抓的网址输入到寻空里就可以更新了。
国际服现在的网址开头是`https://webstatic-sea.hoyoverse.com/genshin/event/e20190909gacha-v2/index.html`
国服的是`https://webstatic.mihoyo.com/hk4e/event/e20190909gacha-v2/index.html`
不知道差别是不是在这里。

**Comment by Scighost** [comment]
原来国际服换网址了
