### ISSUE TITLE
自动签到失败HoyolabException(375)

### ISSUE THREAD

**Issue by kamsahsiegte** [xunkong/xunkong#169]
### 问题描述

账号受到风控限制请前往米游社签到(375)
这个有什么办法解决吗

### 复现步骤

启动软件即弹出错误提示

### 截图

![QQ截图20220826105953](https://user-images.githubusercontent.com/112145108/186810222-3d523ed0-e2e1-4c29-8f5d-c5fbc9a94971.png)

### 系统版本

Windows 10 企业版 21H2

### 寻空版本

1.1.6.0

### 日志

[log_20220826_105945.txt](https://github.com/xunkong/xunkong/files/9429492/log_20220826_105945.txt)

**Comment by Scighost** [comment]
没有很好的办法解决，只能自己去签了。
