### ISSUE TITLE
希望能用webdav备份抽卡记录，牛杂店一直在用

### ISSUE THREAD

**Issue by sonofrain** [xunkong/xunkong#170]
### 你的建议

抽卡记录查询失败才发现作者开新坑了，试用了一下感觉不错。
但是当我像以往一样备份记录的时候，却发现没有熟悉的入口。
牛杂店用了快两年，一直用坚果云备份抽卡记录，也正是这个习惯才让我的记录在数次装机之后依然得以完整保存。
现在的版本我用内置备份功能一直无法连接，希望作者考虑一下，让我用自己的网盘。

**Comment by Scighost** [comment]
写了几行，最后都被我删掉了，想了想只有一个原因：不想做这个功能。
