### ISSUE TITLE
原石增长率和摩拉增长率被玩坏啦！

### ISSUE THREAD

**Issue by HyBoxwood** [xunkong/xunkong#171]
### 你的建议

同样的数据 为什么寻空的曲线比excel逆天
![QQ截图20220827125331](https://user-images.githubusercontent.com/87700780/187015480-861cb721-3928-42ff-9749-f0f9e6fd2071.png)
寻空
![QQ截图20220827132254](https://user-images.githubusercontent.com/87700780/187016102-9de7e2d8-77e6-4224-9e19-6790e69260c9.png)
excel
我在excel里找不到能模仿寻空曲线的方法（x）
ps：数据源：米游社记录
![QQ图片20220819230454](https://user-images.githubusercontent.com/87700780/187015437-c801a461-9be5-45fd-ac53-f041198a9508.jpg)

**Comment by Scighost** [comment]
![T{2%BK7B NWF {17ZZOWR7G](https://user-images.githubusercontent.com/61003590/187032646-24a357aa-c994-45a9-9e69-f1c8eadbdb54.gif)

仔细看这图还挺有道理的，我设置的增长率的坐标范围是 -100~100%，增加了 70 倍那曲线当然是一飞冲天，下一个月增长率接近于 0，又是跌落谷底。看起来这么怪只能说图表的曲线平滑做得不好。

**Comment by Scighost** [comment]
> 删除增长率曲线

因为图表库的平滑曲线功能做得不好，很容易出现楼主的那种情况。

> 删除摩拉原石的数字标注

保存的月数据越多，每个月能占的空间也越少，已经开始出现数字超出柱子范围的情况了。

<img width="132" alt="image" src="https://user-images.githubusercontent.com/61003590/189140506-67032be4-d159-4b5f-9f8e-50cedd2abfdc.png">
