### ISSUE TITLE
希望添加多服务器切换启动功能

### ISSUE THREAD

**Issue by loaferwp** [xunkong/xunkong#172]
### 你的建议

希望添加多服务器切换启动功能，可以实现B服和官服自由切换，并且可以本地保存账号信息

**Comment by Scighost** [comment]
这里有你想要的功能 [DawnFz/Genshin.Launcher.Plus](https://github.com/DawnFz/Genshin.Launcher.Plus)
我没有切换服务器的需求，寻空不会加入这个功能。
