### ISSUE TITLE
椰羊导出成就有误

### ISSUE THREAD

**Issue by JoshYEn** [xunkong/xunkong#174]
### 问题描述

椰羊扫描得到的成就，无法正常导出至xunkong，而且后续也无法手动修改

### 复现步骤

椰羊网页：导出 -> 寻空

### 截图

![image](https://user-images.githubusercontent.com/11255434/187208426-bdc786d8-42c8-492e-8229-6bf112e67a48.png)
该成就应为未完成。

### 系统版本

Windows 11 21H2

### 寻空版本

1.1.7.0

**Comment by Scighost** [comment]
把椰羊导出的文件，椰羊网页里这部分成就的截图，游戏里这部分成就的截图发给我。
________________________________
From: JoshYEn ***@***.***>
Sent: Monday, August 29, 2022 9:10:04 PM
To: xunkong/xunkong ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [xunkong/xunkong] 椰羊导出成就有误 (Issue #174)


问题描述

椰羊扫描得到的成就，无法正常导出至xunkong，而且后续也无法手动修改

复现步骤

椰羊网页：导出 -> 寻空

截图

[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F11255434%2F187208426-bdc786d8-42c8-492e-8229-6bf112e67a48.png&data=05%7C01%7C%7C2ed83b29b9b145dac39008da89bfcad0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637973754084644333%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GzChmQ%2FFQQNYoh%2BNEPfMfIjgBHjL9ACUXq5pfRbJwhA%3D&reserved=0>
该成就应为未完成。

系统版本

Windows 11 21H2

寻空版本

1.1.0

日志

No response

备注

No response

**Comment by JoshYEn** [comment]
椰羊截图：
![image](https://user-images.githubusercontent.com/11255434/187255213-f1a1bdc0-f019-463e-a13b-cd4dc9877774.png)

椰羊导出方式：
![image](https://user-images.githubusercontent.com/11255434/187255572-2d5637d2-f9f6-430b-903c-14455ddb729a.png)

寻空app提示：
![image](https://user-images.githubusercontent.com/11255434/187255658-6fec4b7f-4a28-48a7-8a96-58a2b75cce95.png)

使用这个方法没有文件，不过如果椰羊导出UIAF 1.1 JSON，同样可复现该bug。成就文件如下，删除 `.txt` ：
[椰羊UIAF1.1.20220830010145.json.txt](https://github.com/xunkong/xunkong/files/9446534/UIAF1.1.20220830010145.json.txt)

我这里一共发现了两个不一致的地方，另一个成就是破灭之时：
![image](https://user-images.githubusercontent.com/11255434/187256491-2c5b05ee-001a-49ec-9c2a-d9d6cc7c9fbc.png)

**Comment by JoshYEn** [comment]
另外，寻空的完成进度与椰羊不一致，椰羊与游戏中是一致的，应该是四舍五入出了点问题。
![image](https://user-images.githubusercontent.com/11255434/187257216-d2a016db-f7b9-4691-b22a-e418b33b636d.png)
![image](https://user-images.githubusercontent.com/11255434/187257575-f8315ba7-b8a1-416c-8b80-2f8aeeef5ed4.png)

**Comment by Scighost** [comment]
寻空通过两个条件判断成就是否达成，如果一个成就的 `状态 status > 1`  或 `进度 current` 到达完成值时，则会认为该成就已达成。

以破灭之时为例：
<img width="451" alt="image" src="https://user-images.githubusercontent.com/61003590/187329700-5714906e-dad9-487a-adfb-2fe193e64866.png">
<img width="185" alt="image" src="https://user-images.githubusercontent.com/61003590/187329091-23ec21fb-dae7-4c9b-91b1-9d3cee35c019.png">
`status = 1` 未完成，但是 `current = 1`，达到了该成就的完成值。

两个方法解决这个问题，一是在椰羊中修改当前值，或者在寻空中连续点击达成三次。
<img width="336" alt="image" src="https://user-images.githubusercontent.com/61003590/187329855-0ce1d061-7dcc-49fc-9398-9993efa74290.png">
<img width="158" alt="image" src="https://user-images.githubusercontent.com/61003590/187329932-ccb2137b-ec72-44dc-8082-26c383b65fdb.png">

成就进度显示时寻空使用的方法是**舍去百分位后的数值**。
