### ISSUE TITLE
无边框窗口在游戏卸载重装后失效了，修改注册表解决

### ISSUE THREAD

**Issue by Samonyoge** [xunkong/xunkong#178]
### 问题描述

之前一直打开无边框窗口设置，用工具启动游戏都一切正常。
昨晚卸载游戏重装后，发现此功能失效。没法窗口最大化，副屏点一下别的窗口或者桌面，游戏直接最小化。
寻空版本一直是1.1.7.0，只是游戏本体卸载重装。

后找到原神注册表下的Screenmanager Is Fullscreen mode改为0后用寻空启动成功。
之前是改过注册表就可以了。

### 复现步骤

各种重启各种设置各种打开顺序都试过了

### 系统版本

Windows 10 21H2

### 寻空版本

1.1.7.0

### 日志

LOG最新是8/23的。

**Comment by Scighost** [comment]
没看懂，不过我这测试一切正常。

**Comment by QAQosuy** [comment]
无边框窗口可以用电脑自带的快捷方式
ALT+ENTER（回车）
