### ISSUE TITLE
请问有无小伙伴遇到电脑关机时出现“Task Host Window”

### ISSUE THREAD

**Issue by zeroabc** [xunkong/xunkong#181]
### 问题描述

关机的时候提示“Task Host Window”，然后一直转圈圈不关机，等个一两分钟最后就没关成，回到锁屏状态，类似注销后的状态。
不确定是不是寻空的问题，所以问一下有没有小伙伴遇到类似的问题，排除一下情况
症状已经出现了差不多两周时间了，这段时间内没有装过其它应用类软件，然后更新过系统(包括系统自带软件)，更新过寻空

### 复现步骤

如上

### 系统版本

19044.1949

### 寻空版本

1.1.x

**Comment by Scighost** [comment]
很遗憾，没有。
