### ISSUE TITLE
旅行札记收入记录易读性欠佳

### ISSUE THREAD

**Issue by PurBlu** [xunkong/xunkong#185]
### 问题描述

![image](https://user-images.githubusercontent.com/74239692/189267345-3705a72a-93af-4b34-b423-a671e9964511.png)
当系统处于暗黑模式下时 
旅行札记下收入记录单笔收入信息与数字易读性欠佳

### 复现步骤

略

### 寻空版本

1.2.0.0

**Comment by Scighost** [comment]
https://github.com/xunkong/xunkong/releases/tag/1.2.0  1.2.0.1 版本
