### ISSUE TITLE
寻空内置的游戏启动器会错误提示树脂已满

### ISSUE THREAD

**Issue by PurBlu** [xunkong/xunkong#190]
### 问题描述

通过寻空主界面/任务栏跳转列表/开始菜单所有应用右键菜单启动游戏
寻空会通过应用内横幅/通知 错误的提示“树脂已满”的信息

![image](https://user-images.githubusercontent.com/74239692/189477329-7d6747bc-cb7a-4c73-bc7f-fa3bea55fcdd.png)
_通过程序内启动时出现的横幅。如图所示弹出横幅提示“树脂已满” ，但按实时便笺所提供的正确信息，此时树脂实际为123/160。_

![image](https://user-images.githubusercontent.com/74239692/189477865-74303f87-c0b6-4061-bd43-00c0b798a92a.png)
_通过任务栏跳转列表启动时出现的通知。如图所示推送通知提示“树脂已满” ，但按实时便笺所提供的正确信息，此时树脂实际为6/160。_

### 复现步骤

通过寻空主界面/任务栏跳转列表/开始菜单“所有应用”列表下寻空的右键菜单启动游戏

### 系统版本

Windows 11 Pro 22H2 22622.590

### 寻空版本

1.2.0.1

**Comment by Scighost** [comment]
文本错误，这里的提醒应该是 **参量质变仪可使用**
