### ISSUE TITLE
主页壁纸无法显示：缺少webp解码组件

### ISSUE THREAD

**Issue by Patrick-Ze** [xunkong/xunkong#191]
### 问题描述

这个问题是之前一个问题 #134 的衍生。看起来之前一直无法显示图片是因为缺少解码器

更新到 寻空~夜兰版~1.2.1.0版 后打开主页会提示“缺少webp解码组件”，但是我不知道如何为寻空安装webp解码组件，因为我用寻空的保存壁纸功能保存的webp格式壁纸是能打开并显示的（补充：用Edge浏览器打开）
![image](https://user-images.githubusercontent.com/19711799/189491804-be305d73-cd06-4a99-b052-aa5c264fdb89.png)

可能和我使用的是LTSC系统有关系（`Windows 10 LTSC 10.0.19044.1586`），想请教一下，这种情况如何安装webp解码组件？

非常感谢！

### 复现步骤

1. 启用主页壁纸功能
2. 打开寻空主页

### 截图

![image](https://user-images.githubusercontent.com/19711799/189492011-81146359-3f80-445b-8b84-08fbc889a9e8.png)

### 系统版本

Windows 10 LTSC 10.0.19044.1586

### 寻空版本

1.2.1.0

### 日志

[log_20220911_001154.txt](https://github.com/xunkong/xunkong/files/9540836/log_20220911_001154.txt)

**Comment by Scighost** [comment]
解决方法很简单，安装这个就行 https://www.microsoft.com/store/productId/9PG2DK419DRG

**Comment by Patrick-Ze** [comment]
解决了，谢谢大佬~
