### ISSUE TITLE
首页布局&实时便笺账号切换

### ISSUE THREAD

**Issue by Fachep** [xunkong/xunkong#193]
### 你的建议

![image](https://user-images.githubusercontent.com/31302548/189516260-95eb4fe3-4dc3-4e9c-85bd-d285c0275acd.png)
如图 首页第一屏十分空旷但看不到下面的养成计划，另外实时便笺总是显示我同cookie的弃坑小号（大号b服，小号官服，米游社设置默认b服的号）
可否将两块卡片并排布局，并且提供切换便笺账号的选项

**Comment by Scighost** [comment]
多添加几个账号或者养成计划就不会觉得空旷了。

单账号绑定多个角色的情况我也没遇到过，如果你信得过，可以把 cookie 通过邮件发给我调试一下。

**Comment by Fachep** [comment]
已发送

**Comment by Scighost** [comment]
已解决，为了你的账号安全，请在米游社退出登录，或直接修改密码。
