### ISSUE TITLE
命之座图片素材调用有误，小修下就可以了

### ISSUE THREAD

**Issue by pbxs666** [xunkong/xunkong#194]
### 问题描述
中秋佳节期间冒昧打扰，实在抱歉😊。作者大大还是先好好过节吧，问题我先撂到这里，以后修就行啦、

如题，部分角色的3和5（提高技能等级）的命之座图片调用有误，误调用了固有天赋1和2（也就是全部天赋里的4和5）的图片。
因为第3和5命之座是提升技能等级的，所以图片一般是对应技能（战斗天赋2和3）的图片，凝光是例外，命之座5的图片和对应技能的图片不一样，有些许调整变化。

我把目前所有的角色的图片一一与游戏本体、米游社里我的角色板块、米游社观测枢里wiki界面里命之座的图片做了对比，发现有以下角色存在问题（按照寻空里角色图鉴由左到右的顺序排列）：

久岐忍、雷电将军、宵宫、罗莎莉亚、钟离、砂糖、班尼特、行秋、芭芭拉、凯亚（凯亚的命之座图片没问题，但战斗天赋3-元素爆发图片有问题，疑似是早期的图标）

### 复现步骤

“我的角色”板块刚出就有的问题了，不过最早发现是雷神的好像有点问题，但是我是0命，命之座的图片上有上锁的图层，看不太清楚，也就没提issue。
这次1.2.0大版本更新加上“角色图鉴”功能后，可以清楚查看命之座图片了，发现确实有问题，顺手检查了列表所有角色，就来提issue了😁。

### 截图

以雷电将军为例说明（角色信息借用下其他满命大佬的😂）
游戏内命之座
![雷神-游戏](https://user-images.githubusercontent.com/47630168/189532145-84be53e0-f38b-41fe-a686-c449f16bc1d8.png)

米游社-我的角色板块
![雷神-米游社](https://user-images.githubusercontent.com/47630168/189532663-37812c83-5bdd-4b78-ae13-baa5f8dc5577.png)

米游社-观测枢-wiki
![雷神-wiki](https://user-images.githubusercontent.com/47630168/189532199-e225b3a8-45f3-4079-85e2-3217537f6a54.png)

最后是寻空里的
![雷神-寻空](https://user-images.githubusercontent.com/47630168/189532215-40d9f76d-e9ec-4537-b419-5e421a9ead1b.png)

可以看到，寻空里3和5命的图片是固有天赋1和2的，调取错误。

### 寻空版本

侧载版 1.2.1.0

**Comment by pbxs666** [comment]
我不知道作者大大开发时背后是怎样处理的，是每个命之座都专门准备了一张图片，还是说对3和5这种特殊命之座直接采用了程序调用固有天赋图片的做法，亦或是从米游社接口调用。
不论是那种做法，想来处理9个角色共18张图片应该工作量不是太大，辛苦作者了。

另外，我还是想求求旅行者的天赋详细信息不再考虑下加上吗？虽然我之前已经提过一次了。
旅行者目前只需要准备4套天赋命座信息，判断当前元素属性切换就好了。

元素属性现在寻空能正确获取并判断吧，其他角色的命座解锁情况和天赋等级数据都能获取到，旅行者应该也可以吧。

所以还是想提下要求，完善下“我的角色”和“角色图鉴”里旅行者的信息。

谢谢大佬！！！

**Comment by Scighost** [comment]
细节，真的太细节了！
这种问题都能够发现，而且还每张图都对比了一遍，真是辛苦你了。

经过我的测试，图片本身没有问题，有问题的是缓存图片时**出现了哈希碰撞**。
殊胜之御体：https://file.xunkong.cc/genshin/talent/UI_Talent_S_Shougun_06.png 
真影旧事：https://file.xunkong.cc/genshin/talent/UI_Talent_U_Shougun_02.png
上面两张图片是正确的，但是我用的[社区工具包](https://github.com/CommunityToolkit/WindowsCommunityToolkit)的图片缓存功能的哈希计算算法太简单，上面两个 url 的哈希值是一样的，被认为是同一个文件。

<img width="536" alt="image" src="https://user-images.githubusercontent.com/61003590/189533762-f872a479-c86b-43ed-8728-1738f51ebdc4.png">

通过修改图片 url 解决这个问题很麻烦，修改哈希算法则比较简单，只能在下个版本中修复。

**Comment by pbxs666** [comment]
OK，这个不急，不影响使用，慢慢修就行啦。
