### ISSUE TITLE
请求添加旅行者的天赋和命座数据

### ISSUE THREAD

**Issue by Scighost** [xunkong/xunkong#195]
我不知道作者大大开发时背后是怎样处理的，是每个命之座都专门准备了一张图片，还是说对3和5这种特殊命之座直接采用了程序调用固有天赋图片的做法，亦或是从米游社接口调用。
不论是那种做法，想来处理9个角色共18张图片应该工作量不是太大，辛苦作者了。

另外，我还是想求求旅行者的天赋详细信息不再考虑下加上吗？虽然我之前已经提过一次了。
旅行者目前只需要准备4套天赋命座信息，判断当前元素属性切换就好了。

元素属性现在寻空能正确获取并判断吧，其他角色的命座解锁情况和天赋等级数据都能获取到，旅行者应该也可以吧。

所以还是想提下要求，完善下“我的角色”和“角色图鉴”里旅行者的信息。

谢谢大佬！！！

_Originally posted by @pbxs666 in https://github.com/xunkong/xunkong/issues/194#issuecomment-1242978257_

**Comment by Scighost** [comment]
旅行者有7中元素类型，需要修改现有的数据模型，我只能说会考虑一下。

**Comment by pbxs666** [comment]
嗯嗯，要改数据模型的话那确实增加麻烦了。

“我的角色”板块只显示当前旅行者的属性和天赋及命之座信息，确实要修改下数据结构。但是“角色图鉴”里就不用麻烦了，这里按理说会显示所有角色的信息，目前空和荧的信息都有，只是不全而已，那我不妨大胆提一个建议：

角色图鉴里的不同元素属性的旅行者当成独立角色，各占一个角色卡槽，（这里的信息应该是从米游社提取的吧，都是固定的数据，不会因为账号的不同而改变，不需要读取该账号上角色的天赋等级之类的数据）
目前就可以分成风荧、岩荧、雷荧、草荧以及风空、岩空、雷空和草空。共8个独立角色，互不干扰，按照我的理解就是数据库添加8条数据，不知道可不可行，id冲不冲突。

如果作者想的是做成更完美的样子，比如在旅行者页面上专门添加一个切换元素的按钮，或者是米游社wiki那样，把各元素的信息数据塞到一个页面，那就确实需要改数据结构了。

不管怎样，就静候佳音啦。
