### ISSUE TITLE
点击磁贴及磁贴后台均无法刷新

### ISSUE THREAD

**Issue by Darklighture** [xunkong/xunkong#197]
### 问题描述

寻空0.x版本的时候开始使用的是侧载版，磁贴刷新无问题，寻空更新到1.03，导入0.x的数据后，卸载了0.x版，才发现点击磁贴及磁贴后台均无法刷新（0.x版的磁贴能正常刷新），于是又下载了商店版，卸载了侧载版，同样还是不行，只好使用了寻空小组件，终能正常刷新，但更新1.21之后，点击磁贴及磁贴后台均无法刷新，寻空小组件亦是如此
更新一下 寻空小组件后台能刷新，但大约半小时才刷新一次，不像之前刷新较快

### 复现步骤

添加磁贴后点击磁贴不会刷新，等待很长时间后磁贴也不会刷新，重新添加磁贴才能刷新

### 截图

![微信截图_20220913114719](https://user-images.githubusercontent.com/33174501/189804685-fb7b7425-a934-4988-9629-4ac538f44f16.png)

### 系统版本

Windows 10 专业版 21H2

### 寻空版本

1.21

### 日志

[log_20220913_114446.txt](https://github.com/xunkong/xunkong/files/9553404/log_20220913_114446.txt)

**Comment by Patrick-Ze** [comment]
虽然和你的情况可能不一定一致，不过我通常是寻空无法联网（比如我压根就没联网）的时候会报`不知道这样的主机`
