### ISSUE TITLE
建议添加米游社半自动签到

### ISSUE THREAD

**Issue by smallg0at** [xunkong/xunkong#202]
### 你的建议

目前米游社自动签到基本处于必定被风控状态，但是还是会弹出提示信息。
是的我知道可以关，但是看到之后拿出手机总感觉有些不方便，因此希望能添加一个 Web 签到功能。

## 描述

移除当前的全自动签到机制，发送消息变为签到提醒。

点击通知后，单独小窗口内打开米游社签到网页 `https://webstatic.mihoyo.com/bbs/event/signin-ys/index.html?bbs_auth_required=true&act_id=e202009291139501` 并顺便伪装下 UA(*) 来让服务器认为客户端是米游社，由用户完成所有操作。

(*) 猜测官方用这种方法检测，不知道是不是这样。

**Comment by kengwang** [comment]
经过测试, 假如用了米游社上获取到的 UA 可以不触发风控且稳定签到
