### ISSUE TITLE
【BUG】成就管理的搜索栏文字在选中状态下输入文字会闪退

### ISSUE THREAD

**Issue by slaners** [xunkong/xunkong#204]
### 问题描述

在 成就管理 的 搜索栏 输入文字后，全选文字，然后开始打字，软件会卡住，然后闪退

### 复现步骤

成就管理-搜索栏，输入文字，全选，再次输入文字

### 系统版本

windows 10 21H1

### 寻空版本

1.2.1.0

### 日志

Xunkong文件夹下没有log文件夹

**Comment by Scighost** [comment]
无法复现这个问题
