### ISSUE TITLE
鼠标滚轮无效

### ISSUE THREAD

**Issue by LHDYL** [xunkong/xunkong#206]
### 问题描述

在寻空内鼠标滚轮无效，但是我的鼠标滚轮在其他使用中都是正常的。这种情况是正常的吗？如果异常有什么解决办法。

### 复现步骤

打开寻空随便点一个功能后

### 寻空版本

1.2.1

**Comment by Scighost** [comment]
系统功能有问题，重装可以解决。

**Comment by LHDYL** [comment]
请问是重装软件还是重装系统？

**Comment by misaka1002** [comment]
我也是这样 重装也一样额

**Comment by Scighost** [comment]
重装系统，但是不建议这样做
