### ISSUE TITLE
软件内vbs文件调用wscript.exe

### ISSUE THREAD

**Issue by Honokasumi** [xunkong/xunkong#210]
### 问题描述

安装商店版后，每15分钟左右我的火绒便会通知我wscript.exe启动，当时没想太多直接禁用了。刚刚在查看日志的时候发现启动wscript.exe的vbs文件是寻空的，请问寻空是使用vbs文件启动wscript.exe来获取树脂等刷新信息的吗？

### 复现步骤

在火绒内查看日志后发现

### 截图

![image](https://user-images.githubusercontent.com/48857357/192536117-e5a734cd-e6e4-4899-820a-54f500828c2a.png)

### 系统版本

Windows 10 21H2

### 寻空版本

1.2.1.0

**Comment by Scighost** [comment]
是的，用来启动签到和刷新磁贴的任务。
