### ISSUE TITLE
获取祈愿记录失败

### ISSUE THREAD

**Issue by duanfayoung** [xunkong/xunkong#214]
### 问题描述

在点击“获取记录”下拉菜单中的“启动代理”后，会弹出“有问题”弹窗。内容描述为：代理服务的端口为localhost:10086,但是系统代理设置出错。文字下方有“打开代理设置”的按钮。

### 复现步骤

在点击“获取记录”下拉菜单中的“启动代理”后，会弹出“有问题”弹窗。内容描述为：代理服务的端口为localhost:10086,但是系统代理设置出错。文字下方有“打开代理设置”的按钮。

### 截图

![QQ截图20220928210056](https://user-images.githubusercontent.com/56600078/192785119-ce177813-afbf-42bd-b9ca-0141b29b20d1.png)
![QQ截图20220928210127](https://user-images.githubusercontent.com/56600078/192785203-399923a5-1cbf-4c9a-baa7-3e68f25821e2.png)
![image](https://user-images.githubusercontent.com/56600078/192785270-3e7c90bd-2c7f-461d-b73f-95d2ab457867.png)

### 系统版本

Windows 11 21H2

### 寻空版本

1.2.1.0

### 日志

[log_20220928_211631.txt](https://github.com/xunkong/xunkong/files/9665331/log_20220928_211631.txt)

**Comment by liubai2333** [comment]
一毛一样啊，兄弟你解决了吗？
