### ISSUE TITLE
win10用Yae导入到寻空会有问题

### ISSUE THREAD

**Issue by linxia1314** [xunkong/xunkong#215]
### 问题描述

我是win是下的侧载版，然后寻空自带的成就导入工具yae版本是2.1，最新版为2.2。并且我用了2.2导入进寻空会有bug，没有那个操作窗口。

### 复现步骤

反复重试多次无效

### 系统版本

windows 10 20H2

### 寻空版本

最新版

### 日志

我的文档\Xunkong\Log\App\

**Comment by Scighost** [comment]
把下面这一段输入到浏览器地址栏，然后回车，看看会发生什么：
xunkong://import-achievement?caller=YaeAchievement&from=clipboard

**Comment by linxia1314** [comment]
提示 数据解析失败

**Comment by linxia1314** [comment]
![image](https://user-images.githubusercontent.com/79906623/193418423-54cea7a7-9680-4e7d-a4b9-f6170798f938.png)

**Comment by Scighost** [comment]
解析失败表明url启动没问题。
用Yae最后选择导出至时，输入 7（没错就是7），会提示已保存一个json文件，然后在寻空里导入这个文件，顺便把这个文件发我一份。

**Comment by linxia1314** [comment]
[export-20221002002137-raw.txt](https://github.com/xunkong/xunkong/files/9690746/export-20221002002137-raw.txt)
好的

**Comment by Scighost** [comment]
我测试了 v2.2 的 YaeAchievement，一切正常，能直接导入到寻空。
上面导出的 json 文件中需要把首字母改成小写才能被寻空正常识别。

**Comment by Scighost** [comment]
> 把下面这一段输入到浏览器地址栏，然后回车，看看会发生什么：
> xunkong://import-achievement?caller=YaeAchievement&from=clipboard

或者在 Yae 中输入 5 后，重复这一步。

**Comment by qq786184923** [comment]
没用 进行到5回车后 寻空无任何反应  寻空是今晚更新的最新版本 导出软件也是最新版本 导出软件的群作者让我来评论
