### ISSUE TITLE
浅/深色切换导致的文字颜色异常

### ISSUE THREAD

**Issue by pbxs666** [xunkong/xunkong#218]
### 问题描述

浅/深色切换时会导致部分蓝色的文字描述颜色异常，例如武器描述里的蓝色数字部分，先上图：
①以深色模式启动时
![1](https://user-images.githubusercontent.com/47630168/193435754-bc955567-a8fd-4f77-b105-a3fbc05d8bde.png)

②深色转浅色时
![2](https://user-images.githubusercontent.com/47630168/193435782-1a36c8cc-79ee-49e5-b572-76007789a54a.png)

③以浅色模式启动时
![3](https://user-images.githubusercontent.com/47630168/193435790-089ca614-fdd5-4113-8da0-e667fd2b0e91.png)

④浅色转深色时
![4](https://user-images.githubusercontent.com/47630168/193435801-f8007b11-1756-4743-9f50-26e22db88c5b.png)

可以看到②的情况下描述里的数字部分几乎看不清。
这是详细对比
![5](https://user-images.githubusercontent.com/47630168/193435843-589f0522-744e-48d8-b4bf-82da6fd79d46.png)

### 复现步骤

以深色或浅色启动时，颜色不会有任何问题，如果应用运行期间发生主题模式切换，就会出现文字颜色失常。

### 系统版本

Windows 10 20H2

### 寻空版本

侧载版1.2.1.0

**Comment by pbxs666** [comment]
会不会是主题色切换时之换了背景色，蓝色的文字颜色没切换导致的。

**Comment by Scighost** [comment]
这里的彩色文字不是使用 XAML 中定义的颜色资源，而是直接在代码中给定颜色值，没有办法和黑白颜色一样随着系统主题的变化切换颜色。

**Comment by pbxs666** [comment]
> 这里的彩色文字不是使用 XAML 中定义的颜色资源，而是直接在代码中给定颜色值，没有办法和黑白颜色一样随着系统主题的变化切换颜色。

哦，这样啊。其实也不影响，切换主题色后大不了重启下软件就好了。
