### ISSUE TITLE
无法获取起源记录

### ISSUE THREAD

**Issue by f59375543** [xunkong/xunkong#220]
### 问题描述

和以往完全一样的操作，结果现在获取的结果是authkey timeout (-101)

### 复现步骤

从上个月底开始就报错了

### 寻空版本

1.2.2.0

**Comment by caoyinghong** [comment]
和你一样的问题

**Comment by Nikaple** [comment]
我也遇到了同样的问题，删掉缓存文件后解决了：

1. 先找到 YuanShen.exe 的位置，然后找到缓存文件夹 `YuanShen_Data\webCaches\Cache\Cache_Data`，例如在我电脑上的路径为：`D:\Genshin Impact\Genshin Impact Game\YuanShen_Data\webCaches\Cache\Cache_Data`
2. 删除 Cache_Data 文件夹内的所有文件
3. 退出游戏并重新打开祈愿历史记录界面
4. 重新从寻空中获取祈愿记录
