### ISSUE TITLE
”我的角色“ 会显示所有角色

### ISSUE THREAD

**Issue by BaldnessBaby** [xunkong/xunkong#222]
### 问题描述

进入 “我的角色” 页面时，上方的角色会显示所有角色，并非 “我的角色”，虽然非拥有的角色会显示等级为 “0”，但也会产生一定困惑，错以为拥有了本没有的角色。

### 复现步骤

在 “我的角色” 页面，在角色头像上滚动滚轮，后方便会出现所有角色。

**Comment by pbxs666** [comment]
“**我的角色**”这个功能很早期的版本就有了，当时没有“**角色图鉴**”这个功能模块，我猜当时作者把所有角色都加上可能也是为了方便查看所有角色的技能和命座描述吧。

其实就“**关于显不显示未获得的角色**”这个问题来说”，无非两个方面：
_全部显示_：相较**角色图鉴**加载速度更快，更方便查看角色的天赋和命座，即便这个角色没抽到，也可能提前考虑以分析技能机制嘛。再说了，啥角色有啥角色目前还没有自己应该很清楚吧😜，而且未获得的角色按照5星4星顺序都在最后面排着哩

_仅显示已获得的角色_：也没问题，毕竟**角色图鉴**功能已经实装了，虽然我感觉加载速度比**我的角色**慢了点，但不影响。
