### ISSUE TITLE
无法通过URL获取祈愿记录

### ISSUE THREAD

**Issue by chtholist** [xunkong/xunkong#223]
### 问题描述

通过URL获取祈愿记录时，会显示【Url does not fit the requirement.(-1)】
URL为https://hk4e-api.mihoyo.com/event/gacha_info/
在非小球和snap.genshin上，该URL均能正常获取祈愿记录

### 复现步骤

无

### 截图

![image](https://user-images.githubusercontent.com/56428448/194438524-e50046dd-fb88-407c-a4fa-e31291938b98.png)
![image](https://user-images.githubusercontent.com/56428448/194438583-22f34330-eeb3-40b4-8709-a9194257cd1f.png)

### 系统版本

WIN10 19044

### 寻空版本

1.2.2.0

**Comment by overbluesky** [comment]
改一下域名就能用了，把event前面的域名改成webstatic.com/hk4e/就可以了

**Comment by overbluesky** [comment]
（就是标准抓包链接的那个域名，我怕我记错了）
