### ISSUE TITLE
角色图鉴中雷电将军的语音对应错误

### ISSUE THREAD

**Issue by Big-Cake-jpg** [xunkong/xunkong#224]
### 问题描述

出现问题的语音是【重受击·其一】、【重受击·其二】

两个语音与其所在的位置是相反的

### 复现步骤

1. 打开寻空
2. 导航到角色图鉴
3. 点击雷电将军
4. 滚动到“重受击”语音

### 截图

![image](https://user-images.githubusercontent.com/76810494/194695333-34ffb7a8-e8d8-4720-857f-c0c50e186d21.png)

### 系统版本

Windows 11 Insider Preview, Build 25211

### 寻空版本

1.2.2.0

### 日志

无最新日志产出

**Comment by pbxs666** [comment]
我以前还经常听语音，那时候**角色图鉴**还没实装，都是去米游社观测枢听的。现在寻空里有了，更方便了，反而听的少了的。语音雷电将军这个还真没发现。

这个是米游社观测枢搞错了，受重击的语音按顺序是无礼，荒谬。米游社里雷电将军页面的文字顺序是反的，_荒谬和无礼_，语音对应的自然也就反了，而寻空的语音都是从米游社按顺序调取的，这个自然就对不上了。

应该要改下链接吧
