### ISSUE TITLE
关于Windows11磁贴

### ISSUE THREAD

**Issue by 199Sie** [xunkong/xunkong#226]
### 你的建议

希望可以不要检测到系统为windows11就不允许开启动态磁贴功能，Windows11可以通过livetilesanywhere explorerpatcher等工具继续调用Windows 10的动态磁贴用来查看树脂。我使用寻空很长时间了，大概是Windows端最好用的关于原神的第三方软件，希望作者能移除其限制，谢谢

(Looking forward your reply)

**Comment by Scighost** [comment]
已支持，但是你别急，最近没有发布新版本的计划。

**Comment by 555wmn** [comment]
> 已支持，但你的版本别急，最近没有发布新的计划。

我用ExplorerPatcher恢复了win11磁贴功能，但是用寻空添加磁贴报错：UnauthorizedAccessException-固定磁贴到开始菜单拒绝访问。(0x80070005 (E_ACCESSDENIED))。寻空用管理员打开的

**Comment by Scighost** [comment]
> 我用ExplorerPatcher恢复了win11磁贴功能，但是用寻空添加磁贴报错：UnauthorizedAccessException-固定磁贴到开始菜单拒绝访问。(0x80070005 (E_ACCESSDENIED))。寻空用管理员打开的

不要用管理员权限

**Comment by 555wmn** [comment]
> > 我用ExplorerPatcher恢复了win11磁贴功能，但是用寻空添加磁贴报错：UnauthorizedAccessException-固定磁贴到开始菜单拒绝访问。(0x80070005 (E_ACCESSDENIED))。寻空用管理员打开的
> 
> 不要用管理员权限

不用管理员他就报了这个：COMException -固定磁贴到开始菜单
操作员或系统管理员拒绝了请求。(0x800710E0)

**Comment by Scighost** [comment]
> 不用管理员他就报了这个：COMException -固定磁贴到开始菜单
> 操作员或系统管理员拒绝了请求。(0x800710E0)

这场面我真没见过.jpg

**Comment by 555wmn** [comment]
> > 不用管理员他就报了这个：COMException -固定磁贴到开始菜单
> > 操作员或系统管理员拒绝了请求。(0x800710E0)
> 
> 这场面我真没见过.jpg

找了一圈应该是用ExplorerPatcher恢复磁贴会有一些问题，这是那个作者的回答https://github.com/valinet/ExplorerPatcher/discussions/1037应该是这个，看麻了，还是算了
