### ISSUE TITLE
输出为json格式报错

### ISSUE THREAD

**Issue by 1164844282** [xunkong/xunkong#227]
### 问题描述

祈愿记录输出为json格式报错

### 复现步骤

导出为excel格式没有报错
导出为json格式时报错

### 截图

![图片](https://user-images.githubusercontent.com/52785205/194911278-46d19c54-8232-4cb7-a045-05d0c752310b.png)

### 系统版本

Windows 10 21H2

### 寻空版本

1.2.2.0

### 日志

[log_20221011_000649.txt](https://github.com/xunkong/xunkong/files/9747527/log_20221011_000649.txt)

**Comment by Scighost** [comment]
因为导出的记录中存在多种语言
