### ISSUE TITLE
《角色图鉴》界面的交互问题

### ISSUE THREAD

**Issue by HaRiGiToU** [xunkong/xunkong#228]

**Comment by pbxs666** [comment]
具体是什么交互问题？这不说清楚没法给你出主意啊

**Comment by HaRiGiToU** [comment]
![image](https://user-images.githubusercontent.com/82216377/195796990-8dcadbf3-087a-4f10-96e0-62d31d38973a.png)

**Comment by HaRiGiToU** [comment]
图鉴那个问题没事了，应该是我的问题，图片这个问题是正常的吗

**Comment by pbxs666** [comment]
> 图鉴那个问题没事了，应该是我的问题，图片这个问题是正常的吗

这……，还真没遇到这个问题，等作者回复吧
