### ISSUE TITLE
点击祈愿记录-管理记录后无法快速返回

### ISSUE THREAD

**Issue by zbodo** [xunkong/xunkong#233]
### 问题描述

在祈愿记录管理页面无法使用鼠标上的'后退键'或键盘上的‘ESC键’返回上一页面，只能点击应用左上角的按钮

### 复现步骤

点击祈愿记录-管理记录后无法使用鼠标上的后退键或键盘上的ESC键返回上级页面

### 寻空版本

1.2.2.0

**Comment by Scighost** [comment]
你反馈问题的哪个版本没有支持快捷后退的功能，现在有了但是只支持esc和鼠标中键，我没有带返回键的鼠标。
