### ISSUE TITLE
希望可以添加多个账号直接切换登录的功能

### ISSUE THREAD

**Issue by Meizhi-hua** [xunkong/xunkong#237]
### 你的建议

隔壁Snap Genshin转来的，那边是有这个功能的，切换账号登录游戏里的账号也会变，不需要重新输入账号密码。这边可以出一个类似的功能嘛

**Comment by Askwind** [comment]
本身就有啊，在左上角添加账号后就可以切换了

**Comment by Meizhi-hua** [comment]
> ## 不过更新版本后 取消了，确实建议加回来
> 以前本身就有啊，在系统设置添加账号后就可以切换了。

哈哈 这波回马枪
