### ISSUE TITLE
网页快捷方式中BASE64形式的图标无法解析

### ISSUE THREAD

**Issue by MeiVinEight** [xunkong/xunkong#241]
### 问题描述

如题，寻空的网页快捷方式中设置网页图标时，如果图片的URL是BASE64格式的静态数据，如`data:image/png;base64,xxxx`则不会解析

### 复现步骤

在米游社大地图中找到网页图标，复制URL
![image](https://user-images.githubusercontent.com/57023439/197330835-20d2decc-18a8-4290-a622-ae15d7b37cd3.png)

发现是一个BASE64格式的静态数据，使用工具可以解析
![image](https://user-images.githubusercontent.com/57023439/197330892-2309d95b-96cd-4561-8205-a1242c841264.png)

将URL复制到寻空的图标栏中
![image](https://user-images.githubusercontent.com/57023439/197331118-e1862f9a-88b9-4d26-8a24-6344d7b6b96b.png)

点击保存
![image](https://user-images.githubusercontent.com/57023439/197331004-60b72756-e392-464d-9922-4bb12f8df340.png)

在快捷方式中并没有加载出图标
![image](https://user-images.githubusercontent.com/57023439/197331294-62c8f1ce-47bc-4b23-857a-1aebb201d9d5.png)

### 截图

如上

### 系统版本

Windows 11 22H2

### 寻空版本

1.2.2.0

### 日志

无日志

### 备注

使用获取图标获取到的链接并不是图标链接
![image](https://user-images.githubusercontent.com/57023439/197338244-2ddeb409-05f7-4f96-af4d-c820d375b825.png)
![image](https://user-images.githubusercontent.com/57023439/197338267-3dfee80d-5df0-4126-b3bb-08dbe1f1d868.png)

**Comment by pbxs666** [comment]
@MeiVinEight 用这个，你的图标链接就没找对
https://webstatic.mihoyo.com/ys/app/interactive-map/mapicon.png

**Comment by pbxs666** [comment]
不过BASE64无法解析也确实是个问题

**Comment by Scighost** [comment]
显示图片的控件不支持base64的图片形式
