### ISSUE TITLE
我的角色界面bug

### ISSUE THREAD

**Issue by AssassinVIX** [xunkong/xunkong#246]
### 问题描述

文件没动过，界面自己就白了一个人物没有

### 复现步骤

进入软件点击我的角色后直接报错

### 截图

![image](https://user-images.githubusercontent.com/77925292/197735419-e0439b61-f5c4-417d-922c-4886c1330c62.png)

### 系统版本

windows 11 22H2

### 寻空版本

1.2.2.0

**Comment by Scighost** [comment]
网络不好，必要的数据文件没有下载完。
换一个运营商或自己挂梯子。
