### ISSUE TITLE
【祈愿记录】从缓存文件获取记录报错：autokey timeout(-101)

### ISSUE THREAD

**Issue by Joy6724** [xunkong/xunkong#247]
### 问题描述

从缓存文件获取记录报错：autokey timeout(-101)

### 复现步骤

祈愿记录-获取记录-从缓存文件

### 截图

![image](https://user-images.githubusercontent.com/15258091/198019685-54f3eafd-932b-4a5a-a484-fdc95082aaf4.png)

### 系统版本

Windows 21H2

### 寻空版本

1.2.2.0

**Comment by Aileilaya** [comment]
使用获取记录-使用代理可解决此问题。
