### ISSUE TITLE
[suggestion]支持UI中字体自定义

### ISSUE THREAD

**Issue by modenicheng** [xunkong/xunkong#250]
### 支持字体自定义

如题，建议加个导入字体的入口，然后全局应用什么的。
可以解决 https://github.com/xunkong/xunkong/issues/238 里面提及的问题（因为网上可以找到对应字体，而且这大概不会有版权问题，反正又不是软件内置的）
> 除了全局应用，我觉得每个模块可以单独设置字体。但是我没有WinUI的开发经验，也不好说这么整行不行……

**Comment by Scighost** [comment]
很好的建议，但是我做不到。
尝试使用过 汉仪文黑 85W，因为应用内有不同的字体大小和粗细，再加上 汉仪文黑不是等宽字体，实际显示效果不如 Harmony OS Sans。

**Comment by Scighost** [comment]
#271
