### ISSUE TITLE
引进非小酋的祈愿查询方法

### ISSUE THREAD

**Issue by overbluesky** [xunkong/xunkong#256]
### 你的建议

非小酋书签获取祈愿链接的方法比较好用 主要是能避开抓包一些奇奇怪怪的问题（深受困扰）。然后寻空用非小酋那里搞的链接只要把域名改成寻空能用的那个就行了，或者大大能不能把非小酋那里的域名添加到合法URL中

**Comment by Scighost** [comment]
已支持 `https://hk4e-api` 开头的链接
