### ISSUE TITLE
Windows端大倍放大导致的显示异常

### ISSUE THREAD

**Issue by A41511** [xunkong/xunkong#257]
### Windows端大倍率缩放导致的显示异常

缩放问题导致的以下三个问题：
1.命座和技能显示丢失（放大倍率越高显示的越少）
2.圣遗物显示不全（被挤出显示区域）
3.无法用除了拉滚动条之外的任何方式上下滑动界面

### 复现步骤

我设备的屏幕是10吋2560x1600的面板，因为日常阅读需要会开启225%缩放，我发现当缩放在175%以上的时候“我的角色”页面排版会出错

### 截图

![新建 BMP 图像](https://user-images.githubusercontent.com/117516401/200117081-bf782272-4122-4d1f-9f19-7bc38943927e.jpg)

### 系统版本

Windows 11 22H2

### 寻空版本

1.2.2.0

**Comment by Scighost** [comment]
我还真没见过这么高的缩放率，凑合着用吧。

<img width="443" alt="image" src="https://user-images.githubusercontent.com/61003590/201512445-c772e35a-d57e-4d01-b24f-f69c1a6f43d8.png">
