### ISSUE TITLE
导出为Excel格式出错

### ISSUE THREAD

**Issue by FanJZSS** [xunkong/xunkong#259]
### 问题描述

在使用祈愿记录管理的导出功能时出错

### 复现步骤

打开寻空，祈愿记录，管理记录，导入导出，选择导出模板UIGF Excel v2.2，导出

### 截图

![QQ截图20221106152645](https://user-images.githubusercontent.com/96369018/200159478-6ce238f7-d9df-4a57-917d-93b06abbaee1.jpg)

### 系统版本

Windows 10 LTSC 1809

### 寻空版本

寻空侧载版1.2.2.0

### 日志

[log_20221106_153000.txt](https://github.com/xunkong/xunkong/files/9945335/log_20221106_153000.txt)

### 备注

使用json导出是正常的

**Comment by Scighost** [comment]
<img width="284" alt="image" src="https://user-images.githubusercontent.com/61003590/201122110-912a4229-9f27-4d46-bd22-3a71a30abb0a.png">
升级到 2004 (19041) 及以上版本即可解决这个问题

**Comment by FanJZSS** [comment]
更新到1.2.3.1可以导出了，谢谢开发者
