### ISSUE TITLE
主页实时便笺突然出错

### ISSUE THREAD

**Issue by simousis** [xunkong/xunkong#264]
### 问题描述

添加了两个账号的实时便签，一个正常显示，另外一个今天突然显示1034，如截图。删除账号重新获取后还是1034

### 复现步骤

无法复现，一直有1034

### 截图

![1667836760879](https://user-images.githubusercontent.com/73791302/200356268-206f1150-0aac-451a-9dda-9729592fff93.png)

### 系统版本

WIN 10 21H1

### 寻空版本

1.2.2.0

### 日志

[log_20221107_061119.txt](https://github.com/xunkong/xunkong/files/9953360/log_20221107_061119.txt)

**Comment by hcy0317** [comment]
这个应该是米忽悠又添加了新的风控限制，你要去米游社验证一下，还会提示你修改密码呢

**Comment by MaxwellYe0815** [comment]
用手机米游社进入”我的角色”界面，会提示你账号异常，要求使用拼图滑块验证码进行验证，验证完就好了
可能是请求次数过多被风控了？

**Comment by simousis** [comment]
> 这个应该是米忽悠又添加了新的风控限制，你要去米游社验证一下，还会提示你修改密码呢

OK,搞定了。多谢

**Comment by simousis** [comment]
> 用手机米游社进入”我的角色”界面，会提示你账号异常，要求使用拼图滑块验证码进行验证，验证完就好了 可能是请求次数过多被风控了？

搞定了，多谢。
