### ISSUE TITLE
我的角色页面技能等级显示及小组件问题

### ISSUE THREAD

**Issue by MafiaAce** [xunkong/xunkong#266]
### 问题描述

高命角色的技能等级显示有问题，技能等级最高一直是10级；小组件添加一次帐号之后，再打开就一直显示没有账号，小组件也一直显示出错。有没有可能利用一下WIN11的桌面侧边栏里的小组件，我记得微软说过支持第三方

### 截图

![屏幕截图 2022-11-10 193345](https://user-images.githubusercontent.com/45426360/201080950-66947568-e191-4fb9-b6fb-050de171bfe2.png)

### 寻空版本

1.2.2

**Comment by Scighost** [comment]
最高等级是10级，名座算额外加成。

什么错误？

22H2 还不支持小组件

**Comment by MafiaAce** [comment]
> 
元素战技和元素爆发应该额外+3吧~  小组件的事儿可能是我记错了~~
