### ISSUE TITLE
实时便签显示（出错1034）

### ISSUE THREAD

**Issue by LarryLeee** [xunkong/xunkong#267]
### 问题描述

很久之前便签更新就显示1034，我重试了更新cookie，也尝试了删除重新添加，通过寻空登录添加，均失败。

### 复现步骤

重新打开登陆依然出错。

### 系统版本

Windows10 22H2

### 寻空版本

1.2.2.0

### 日志

[log_20221110_183515.txt](https://github.com/xunkong/xunkong/files/9981437/log_20221110_183515.txt)
[log_20221110_185115.txt](https://github.com/xunkong/xunkong/files/9981438/log_20221110_185115.txt)
[log_20221110_190714.txt](https://github.com/xunkong/xunkong/files/9981439/log_20221110_190714.txt)
[log_20221110_192317.txt](https://github.com/xunkong/xunkong/files/9981440/log_20221110_192317.txt)
[log_20221110_193916.txt](https://github.com/xunkong/xunkong/files/9981441/log_20221110_193916.txt)
[log_20221110_195515.txt](https://github.com/xunkong/xunkong/files/9981442/log_20221110_195515.txt)
[log_20221110_201114.txt](https://github.com/xunkong/xunkong/files/9981443/log_20221110_201114.txt)
[log_20221110_202715.txt](https://github.com/xunkong/xunkong/files/9981444/log_20221110_202715.txt)
[log_20221110_211511.txt](https://github.com/xunkong/xunkong/files/9981445/log_20221110_211511.txt)
[log_20221110_213113.txt](https://github.com/xunkong/xunkong/files/9981446/log_20221110_213113.txt)
[log_20221110_213820.txt](https://github.com/xunkong/xunkong/files/9981447/log_20221110_213820.txt)
[log_20221110_214453.txt](https://github.com/xunkong/xunkong/files/9981449/log_20221110_214453.txt)
[log_20221110_214711.txt](https://github.com/xunkong/xunkong/files/9981451/log_20221110_214711.txt)
[log_20221110_220310.txt](https://github.com/xunkong/xunkong/files/9981452/log_20221110_220310.txt)
[log_20221109_141915.txt](https://github.com/xunkong/xunkong/files/9981454/log_20221109_141915.txt)
[log_20221109_143515.txt](https://github.com/xunkong/xunkong/files/9981455/log_20221109_143515.txt)
[log_20221109_145115.txt](https://github.com/xunkong/xunkong/files/9981456/log_20221109_145115.txt)
[log_20221109_150715.txt](https://github.com/xunkong/xunkong/files/9981457/log_20221109_150715.txt)
[log_20221109_152314.txt](https://github.com/xunkong/xunkong/files/9981458/log_20221109_152314.txt)
[log_20221109_153917.txt](https://github.com/xunkong/xunkong/files/9981459/log_20221109_153917.txt)
[log_20221109_155514.txt](https://github.com/xunkong/xunkong/files/9981460/log_20221109_155514.txt)
[log_20221109_161117.txt](https://github.com/xunkong/xunkong/files/9981461/log_20221109_161117.txt)
[log_20221109_162716.txt](https://github.com/xunkong/xunkong/files/9981462/log_20221109_162716.txt)
[log_20221109_164317.txt](https://github.com/xunkong/xunkong/files/9981463/log_20221109_164317.txt)
[log_20221109_165914.txt](https://github.com/xunkong/xunkong/files/9981465/log_20221109_165914.txt)
[log_20221109_171515.txt](https://github.com/xunkong/xunkong/files/9981466/log_20221109_171515.txt)
[log_20221109_173120.txt](https://github.com/xunkong/xunkong/files/9981467/log_20221109_173120.txt)
[log_20221109_174714.txt](https://github.com/xunkong/xunkong/files/9981468/log_20221109_174714.txt)
[log_20221109_180315.txt](https://github.com/xunkong/xunkong/files/9981469/log_20221109_180315.txt)
[log_20221109_181914.txt](https://github.com/xunkong/xunkong/files/9981470/log_20221109_181914.txt)
[log_20221109_183515.txt](https://github.com/xunkong/xunkong/files/9981471/log_20221109_183515.txt)
[log_20221109_185113.txt](https://github.com/xunkong/xunkong/files/9981472/log_20221109_185113.txt)
[log_20221109_190719.txt](https://github.com/xunkong/xunkong/files/9981473/log_20221109_190719.txt)
[log_20221109_192315.txt](https://github.com/xunkong/xunkong/files/9981474/log_20221109_192315.txt)
[log_20221109_193914.txt](https://github.com/xunkong/xunkong/files/9981475/log_20221109_193914.txt)
[log_20221109_195514.txt](https://github.com/xunkong/xunkong/files/9981476/log_20221109_195514.txt)
[log_20221109_201149.txt](https://github.com/xunkong/xunkong/files/9981477/log_20221109_201149.txt)
[log_20221109_202751.txt](https://github.com/xunkong/xunkong/files/9981478/log_20221109_202751.txt)
[log_20221109_204352.txt](https://github.com/xunkong/xunkong/files/9981479/log_20221109_204352.txt)
[log_20221109_205955.txt](https://github.com/xunkong/xunkong/files/9981480/log_20221109_205955.txt)
[log_20221109_211555.txt](https://github.com/xunkong/xunkong/files/9981481/log_20221109_211555.txt)
[log_20221109_213119.txt](https://github.com/xunkong/xunkong/files/9981482/log_20221109_213119.txt)
[log_20221109_214722.txt](https://github.com/xunkong/xunkong/files/9981483/log_20221109_214722.txt)
[log_20221109_220319.txt](https://github.com/xunkong/xunkong/files/9981484/log_20221109_220319.txt)
[log_20221109_221915.txt](https://github.com/xunkong/xunkong/files/9981485/log_20221109_221915.txt)
[log_20221109_223516.txt](https://github.com/xunkong/xunkong/files/9981486/log_20221109_223516.txt)
[log_20221109_225113.txt](https://github.com/xunkong/xunkong/files/9981487/log_20221109_225113.txt)
[log_20221109_230713.txt](https://github.com/xunkong/xunkong/files/9981488/log_20221109_230713.txt)
[log_20221109_232314.txt](https://github.com/xunkong/xunkong/files/9981489/log_20221109_232314.txt)
[log_20221109_233914.txt](https://github.com/xunkong/xunkong/files/9981492/log_20221109_233914.txt)
[log_20221109_235514.txt](https://github.com/xunkong/xunkong/files/9981493/log_20221109_235514.txt)
[log_20221110_001113.txt](https://github.com/xunkong/xunkong/files/9981494/log_20221110_001113.txt)
[log_20221110_002715.txt](https://github.com/xunkong/xunkong/files/9981495/log_20221110_002715.txt)
[log_20221110_004334.txt](https://github.com/xunkong/xunkong/files/9981497/log_20221110_004334.txt)
[log_20221110_005913.txt](https://github.com/xunkong/xunkong/files/9981498/log_20221110_005913.txt)
[log_20221110_011513.txt](https://github.com/xunkong/xunkong/files/9981499/log_20221110_011513.txt)
[log_20221110_013114.txt](https://github.com/xunkong/xunkong/files/9981500/log_20221110_013114.txt)
[log_20221110_014712.txt](https://github.com/xunkong/xunkong/files/9981501/log_20221110_014712.txt)
[log_20221110_020313.txt](https://github.com/xunkong/xunkong/files/9981503/log_20221110_020313.txt)
[log_20221110_021914.txt](https://github.com/xunkong/xunkong/files/9981504/log_20221110_021914.txt)
[log_20221110_023513.txt](https://github.com/xunkong/xunkong/files/9981505/log_20221110_023513.txt)
[log_20221110_025112.txt](https://github.com/xunkong/xunkong/files/9981506/log_20221110_025112.txt)
[log_20221110_030714.txt](https://github.com/xunkong/xunkong/files/9981507/log_20221110_030714.txt)
[log_20221110_032314.txt](https://github.com/xunkong/xunkong/files/9981509/log_20221110_032314.txt)
[log_20221110_033913.txt](https://github.com/xunkong/xunkong/files/9981510/log_20221110_033913.txt)
[log_20221110_035514.txt](https://github.com/xunkong/xunkong/files/9981511/log_20221110_035514.txt)
[log_20221110_041115.txt](https://github.com/xunkong/xunkong/files/9981512/log_20221110_041115.txt)
[log_20221110_042714.txt](https://github.com/xunkong/xunkong/files/9981513/log_20221110_042714.txt)
[log_20221110_044314.txt](https://github.com/xunkong/xunkong/files/9981514/log_20221110_044314.txt)
[log_20221110_045914.txt](https://github.com/xunkong/xunkong/files/9981515/log_20221110_045914.txt)
[log_20221110_051514.txt](https://github.com/xunkong/xunkong/files/9981516/log_20221110_051514.txt)
[log_20221110_053114.txt](https://github.com/xunkong/xunkong/files/9981517/log_20221110_053114.txt)
[log_20221110_054713.txt](https://github.com/xunkong/xunkong/files/9981519/log_20221110_054713.txt)
[log_20221110_060314.txt](https://github.com/xunkong/xunkong/files/9981520/log_20221110_060314.txt)
[log_20221110_061914.txt](https://github.com/xunkong/xunkong/files/9981522/log_20221110_061914.txt)
[log_20221110_063514.txt](https://github.com/xunkong/xunkong/files/9981523/log_20221110_063514.txt)
[log_20221110_065113.txt](https://github.com/xunkong/xunkong/files/9981524/log_20221110_065113.txt)
[log_20221110_070757.txt](https://github.com/xunkong/xunkong/files/9981525/log_20221110_070757.txt)
[log_20221110_072359.txt](https://github.com/xunkong/xunkong/files/9981526/log_20221110_072359.txt)
[log_20221110_074002.txt](https://github.com/xunkong/xunkong/files/9981527/log_20221110_074002.txt)
[log_20221110_075602.txt](https://github.com/xunkong/xunkong/files/9981528/log_20221110_075602.txt)
[log_20221110_081158.txt](https://github.com/xunkong/xunkong/files/9981529/log_20221110_081158.txt)
[log_20221110_082757.txt](https://github.com/xunkong/xunkong/files/9981530/log_20221110_082757.txt)
[log_20221110_084358.txt](https://github.com/xunkong/xunkong/files/9981531/log_20221110_084358.txt)
[log_20221110_085958.txt](https://github.com/xunkong/xunkong/files/9981532/log_20221110_085958.txt)
[log_20221110_091601.txt](https://github.com/xunkong/xunkong/files/9981533/log_20221110_091601.txt)
[log_20221110_093116.txt](https://github.com/xunkong/xunkong/files/9981534/log_20221110_093116.txt)
[log_20221110_094717.txt](https://github.com/xunkong/xunkong/files/9981535/log_20221110_094717.txt)
[log_20221110_100321.txt](https://github.com/xunkong/xunkong/files/9981536/log_20221110_100321.txt)
[log_20221110_101925.txt](https://github.com/xunkong/xunkong/files/9981537/log_20221110_101925.txt)
[log_20221110_103515.txt](https://github.com/xunkong/xunkong/files/9981538/log_20221110_103515.txt)
[log_20221110_105116.txt](https://github.com/xunkong/xunkong/files/9981539/log_20221110_105116.txt)
[log_20221110_110715.txt](https://github.com/xunkong/xunkong/files/9981540/log_20221110_110715.txt)
[log_20221110_112314.txt](https://github.com/xunkong/xunkong/files/9981541/log_20221110_112314.txt)
[log_20221110_113914.txt](https://github.com/xunkong/xunkong/files/9981542/log_20221110_113914.txt)
[log_20221110_115514.txt](https://github.com/xunkong/xunkong/files/9981543/log_20221110_115514.txt)
[log_20221110_121114.txt](https://github.com/xunkong/xunkong/files/9981544/log_20221110_121114.txt)
[log_20221110_122714.txt](https://github.com/xunkong/xunkong/files/9981545/log_20221110_122714.txt)
[log_20221110_124314.txt](https://github.com/xunkong/xunkong/files/9981546/log_20221110_124314.txt)
[log_20221110_125916.txt](https://github.com/xunkong/xunkong/files/9981547/log_20221110_125916.txt)
[log_20221110_131518.txt](https://github.com/xunkong/xunkong/files/9981548/log_20221110_131518.txt)
[log_20221110_133114.txt](https://github.com/xunkong/xunkong/files/9981549/log_20221110_133114.txt)
[log_20221110_134713.txt](https://github.com/xunkong/xunkong/files/9981551/log_20221110_134713.txt)
[log_20221110_140316.txt](https://github.com/xunkong/xunkong/files/9981552/log_20221110_140316.txt)
[log_20221110_141915.txt](https://github.com/xunkong/xunkong/files/9981553/log_20221110_141915.txt)
[log_20221110_143514.txt](https://github.com/xunkong/xunkong/files/9981554/log_20221110_143514.txt)
[log_20221110_145113.txt](https://github.com/xunkong/xunkong/files/9981555/log_20221110_145113.txt)
[log_20221110_150716.txt](https://github.com/xunkong/xunkong/files/9981556/log_20221110_150716.txt)
[log_20221110_152315.txt](https://github.com/xunkong/xunkong/files/9981557/log_20221110_152315.txt)
[log_20221110_153916.txt](https://github.com/xunkong/xunkong/files/9981558/log_20221110_153916.txt)
[log_20221110_155516.txt](https://github.com/xunkong/xunkong/files/9981559/log_20221110_155516.txt)
[log_20221110_161114.txt](https://github.com/xunkong/xunkong/files/9981561/log_20221110_161114.txt)
[log_20221110_162713.txt](https://github.com/xunkong/xunkong/files/9981562/log_20221110_162713.txt)
[log_20221110_164315.txt](https://github.com/xunkong/xunkong/files/9981563/log_20221110_164315.txt)
[log_20221110_165916.txt](https://github.com/xunkong/xunkong/files/9981564/log_20221110_165916.txt)
[log_20221110_171513.txt](https://github.com/xunkong/xunkong/files/9981565/log_20221110_171513.txt)
[log_20221110_173114.txt](https://github.com/xunkong/xunkong/files/9981566/log_20221110_173114.txt)
[log_20221110_174716.txt](https://github.com/xunkong/xunkong/files/9981567/log_20221110_174716.txt)

**Comment by wmhjbj** [comment]
我也遇到1034问题了，删掉账号重新登录重新固定磁贴好了1天，又出现1034了

**Comment by SteveWYSism** [comment]
+1，现在点固定到开始屏幕，也会报错 hoyolab exception 1034

**Comment by jqtmviyu** [comment]
https://github.com/xunkong/xunkong/issues/264

**Comment by MisakaMikoto2333** [comment]
我也遇到了，重新添加过一段时间又会这样

**Comment by ghosthands** [comment]
同遇到，删除重新添加账号一段时间后仍会出现

**Comment by 1TCAN** [comment]
+1，之前不会遇到的，最近2天才有

**Comment by FangDoudouY** [comment]
+1

1034

**Comment by misaka1002** [comment]
+1

**Comment by POEG1726** [comment]
+1
