### ISSUE TITLE
侧载版安装出错

### ISSUE THREAD

**Issue by MeiVinEight** [xunkong/xunkong#268]
### 问题描述

使用侧载版时无法安装，手动安装报错文件系统错误，自动安装运行ps1后会直接卡死然后崩溃
![image](https://user-images.githubusercontent.com/57023439/201273192-b43f9ac9-098b-43ae-baee-dac1584af38c.png)
![image](https://user-images.githubusercontent.com/57023439/201273283-07fad51c-56c6-417d-a0e4-25c6b5225477.png)

### 复现步骤

如上

### 截图

如上

### 系统版本

Windows 11 22H2

### 寻空版本

正在安装的是1.2.3.0

**Comment by Scighost** [comment]
不知道是什么情况，你可以等商店版
