### ISSUE TITLE
每次打开都提示更新，忽略后重启仍然弹出

### ISSUE THREAD

**Issue by Ulua3809** [xunkong/xunkong#270]
### 问题描述

![image](https://user-images.githubusercontent.com/63995396/201333151-747ed171-1611-4f46-a7e3-2521802f8597.png)

### 复现步骤

弹出后点击忽略，关闭应用必定弹出
弹出后点击忽略并切换到主页，关闭应用必定弹出

### 系统版本

Windows11 21h2

### 寻空版本

1.2.3.0

### 日志

[log_20221106_113849.txt](https://github.com/xunkong/xunkong/files/9989932/log_20221106_113849.txt)
[log_20221111_194715.txt](https://github.com/xunkong/xunkong/files/9989938/log_20221111_194715.txt)

### 备注

之前手动设置过夜间模式和毛玻璃特效

**Comment by Scighost** [comment]
在浏览器中输入 `xunkong://settings`，然后在打开的窗口中输入
![image](https://user-images.githubusercontent.com/61003590/201335552-f127e75a-4461-4cc3-a46a-3f480cf7af2c.png)

**Comment by Ulua3809** [comment]
解决了，所以啥时候可以加个不自动检测更新的设置，国内薛定谔的网络环境不知道什么时候就被墙了

**Comment by Scighost** [comment]
这是更新后显示更新内容的页面，看日志是 WebView2 的问题，之前修改了部分逻辑，但是把**忽略**忘了。
检查更新失败是不会有任何提示的，国内的网络访问 `api.github.com` 速度还行。 

暂时别关，肯定不止你一人有这样的问题。
