### ISSUE TITLE
修改应用内备注性文字的字体为无衬线字体

### ISSUE THREAD

**Issue by RyanSaul** [xunkong/xunkong#271]
### 你的建议

目前寻空 app 内许多备注性文字使用了楷体，在低分屏下辨识度较低且与界面整体格格不入，希望能更换成无衬线字体。若担心区分度不高，可将备注性文字处理为无衬线字体斜体。

![image](https://user-images.githubusercontent.com/16830734/201380486-563756e2-4952-438a-8aa1-b11f39eebc79.png)

![image](https://user-images.githubusercontent.com/16830734/201381709-9a9d27db-00c7-41fd-9e01-01a37189ce9d.png)

![image](https://user-images.githubusercontent.com/16830734/201382145-86e5217d-85b1-4b27-87a5-78ef04689c9d.png)

**Comment by Scighost** [comment]
成就页面保持原样，改了之后也不好看

**Comment by RyanSaul** [comment]
> 

我的意思是说把楷体换成 HarmonyOS Sans 之类的无衬线字体啦，如果没有对应的字重甚至用微软雅黑都行…… 可能之前是我说得太委婉了，但楷体在低分辨率下的显示效果真的惨不忍睹，挤成一团什么都看不清（关于楷体好看与否，由于有主观因素影响所以我没有评价，但辨识度低是确实存在的问题），斜体那条我是想说在换成无衬线字体的前提下如果还是担心辨识度不够再将字体设为斜体

**Comment by Scighost** [comment]
<img width="981" alt="image" src="https://user-images.githubusercontent.com/61003590/201517365-88c62dcc-c057-4689-bd76-08afcfd0eb46.png">

<img width="388" alt="image" src="https://user-images.githubusercontent.com/61003590/201517460-d7b820e1-1fb5-4efa-afa3-dbe0169136d7.png">

汉仪文黑的显示效果还可以，备注字体太小用 HarmonyOS Sans 更合适。
另外两处已经改成了 HarmonyOS Sans 的斜体。
汉仪文黑需要自行安装原神中的那个版本。

**Comment by Scighost** [comment]
<img width="954" alt="image" src="https://user-images.githubusercontent.com/61003590/201517647-e5c5eca2-5cc1-4726-b864-4af5f60b7da4.png">

未安装字体时的显示效果略有变化，字体粗细全部改为正常。
