### ISSUE TITLE
祈愿记录云备份功能无法使用，提示“An error occurred...”

### ISSUE THREAD

**Issue by moulai** [xunkong/xunkong#276]
### 问题描述

使用祈愿记录云备份功能时，所有的功能（包括查询记录功能、上传、恢复、删除云端记录等），都会提示`An error occured while saving the entity changes. See the inner exception for details`。
查看Log文件时，没有发现相关的错误信息。

### 复现步骤

1. 删除账号；
2. 重新添加账号；
3. 通过寻空启动器打开原神，打开祈愿历史；
4. 通过寻空【祈愿记录】→【获取记录】→【从缓存文件】获取祈愿记录；
5. 【记录备份】→【增量上传】（【全量上传】）提示上述错误信息；
6. 尝试其它功能，也提示上述错误信息。

我之前曾经用过这个云备份功能，当时是可以使用的。今天突然不行了。
尝试了如下方法都还是出错：
- 删除账号后重新添加账号
- 清空寻空数据库（保存于个人文档下的那个）
- 卸载重装寻空
- 使用寻空侧装版（1.2.3.0）

### 截图

![xunkong_bug](https://user-images.githubusercontent.com/8275836/201479503-7e1b23bc-3294-417f-bb02-062be5d01574.gif)

### 系统版本

Windows 11 专业版 21H2

### 寻空版本

应用商城版 1.2.2.0

**Comment by Scighost** [comment]
已修改了表结构，但是不清楚是否可用

**Comment by moulai** [comment]
> 已修改了表结构，但是不清楚是否可用

可以用了！非常感谢！辛苦大佬！
