### ISSUE TITLE
希望适配https://github.com/biuuu/genshin-wish-export里面导出的抽卡记录

### ISSUE THREAD

**Issue by Dongyifengs** [xunkong/xunkong#278]
### 你的建议

希望适配
https://github.com/biuuu/genshin-wish-export
项目里面导出的抽卡记录！！
万分感谢

**Comment by TremblingMoeNew** [comment]
GWE里，设置-导出JSON

**Comment by xingzhige** [comment]
其实是可以用的，在Genshin-Wish-Export里，先切换至你要导出记录的UID，然后点击右上角设置，在设置中找到“导出到其他工具”，点击“导出JSON”，然后将其保存路径选择到你方便找到的位置（例如桌面）
![image](https://user-images.githubusercontent.com/72428624/201590568-0601e6d2-5e9e-4fe3-99f1-874a34549368.png)
![image](https://user-images.githubusercontent.com/72428624/201590910-86c919ad-5738-4ba7-b772-e7d08e850d96.png)
导出后，你可以尝试是否可以直接导入到寻空，如不行，可参照寻空的文档中的格式进行修改
![image](https://user-images.githubusercontent.com/72428624/201591126-3d01aa5f-ab0f-4270-b9cc-f32217b936db.png)
例如Genshin-Wish-Export导出的json文件中不会包含上图中的第2行与第6行的信息，你可以通过查找前后字符来全部替换进去，注意是全部替换。如我想添加第6行的《"lang": "zh-cn", 》我可以先搜索《"item_type"》，然后再进行全部替换成《"lang": "zh-cn","item_type" 》

**Comment by Dongyifengs** [comment]
已经可以正常使用了，万分感谢，中间导入的时候出现个小bug，就是在导入的时候uid是0的话不就是默认情况吗，我JSON里面是包含uid的 然后就不能导入，说是uid是空 必须要给导入那里的uid改成JSON的才行

**Comment by xingzhige** [comment]
> 已经可以正常使用了，万分感谢，中间导入的时候出现了个小bug，就是在导入的时候uid是0的话不就是默认情况吗，我JSON里面是包含uid的然后就不能导入了，说是uid是空的必须要给导入那里的uid改成JSON的才行

总之寻空由于依赖库的限制，导入功能不完全支持 [UIGF v2.2]，所以导出的时候先自己手动改一下再导入吧2333
