### ISSUE TITLE
我的角色，角色图鉴，武器图鉴，成就管理无法使用！

### ISSUE THREAD

**Issue by Gexiao-Li** [xunkong/xunkong#280]
### 问题描述

我的角色，角色图鉴，武器图鉴，成就管理这几个页面均显示空白，设置里，预缓存所有图片我没点过，点击开始下载它提示“所有图片均已缓存”

### 复现步骤

关于成就管理，我点击获取，然后按操作导出到寻空，之后就是重开软件也是如图所示，以上种种情况都是从下载安装到首次进入软件就存在的！

### 截图

![image](https://user-images.githubusercontent.com/81342097/201525948-be4bf8f9-0ed8-41de-9121-e008c4f0f1bf.png)
![image](https://user-images.githubusercontent.com/81342097/201525964-8215f844-4149-43ba-a73d-192233a1647f.png)
![image](https://user-images.githubusercontent.com/81342097/201526023-4dfe416a-4bd0-45e7-a19c-58e88e9b8308.png)
![image](https://user-images.githubusercontent.com/81342097/201526032-903db0c7-2cda-4d78-8405-6f4d54875ba6.png)
![image](https://user-images.githubusercontent.com/81342097/201526040-f49e5188-bbdb-44e5-aea3-d3b3e9299995.png)

### 系统版本

Windows 11  22H2

### 寻空版本

1.2.3.0

### 日志

[log_20221113_215859.txt](https://github.com/xunkong/xunkong/files/9997410/log_20221113_215859.txt)

**Comment by Scighost** [comment]
<img width="367" alt="image" src="https://user-images.githubusercontent.com/61003590/201526150-d738c4fd-1e1f-4368-b1c6-ff38e2bae673.png">

**Comment by Gexiao-Li** [comment]
也试过，提示这个！
![image](https://user-images.githubusercontent.com/81342097/201536289-b0ddf593-3eb4-4367-8754-a13ae4c45142.png)

**Comment by Gexiao-Li** [comment]
彻底卸载重装我也试了几次，没有得到解决…

**Comment by Gexiao-Li** [comment]
> <img alt="image" width="367" src="https://user-images.githubusercontent.com/61003590/201526150-d738c4fd-1e1f-4368-b1c6-ff38e2bae673.png">

麻烦看一下我最新回复的，关于无法手动更新的问题，网络是电信千兆，梯子的话也没问题，YouTube 4K都能随便跑。

**Comment by Scighost** [comment]
https://api.xunkong.cc/v1/genshindata/all
能打开不？

**Comment by Gexiao-Li** [comment]
> https://api.xunkong.cc/v1/genshindata/all 能打开不？

使用代理，可以打开的！

**Comment by Gexiao-Li** [comment]
> https://api.xunkong.cc/v1/genshindata/all 能打开不？

问题已经解决了，我将版本升级到1.2.3.1，代理设为系统代理开了全局，手动更新了数据。
