### ISSUE TITLE
关于 Windows 10 上的表现，以及成就管理与过场动画

### ISSUE THREAD

**Issue by fivefirex** [xunkong/xunkong#282]
### 你的建议

Windows 10 [^1] 上 Acrylic 效果可以正常启用。

[^1]: 所用系统环境为 Microsoft Windows 10 Version 21H2 19044.1826。

Windows 10 上右上角最小化、最大化、关闭按钮经多次测试，效果正常。

---

在为所有用户安装完成字体并重启后，**成就管理** 页面字体未改变。

**过场动画** 中的视频用第三方下载器（如 IDM 等）下载会返回 HTTP 报头错误。~~还有就是下载的文件没有后缀名。。。~~

**Comment by Scighost** [comment]
感谢反馈。

你看一下控制面板的所有字体中有没有下图的这个。
<img width="98" alt="image" src="https://user-images.githubusercontent.com/61003590/201620555-2f0acec3-eaf1-40ff-b8c9-af9a1425d3a9.png">

为了防止消耗的流量过大，我开启了 Cloudflare 的托管质询，需要在浏览器中通过验证才能下载。
如果加载扩展名就会被服务商禁止下载。

**Comment by fivefirex** [comment]
OK，解决了。
