### ISSUE TITLE
过场动画下载速度太慢

### ISSUE THREAD

**Issue by MeiVinEight** [xunkong/xunkong#290]
### 问题描述

如题，MSEdge浏览器

### 复现步骤

无

### 截图

![image](https://user-images.githubusercontent.com/57023439/202063485-d3f7d5a4-d09d-4c92-8563-6e3225b655c7.png)

### 系统版本

Windows 11 22H2

### 寻空版本

1.2.3.0

**Comment by Scighost** [comment]
下载速度太慢是你的问题
<img width="256" alt="image" src="https://user-images.githubusercontent.com/61003590/202074842-2175068d-40e1-4082-98de-e4a71b8c75f4.png">

**Comment by MeiVinEight** [comment]
需要加速吗，我没有加速器，难道因为运营商是移动

**Comment by MeiVinEight** [comment]
> > 需要加速吗，我没有加速器，难道因为运营商是移动
> 
> 可以试试IDM，B站上有下载和激活教程

IDM通不过cf的验证，没法下载的

**Comment by yjc20061008** [comment]
> > > 需要加速吗，我没有加速器，难道因为运营商是移动
> > 
> > 可以试试IDM，B站上有下载和激活教程
> 
> IDM通不过cf的验证，没法下载的

安装IDM并激活（同时检查浏览器是否有IDM的扩展），在寻空里点击下载，打开浏览器，等待验证，待屏幕显示“Processing....”时（此时浏览器会弹出下载窗口），在网页空白地方按右键，点击“使用IDM下载”，即可打开IDM，点击开始下载即可，下载完成再关闭浏览器。
如果浏览器一直不显示“Processing”，可以使用steam++（现在微软商店已改名Watt Toolkit）加速访问国外验证码平台。

**Comment by MeiVinEight** [comment]
> > > > 需要加速吗，我没有加速器，难道因为运营商是移动
> > > 
> > > 
> > > 可以试试IDM，B站上有下载和激活教程
> > 
> > 
> > IDM通不过cf的验证，没法下载的
> 
> 安装IDM并激活（同时检查浏览器是否有IDM的扩展），在寻空里点击下载，打开浏览器，等待验证，待屏幕显示“Processing....”时（此时浏览器会弹出下载窗口），在网页空白地方按右键，点击“使用IDM下载”，即可打开IDM，点击开始下载即可，下载完成再关闭浏览器。 如果浏览器一直不显示“Processing”，可以使用steam++（现在微软商店已改名Watt Toolkit）加速访问国外验证码平台。

似乎并没有用，还是会被cf挡住
![image](https://user-images.githubusercontent.com/57023439/208917524-b4e323fe-5a92-442e-a5b4-48aed6291d65.png)
