### ISSUE TITLE
更新后祈愿记录获取后不刷新数据显示

### ISSUE THREAD

**Issue by raiwhiz** [xunkong/xunkong#296]
### 问题描述

更新后，获取到新的祈愿记录后，无法更新数据，刷新页面也没用。左侧切换到其他页面再切换到祈愿记录才更新显示。

### 复现步骤

祈愿记录-获取记录-从缓存文件-新增x条祈愿记录，数据不变，刷新也不变。
左侧切换到其他页面，再切回来，数据会更新。

### 系统版本

Windows 10 22H2

### 寻空版本

1.2.3.0

**Comment by smallg0at** [comment]
实际上，刷新按钮也不能正常工作了

**Comment by Scighost** [comment]
更新到 1.2.4
