### ISSUE TITLE
win10 用不了窗口材质

### ISSUE THREAD

**Issue by anhcemi** [xunkong/xunkong#299]
### 问题描述

win10 用不了窗口材质，是要额外到哪下载一下材质包吗？

### 复现步骤

特地把win10 更到了最新，但都还是说不支持此操作

### 系统版本

win10家庭中文版 22H2

### 寻空版本

微软商店1.2.3.0-

**Comment by fivefirex** [comment]
Windows 10 只能使用 `Acrylic` 材质。

寻空版本需要大于等于 `1.2.3.0`。

**Comment by fivefirex** [comment]
我这边 Windows 10 专业版 22H2 、 Windows 10 家庭版 21H2 都测试过 `Acrylic` 显示完全正常。

**Comment by Scighost** [comment]
机器配置过低或在系统设置中关闭了透明选项，会开启不了亚克力材质
