### ISSUE TITLE
使用Snipaste在客户端截屏时会很卡

### ISSUE THREAD

**Issue by Muhe-nye** [xunkong/xunkong#302]
### 问题描述

使用Snipaste在客户端截屏时会很卡，寻空是商店版，Snipaste是1.16.2，在寻空打开时，Snipaste在寻空窗口划过时就会很卡，CPU占用率会突然上升。若全屏截屏时，Snipaste会卡在截屏页面，无法操作，只能注销。

### 复现步骤

寻空窗口最大化，使用snipaste快捷键F1截屏

### 系统版本

Windows 10 21H2

### 寻空版本

1.2.3.0

**Comment by Scighost** [comment]
我用的是 Snipaste 2.8，没有发现这个问题。

**Comment by Muhe-nye** [comment]
我更新一下试试，我的版本居然这么老了

**Comment by Muhe-nye** [comment]
问题解决，谢谢啦

**Comment by Muhe-nye** [comment]
问题解决，谢谢啦
