### ISSUE TITLE
祈愿记录更新问题

### ISSUE THREAD

**Issue by qakcn** [xunkong/xunkong#303]
### 问题描述

点击“获取记录“、”从缓存文件”之后下面的页面不会更新，甚至点“刷新页面”也不会，要切换到别的页面再切回来才会更新。

设置中”页面缓存“是关闭的。

### 复现步骤

1. 切换到”祈愿记录“页面。
2. 点击”获取记录“。
3. 点击”从缓存文件“，页面内容**无变化**。
4. 点击”刷新页面“，页面内容**无变化**。
5. 切换到其他页面，再切换到”祈愿记录“页面，页面内容才**有变化**。

### 系统版本

Windows 10 22H2 19045.2251

### 寻空版本

1.2.3.0

**Comment by Scighost** [comment]
更新到 1.2.4
