### ISSUE TITLE
换盘了，祈愿记录丢失，寻空的云备份不认。

### ISSUE THREAD

**Issue by lightarkfun** [xunkong/xunkong#304]
### 问题描述

资料盘坏了，但是寻空安装目录没坏。
祈愿记录全部丢失，但是在寻空登陆米游社后，用云备份的恢复功能竟然一条记录都没发现。
猜测与寻空分配云备份空间的用户识别方式有关？是用的cookie分配吗，还是什么方式……

### 复现步骤

略

### 系统版本

win11

### 寻空版本

1.2.2.0

### 备注

云备份功能不就是为了防丢失吗？我觉得如果没有提供注册寻空账号的功能，那就还是按米游社账号分配云备份空间比较好吧。
我以前从云端恢复过数据，能正确识别，说明你们服务器里是有给每个祈愿记录的备份记录UID的。既然如此，这个功能应该挺好修改的！
我原神ID：140720389，期待你们的修复帮我找回备份记录哦！（呜呜呜官方只提供最近6个月祈愿记录太酸了）

**Comment by lightarkfun** [comment]
我知道怎么回事了。寻空目前的功能逻辑是，必须先在原神里抓取一次记录，然后再与云端记录进行对比核实身份。。也就是说我手动抓取过一次记录后，云备份就认识我了！。。

**Comment by Scighost** [comment]
很高兴云备份能发挥作用
