### ISSUE TITLE
[UIAFv1.0] 过量的思念

### ISSUE THREAD

**Issue by emako** [xunkong/xunkong#306]
### 问题描述

UIAFv1.0会被误识别为完成，而不是2/5

```json
{
  "info": {
    "export_app": "genshin-achievement-ocr",
    "export_app_version": "v1.0.0",
    "export_timestamp": 1668998085,
    "uiaf_version": "v1.0"
  },
  "list": [
    {
      "id": 84512,
      "timestamp": 1664409600,
      "current": 2
    }
  ]
}
```

### 复现步骤

如上

### 截图

![image](https://user-images.githubusercontent.com/24737061/202920214-affb9706-6cb0-481e-9f63-90476839de2a.png)

### 系统版本

w11-22h2

### 寻空版本

1.2.3.1

### 备注

> https://github.com/UIGF-org/UIGF-org.github.io/blob/f7edd354e4578b730c6a98c6db50b8fd00a94b37/docs/standards/UIAF.md

current
对于识别成功的值，如 30/40 current 的值应设置为30

因为始终可以从原神的数据中找到目标达成值

对于识别失败的值，请将该字段的值设为 0

**Comment by Scighost** [comment]
1.0 的设计有一些不合理的地方，是已弃用的版本，请改用 1.1
