### ISSUE TITLE
获取记录后要切换一下页面记录才会刷新，点击刷新是无效的

### ISSUE THREAD

**Issue by a616781689** [xunkong/xunkong#309]
### 问题描述

RT，屏幕上方提示新增x条记录后，页面并没有更新，刷新页面按钮也无效，需要切换一下页面数据才会载入

### 复现步骤

1.抽卡
2.等待几个小时
3.使用寻空更新记录
4.点击刷新页面无反应

### 系统版本

Win11 22H2 22623.885  Windows Feature Experience Pack 1000.22637.1000.0

### 寻空版本

1.2.3.1

**Comment by Scighost** [comment]
更新到 1.2.4
