### ISSUE TITLE
希望无窗口模式可以增加全屏的那个

### ISSUE THREAD

**Issue by Cololee2333** [xunkong/xunkong#314]
### 你的建议

手里的笔记本没有2560*1600的窗口模式,只有2560*1440的窗口,然后笔记本屏幕是2560*1600的..
在全屏模式下,没办法调成无边框,切换出来打字的时候就有点点麻烦,可以加一个全屏改无边框窗口的模式嘛..

**Comment by WinTerminal** [comment]
其实你选无边框窗口之后，进游戏，设置里切独占全屏，然后 Alt + Enter 就可以变成无边框窗口了（
