### ISSUE TITLE
过场动画页面点击“选择本地文件夹”时抛出异常 Error HRESULT E_FAIL has been returned from a call to a COM component

### ISSUE THREAD

**Issue by Patrick-Ze** [xunkong/xunkong#317]
### 问题描述

过场动画页面点击“选择本地文件夹”时会抛出异常（见截图）
Error HRESULT E_FAIL has been returned from a call to a COM component

### 复现步骤

过场动画页面点击“选择本地文件夹”

### 截图

![image](https://user-images.githubusercontent.com/19711799/204076635-0456838b-e2cb-41f0-8061-88191f5d423e.png)

### 系统版本

Windows  10 21H2 (19044.2130)

### 寻空版本

三二一，一二三，啊啊——

### 日志

[log_20221126_145812.txt](https://github.com/xunkong/xunkong/files/10095822/log_20221126_145812.txt)

### 备注

issue区太可怕了，大佬招不招人维护issue区呀

**Comment by Scighost** [comment]
#291
