### ISSUE TITLE
米游社cookie寄了

### ISSUE THREAD

**Issue by renleihaokun** [xunkong/xunkong#318]
### 问题描述

大抵是更新了登录验证，还顺手把cookie砍了

### 复现步骤

没有找到 cookie_token 和 account_id，请重新登录（不管登录几遍还是在寻空里登录都一样）

### 截图

![image](https://user-images.githubusercontent.com/119118549/204093231-c1de3ebf-d3f3-48a1-af51-8dd9cc29de17.png)
![image](https://user-images.githubusercontent.com/119118549/204093295-b96dcac2-9a9d-468b-8dec-3d8f29c63e8b.png)

### 系统版本

Windows 11 专业版22H2

### 寻空版本

1.2.3.0

### 日志

[log_20220819_144500.txt](https://github.com/xunkong/xunkong/files/10096422/log_20220819_144500.txt)

**Comment by fivefirex** [comment]
参见 #315 。

**Comment by Scighost** [comment]
更新到 1.2.4
