### ISSUE TITLE
成就管理界面有问题

### ISSUE THREAD

**Issue by Winter-is-comingXK** [xunkong/xunkong#319]
### 问题描述

窗口空间挤在一起

### 复现步骤

缩小窗口

### 截图

![Xunkong Desktop_QOsQCUkov6](https://user-images.githubusercontent.com/33370220/204103267-5382d0bc-32e6-4b36-ba3d-f215abe05667.png)

### 系统版本

win11 22H2

### 寻空版本

1.2.3.0从商店中下载的

**Comment by fivefirex** [comment]
~~所以你希望这个界面怎么显示？~~
