### ISSUE TITLE
登录不了

### ISSUE THREAD

**Issue by wanfengmian** [xunkong/xunkong#321]
### 问题描述

目前寻空的网页登录已经没有用了。点击登录是显示缺少account_id"or "cookie token，还有输入cookie ,各种方法都试过了目前是登录不了的

### 复现步骤

1、添加账号-网页登录---登录后点确认显示错误
2、输入cookie--错误  无痕浏览器打开并登录 复制帮助里面的代码时，显示没有account_id"or "cookie token，需要重新登录

### 截图

![image](https://user-images.githubusercontent.com/119148782/204119690-c9a2fda3-098d-43ea-bed2-750b41840135.png)

### 系统版本

Windows 11 专业版  21H2

### 寻空版本

1.2.3.1

### 日志

[log_20221124_204301.txt](https://github.com/xunkong/xunkong/files/10097545/log_20221124_204301.txt)
[log_20221125_145440.txt](https://github.com/xunkong/xunkong/files/10097546/log_20221125_145440.txt)
[log_20221125_145947.txt](https://github.com/xunkong/xunkong/files/10097547/log_20221125_145947.txt)
[log_20221125_150013.txt](https://github.com/xunkong/xunkong/files/10097548/log_20221125_150013.txt)
[log_20221125_151122.txt](https://github.com/xunkong/xunkong/files/10097549/log_20221125_151122.txt)
[log_20221125_193639.txt](https://github.com/xunkong/xunkong/files/10097550/log_20221125_193639.txt)
[log_20221126_134512.txt](https://github.com/xunkong/xunkong/files/10097551/log_20221126_134512.txt)
[log_20221127_104208.txt](https://github.com/xunkong/xunkong/files/10097552/log_20221127_104208.txt)
[log_20221127_104224.txt](https://github.com/xunkong/xunkong/files/10097553/log_20221127_104224.txt)
[log_20221127_104328.txt](https://github.com/xunkong/xunkong/files/10097554/log_20221127_104328.txt)
[log_20221127_105746.txt](https://github.com/xunkong/xunkong/files/10097555/log_20221127_105746.txt)
[log_20221127_111719.txt](https://github.com/xunkong/xunkong/files/10097556/log_20221127_111719.txt)
[log_20221127_113414.txt](https://github.com/xunkong/xunkong/files/10097557/log_20221127_113414.txt)
[log_20221127_120629.txt](https://github.com/xunkong/xunkong/files/10097558/log_20221127_120629.txt)
[log_20221127_124538.txt](https://github.com/xunkong/xunkong/files/10097559/log_20221127_124538.txt)
[log_20221119_140415.txt](https://github.com/xunkong/xunkong/files/10097560/log_20221119_140415.txt)

**Comment by wangjunru159** [comment]
目前米游设把cookie_token换成了cookie_token_v2，需要修改一下cookie的代码

**Comment by fivefirex** [comment]
参见 #315 。

**Comment by Scighost** [comment]
更新到 1.2.4
