### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by xvcat** [xunkong/xunkong#323]
### 问题描述

无法登录，无论选择网页登录还是输入Cookie都显示不包含cookie_token和account_id，打开cookie发现account_id字段实际字符为account_mid，删掉m后可以登录，但是角色、旅行札记、深境螺旋等界面仍显示未登录。

### 复现步骤

无论选择网页登录还是输入Cookie都显示不包含cookie_token和account_id，打开cookie发现account_id字段实际字符为account_mid，删掉m后可以登录，但是角色、旅行札记、深境螺旋等界面仍显示未登录。

### 系统版本

 Windows 10 21H2

### 寻空版本

1.2.3.0

**Comment by fivefirex** [comment]
参见 #315 。
