### ISSUE TITLE
在祈愿记录 - 卡池历史界面，按照以下复现步骤会出现问题

### ISSUE THREAD

**Issue by fivefirex** [xunkong/xunkong#324]
### 问题描述

在祈愿记录 - 卡池历史界面，按照以下复现步骤会出现卡顿、卡死、未响应等问题。

跟这位老哥（#244）出现的情况差不多。

~~这个问题可能很难解决，而且具有偶然性。只是希望优化一下，比如说添加一个展开按钮，或者分成几页，用户想看哪页翻哪页，就不用一次性加载大量资源了。~~

### 复现步骤

我经过了多个系统版本测试。

其中寻空版本均为 `1.2.3.0`，均开启了 `Acrylic` 材质。

环境：
1. `CPU`: i5-1240P 12 Cores. 保证占用均不超过 `30%`。
2. `RAM`: 16 GB. 保证占用均不超过 `70%`。
3. `GPU`: 集成显卡 iRis Xe. 保证占用均不超过 `20%`。

复现：
1. Windows 10 专业版 21H2 复现步骤（微软商店版寻空）：
   1. 点开祈愿记录。
   2. 点开卡池历史。
   3. 将窗口全屏，此时已经有卡顿现象。
   4. 上下滑动，此时已经有卡顿现象。
   5. 左上角切换选项卡，此时应用未响应。
2. Windows 10 专业版 21H2 复现步骤（侧载版寻空）：
   1. 点开祈愿记录。
   2. 点开卡池历史，此时应用未响应。
3. Windows 10 家庭版 22H2 复现步骤（微软商店版寻空）：
   1. 点开祈愿记录。
   4. 点开卡池历史，此时已经有卡顿现象。
   5. 将窗口全屏，此时已经有卡顿现象。
   6. 上下滑动，此时应用未响应。
4. Windows 11 专业工作站版 22H2 复现步骤（微软商店版寻空）：
   1. 点开祈愿记录。
   2. 点开卡池历史。
   3. 将窗口全屏，此时已经有卡顿现象。
   4. 上下滑动，此时已经有卡顿和加载缓慢现象。
   7. 左上角切换选项卡。
   8. 按一下 `Win` + `Tab`，或者切出其他应用。
   9. 回到寻空，此时应用未响应。

综上。

高版本 `Windows` 坚持时间较久，但无一例外都出现了未响应的出现（当然也可能是我设备的问题。

每一个系统版本都经过了 `6~8` 次的测试，取得平均值。

应用未响应后，有些测试过了几秒就恢复了。有些直接白屏，~~但我忘了统计了~~

### 截图

在 Windows 10 专业版 21H2 的测试中，随手截了两张图。

任务管理器截的图。从左往右依次为 `CPU` `RAM` `磁盘` `网络` `GPU`。

开启应用的一瞬间：

![屏幕截图 2022-11-28 081329](https://user-images.githubusercontent.com/91671226/204168719-c805eedb-af25-4590-bc12-e93a92be3873.png)

开启祈愿管理 - 卡池历史的一瞬间：

![屏幕截图 2022-11-28 081422](https://user-images.githubusercontent.com/91671226/204168771-6d826d32-3650-40e2-aeed-04d8d4f47c27.png)

### 系统版本

综上，我使用了多个 `Windows` 版本。

### 寻空版本

均为 `1.2.3.0`，但有些测试环境用了 `侧载版` 寻空。

### 备注

~~估计只有 Windows 10 专业版 21H2 是最准的，因为只有这个是我的主力系统，开了一些优化，能保证没有其他进程在跑~~

**Comment by hellolllllin** [comment]
@XHLiang0 帮你放出来图片：

![](https://user-images.githubusercontent.com/90927576/204357712-a5eb22f0-0306-496a-b64a-71338fd38cfe.png)

![](https://user-images.githubusercontent.com/90927576/204358178-42be3f88-619c-4073-a134-e788f170bb7f.png)

![](https://user-images.githubusercontent.com/90927576/204358356-e6d38137-8ac4-4e05-98fb-802301b81e17.png)
