### ISSUE TITLE
无法添加网页快捷方式

### ISSUE THREAD

**Issue by anpoz** [xunkong/xunkong#325]
### 问题描述

一点击添加就卡住，然后过几秒就闪退

### 复现步骤

点击添加按钮

### 截图

![image](https://user-images.githubusercontent.com/2825342/204300778-d4554f84-978d-405c-a2fe-9ffdf6b57d71.png)

### 系统版本

22623.891

### 寻空版本

1.2.3.0

### 日志

[22:17:46.542] [INFO] 
寻空 1.2.3.0
E0238BE05E5071D48B78227BC23443A8
"C:\Program Files\WindowsApps\40418Scighost.Xunkong_1.2.3.0_x64__db3crskbcera8\Xunkong.Desktop\Xunkong.Desktop.dll"

[22:17:46.542] [EROR] Xunkong.Desktop.App.App_UnhandledException
崩溃了
System.ArgumentException: Value does not fall within the expected range.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Markup.IXamlBindingHelperStaticsMethods.ConvertValue(IObjectReference _obj, Type type, Object value)
   at Xunkong.Desktop.Pages.SettingPage.SettingPage_obj22_Bindings.Update_Icon(String obj, Int32 phase) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\obj\x64\Release\net7.0-windows10.0.22621.0\win10-x64\Pages\SettingPage.g.cs:line 269
   at Xunkong.Desktop.Pages.SettingPage.SettingPage_obj22_Bindings.Update_(WebToolItem obj, Int32 phase) in C:\Users\Scighost\OneDrive\Code\Xunkong\Desktop\App\obj\x64\Release\net7.0-windows10.0.22621.0\win10-x64\Pages\SettingPage.g.cs:line 258
   at ABI.Microsoft.UI.Xaml.Markup.IDataTemplateComponent.Do_Abi_ProcessBindings_1(IntPtr thisPtr, IntPtr item, Int32 itemIndex, Int32 phase, Int32* nextPhase)

**Comment by fivefirex** [comment]
应该是高版本特有的，~~以前版本没问题，添加的也都还在~~

**Comment by fivefirex** [comment]
要插入和删除数据，可以暂时使用以下方法：

先在电脑上安装 `SQLite3`，参见 [菜鸟教程](https://www.runoob.com/sqlite/sqlite-installation.html)。

进入终端，`>` 后表示执行的命令。

``` powershell
PS> cd ~/Documents/Xunkong/Database
PS> ls

Directory: C:\Users\Win\Documents\Xunkong\Database

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          2022/11/20    15:37          40960 Document.db
-a---          2022/11/29    07:47       12271616 GenshinData.db
-a---          2022/11/29    07:47         475136 XunkongData.db
```

以上命令用于切换到数据库目录。

``` powershell
PS> sqlite3
SQLite version 3.39.3 2022-09-05 11:02:23
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open XunkongData.db
sqlite> .database
main: C:\Users\Win\Documents\Xunkong\Database\XunkongData.db r/w
```

以上命令用于启动 `SQLite`，导入数据库，然后检验是否导入成功。

``` powershell
sqlite> .dump WebToolItem
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE WebToolItem
(
    Id         INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Title      TEXT,
    Icon       TEXT,
    "Order"    INTEGER NOT NULL,
    Url        TEXT    NOT NULL,
    JavaScript TEXT
);
INSERT INTO WebToolItem VALUES(12,'观测大地图','https://webstatic.mihoyo.com/upload/static-resource/2021/09/06/1ec1d1e2afbcc99f8f8c58eabb88a69d_3023852421646190619.png',0,'https://webstatic.mihoyo.com/app/ys-map-cn/index.html',NULL);
INSERT INTO WebToolItem VALUES(13,'莫娜占卜铺','https://mona-uranai.com/favicon.ico',1,'https://mona-uranai.com',NULL);
INSERT INTO WebToolItem VALUES(14,'原魔计算器','https://genshin.mingyulab.com/favicon.ico',2,'https://genshin.mingyulab.com',NULL);
COMMIT;
```

以上命令用于查看数据库中 `WebToolItem` 表。

注意格式，`Id` 从 `12` 开始，`Order` 从 `0` 开始，`JavaScript` 的值填入 `NULL`。

``` powershell
sqlite> INSERT INTO WebToolItem VALUES(15,'TEST','https://xunkong.cc/images/logo.64.webp',3,'https://xunkong.cc',NULL);
```

以上命令用于在数据库中插入数据。

![image](https://user-images.githubusercontent.com/91671226/204408370-c0850a63-43b2-4a56-85e8-af14871fb540.png)

以上是上传成功的结果。

``` powershell
sqlite> UPDATE WebToolItem SET Title = '你干嘛' WHERE Id = 15;
```

以上命令用于更新数据。

![image](https://user-images.githubusercontent.com/91671226/204408611-b47b3176-f239-4c9c-8a15-f323b0525aa3.png)

以上是更新成功的结果。

``` powershell
sqlite> DELETE FROM WebToolItem WHERE Id = 15;
```

以上命令用于删除数据。

![image](https://user-images.githubusercontent.com/91671226/204408758-7a7295c7-14c4-4d42-9218-675a64f374c0.png)

以上是删除成功的结果。

实时保存，无需执行保存命令。

若要进一步学习 `SQLite`，推荐 [菜鸟教程](https://www.runoob.com/sqlite/sqlite-tutorial.html)。

``` powershell
sqlite> .exit
PS> 
```

**Comment by Scighost** [comment]
更新到 1.2.4
