### ISSUE TITLE
米游社cookie格式升级至v2，无法登录

### ISSUE THREAD

**Issue by xing-yv** [xunkong/xunkong#326]
### 问题描述

米游社cookie格式升级至v2，无法登录，希望可以更新一下QAQ

### 复现步骤

在应用内网页登录显示获取不到cookie，用书签也获取不到cookie，在开发人员工具中发现cookie已升级至v2。

### 截图

![屏幕截图 2022-11-30 013438](https://user-images.githubusercontent.com/109603760/204601477-d94c1f1d-6c83-42c8-b2bd-c9ff37b61729.png)

### 系统版本

Windows 11 22H2

### 寻空版本

1.2.3.0

### 日志

[log_20221130_011811.txt](https://github.com/xunkong/xunkong/files/10115658/log_20221130_011811.txt)

**Comment by fivefirex** [comment]
看一眼置顶 issue 吧。#315

**Comment by Scighost** [comment]
更新到 1.2.4
