### ISSUE TITLE
获取不到cookie

### ISSUE THREAD

**Issue by XXSSSXX** [xunkong/xunkong#328]
### 问题描述

Cookie does not contain "account id" or "cookie token"

### 复现步骤

按步骤登录米友社但是获取不到cookie

### 系统版本

Windows 10 21H2

### 寻空版本

1.2.3.0

**Comment by fivefirex** [comment]
求求了，看一眼置顶 issue。

#315

**Comment by Scighost** [comment]
更新到 1.2.4
