### ISSUE TITLE
图标颜色

### ISSUE THREAD

**Issue by ahshy1996** [xunkong/xunkong#329]
### 你的建议

以前图标颜色不是白色金色吧，现在跟原神图标颜色太像了，会造成困扰

**Comment by fivefirex** [comment]
~~我寻思这图标也不像啊~~

**Comment by gszshdzz** [comment]
~~其实你电脑里相似的图标一大堆~~
之前的图标是夜兰的，但现在妹妹的图标跟原神感觉区分度不是很低，寻空偏黄原神偏白，如果你有高频率打开原神的需求可以扔任务栏用快捷键启动
或者是你桌面图标太多了，但习惯之后图标只是一个辅助定位，可以把这两个放远一点
