### ISSUE TITLE
1.2.4版本更新后无法添加第2个账号

### ISSUE THREAD

**Issue by wtof1996** [xunkong/xunkong#331]
### 问题描述

之前的版本可以添加第2个账号，更新1.2.4后有些问题因此退出了之前添加的2个账号。
但是更新后发现，登陆账号A以后，使用网页登陆尝试登陆账号B时发现打开的米游社页面仍然为账号A的页面（之前版本应该是未登录的页面，这样就可以登录账号B）。

### 复现步骤

1、先退出所有账号，然后重启软件
2、登陆一个账号
3、再尝试登陆第二个账号，问题复现

### 截图

![image](https://user-images.githubusercontent.com/5406275/205308400-663ff2b8-e433-4566-9d86-27a382ec97b3.png)
如图所示， 登陆一个账号以后，再登陆第二个账号，红圈处会仍然显示第一个账号登陆的米游社页面。

### 系统版本

Windows 10 22H2  19045.2251

### 寻空版本

1.2.4.0

**Comment by Scighost** [comment]
米哈游把 `https://bbs.mihoyo.com/ys/` 重定向到了 `https://www.miyoushe.com/ys/`，而应用只会自动清除前者的 cookie，在后者的界面中仍处于登录状态。

按照以下步骤手动清除 cookie：

- 确保网页在 `https://www.miyoushe.com/ys/` 这个界面
- 鼠标右键菜单->检查
- 在弹出的 DevTools 的上方点击 `应用程序`
- 左边的 `存储` 区域找到 `Cookie`
- 右键点击 `https://www.miyoushe.com`，然后点击 `清除`
- 关闭 DevTools，刷新网页

<img width="388" alt="image" src="https://user-images.githubusercontent.com/61003590/205316151-fde64f50-8800-4a5d-af08-f3002f0a5a05.png">

**Comment by wtof1996** [comment]
已尝试上述方法，但仍然存在问题：
1、先将现有账号删除，然后退出程序，并且结束后台所有的edge进程
2、重新启动程序，先登陆账号A
3、成功登陆账号A后，按上述方法尝试登陆账号B，清除Cookie并刷新页面后，可以在页面上正常登陆账号B，并且点击对勾以后提示已添加账号，但账号列表仍然只有一个账号A
4、此时切到主页也可以看到之前登陆的账号A无法获取实时便笺，提示没有绑定信息，主页也看不到账号B的信息：
![image](https://user-images.githubusercontent.com/5406275/205326338-0d89a700-8340-4c9c-b8a5-1f350d8c6013.png)

**Comment by Scighost** [comment]
登录第一个账号后，退出程序，然后在应用的系统设置中点击**重置**，再登陆第二个账号。

<img width="161" alt="image" src="https://user-images.githubusercontent.com/61003590/205440382-7f7b99a1-1495-4616-bdfa-8dc796fc0f70.png">

<img width="305" alt="image" src="https://user-images.githubusercontent.com/61003590/205440361-47708f7a-c6a2-4544-abe7-179c97e2e3fb.png">

**Comment by wtof1996** [comment]
重置了还是不行:
![image](https://user-images.githubusercontent.com/5406275/205442165-1afa5532-4841-46ed-a1d5-a710f25bc941.png)
![image](https://user-images.githubusercontent.com/5406275/205442180-516cac17-d194-4506-bb67-118a0568734d.png)
![image](https://user-images.githubusercontent.com/5406275/205442191-7ecb2f10-a720-4bec-9679-c844b099c6e9.png)

此外，也试过单独输入第二个账号的cookie，添加以后没有提示，并且也会导致第一个已登陆的账号无法正常使用便笺等功能。

**Comment by fivefirex** [comment]
+1 同样问题

**Comment by fivefirex** [comment]
+1 同样问题

**Comment by Scighost** [comment]
在这个网址中登陆
https://bbs.mihoyo.com/ys/strategy

**Comment by CarlLester** [comment]
> 在这个网址中登陆 https://bbs.mihoyo.com/ys/strategy

感谢，已解决。给遇到相同问题的看看：
1，寻空删除所有账号
2，把获取米游社cookie添加到书签
3，Chrome打开无痕窗口，打开上面网址登录账号，点击获取米游社cookie的书签
4，进入寻空输入刚获取的cookie
5，重复34添加第二个账号

**Comment by aaaol** [comment]
> 在这个网址中登陆 https://bbs.mihoyo.com/ys/strategy

这方法真不错
我的解决方案是
打开寻空
通过网页添加 粘贴这个地址
登录打✔

测试可以退出账号 继续登录另一个账号添加
