### ISSUE TITLE
获取祈愿记录后显示错误

### ISSUE THREAD

**Issue by Fachep** [xunkong/xunkong#332]
### 问题描述

图一是获取后的结果
图二是重新切换到本账号的正常状态

### 复现步骤

祈愿记录->获取记录->从缓存文件

### 截图

![image](https://user-images.githubusercontent.com/31302548/205331756-3b210f7b-a4bd-4c86-b61a-360d45adec8c.png)
![image](https://user-images.githubusercontent.com/31302548/205331910-570ac010-e61d-4e15-b14e-3967e567b2e8.png)

### 系统版本

Winodws 10 22H2

### 寻空版本

1.2.4.0 商店版

**Comment by Fachep** [comment]
又抽了几发没有复现0.0

**Comment by Scighost** [comment]
大概率是因为卡池数据没有下载完成
