### ISSUE TITLE
关于更新提示

### ISSUE THREAD

**Issue by soratanmer** [xunkong/xunkong#333]
### 你的建议

![image](https://user-images.githubusercontent.com/23238799/205426641-8ed7e5b9-03b8-421a-843a-c1de82f1258d.png)

既然都上架了 Microsoft Store 了，那就让 Store 自动更新好啦，打开软件看到这个更新提示，让用户自己去 GitHub 下载安装真的很膈应人，要知道国内不是所有地方都能上 GitHub  的。。。

**Comment by fivefirex** [comment]
不是很明白你的意思。Microsoft Store 和 GitHub Release 是区分的两个版本，~~虽然共用一个数据库~~但两个版本互不冲突，Store 版无法同步侧载版的版本。

**Comment by soratanmer** [comment]
> 不是很明白你的意思。Microsoft Store 和 GitHub Release 是区分的两个版本，~虽然共用一个数据库~但两个版本互不冲突，Store 版无法同步侧载版的版本。

我装的就是 Store 版本，新版本上线的时候 Store 版得审核吧，那上线时间应该会比 GitHub Release 版慢，这时候 Store 版的首页就会弹出“商店版无法获取新版本的信息”，提示用户去下载 GitHub Release 版来更新，既然这样那为什么还要上线 Store 版？

我个人膈应的就是这一点，既然都上线 Store 版本了那么这个更新提示就不应该出来。

**Comment by fivefirex** [comment]
这倒确实。

**Comment by Scighost** [comment]
> 我装的就是 Store 版本，新版本上线的时候 Store 版得审核吧，那上线时间应该会比 GitHub Release 版慢，这时候 Store 版的首页就会弹出“商店版无法获取新版本的信息”，提示用户去下载 GitHub Release 版来更新，既然这样那为什么还要上线 Store 版？
> 
> 我个人膈应的就是这一点，既然都上线 Store 版本了那么这个更新提示就不应该出来。

呵，你真的点过这个**下载并安装**？

**Comment by soratanmer** [comment]
> > 我装的就是 Store 版本，新版本上线的时候 Store 版得审核吧，那上线时间应该会比 GitHub Release 版慢，这时候 Store 版的首页就会弹出“商店版无法获取新版本的信息”，提示用户去下载 GitHub Release 版来更新，既然这样那为什么还要上线 Store 版？
> > 我个人膈应的就是这一点，既然都上线 Store 版本了那么这个更新提示就不应该出来。
> 
> 呵，你真的点过这个**下载并安装**？

点过啊，直接跳到 GitHub，不过我没下载就是了，老老实实等 Store 版自动更新。

**Comment by fivefirex** [comment]
> > > 我装的就是 Store 版本，新版本上线的时候 Store 版得审核吧，那上线时间应该会比 GitHub Release 版慢，这时候 Store 版的首页就会弹出 “商店版无法获取新版本的信息”，提示用户去下载 GitHub Release 版来更新，既然这样那为什么还要上线 Store 版？
> > > 我个人膈应的就是这一点，既然都上线 Store 版本了那么这个更新提示就不应该出来。
> > 
> > 
> > 呵，你真的点过这个**下载并安装**？
> 
> 点过啊，直接跳到 GitHub，不过我没下载就是了，老老实实等 Store 版自动更新。

![image](https://user-images.githubusercontent.com/91671226/207285972-ac91dc29-30c1-4e0a-9deb-7ef5b29b5bf0.png)

也许你可以尝试读读源代码
