### ISSUE TITLE
建议增加一个自定义设置的快速入口和使用说明

### ISSUE THREAD

**Issue by yjc20061008** [xunkong/xunkong#335]
### 你的建议

自定义设置需要在浏览器或者运行里输入xunkong://settings才能打开，建议在设置里增加一个按钮点一下就可以打开自定义设置；
如果可以也在GitHub上写一个键值和用途的对照表

**Comment by Scighost** [comment]
`xunkong://settings` 在未验证的情况下直接修改存储的设置项，不应该作为一个公开的入口。
你要的键值表：https://github.com/xunkong/xunkong/blob/main/App/Models/SettingKeys.cs
