### ISSUE TITLE
关于云·原神的支持

### ISSUE THREAD

**Issue by lihaoDai** [xunkong/xunkong#337]
### 你的建议

不知道可不可以添加对云·原神PC端的支持，比如祈愿记录获取

**Comment by gszshdzz** [comment]
不太可能吧，你可以用别的工具（比如[胡桃](https://github.com/DGP-Studio/Snap.Hutao)，这个要抓包，他不给直接复制，可以找找别的）利用stoken获取链接然后输进去

**Comment by yjc20061008** [comment]
再等等吧，云原神PC还在测试，等到正式上线以后才可能有

**Comment by gszshdzz** [comment]
> 再等等吧，云原神PC还在测试，等到正式上线以后才可能有

奥奥不好意思，我以为是查看记录也是云端进行，刚才测试一下确实是本地查看

**Comment by Scighost** [comment]
#391
