### ISSUE TITLE
[Feature Requests] 主页的大图能否去掉，只去除大图或者减小

### ISSUE THREAD

**Issue by POEG1726** [xunkong/xunkong#345]
### 你的建议

![image](https://user-images.githubusercontent.com/73727028/209792820-5265f971-6d79-4e5b-a2e6-8ce8a320f817.png)
我认为太大了，作为主页应该能够清晰明了的看到养成计划，而不是点进主页后仍需下滑
![image](https://user-images.githubusercontent.com/73727028/209792946-69f7dd2a-df70-4c47-8b11-c1c5a041ebae.png)

一个小小的请求，感谢XUNKONG开发组！

**Comment by yjc20061008** [comment]
寻空>设置>主页壁纸 关了就行了
