### ISSUE TITLE
1.2.5版本更新包无法安装

### ISSUE THREAD

**Issue by z7arf** [xunkong/xunkong#346]
### 问题描述

无法验证此应用包的发布者证书。请与系统管理员或应用开发人员联系，以获取具有验证证书的新应用包。必须验证应用包中签名的根证书和所有直接证书(0x800B010A)

### 复现步骤

下载安装包，解压，安装Xunkong.Desktop.Package_1.2.5.0_x64.msixbundle，弹窗

### 截图

![PO4{A1PWHSL)WI4VV8V@BF](https://user-images.githubusercontent.com/121581760/209872557-6be42bbf-db25-4a91-a250-245d00df4991.png)

### 系统版本

win10 21H2

### 寻空版本

1.2.5

### 日志

[log_20221129_202124.txt](https://github.com/xunkong/xunkong/files/10316484/log_20221129_202124.txt)
[log_20221129_205957.txt](https://github.com/xunkong/xunkong/files/10316485/log_20221129_205957.txt)
[log_20221130_083350.txt](https://github.com/xunkong/xunkong/files/10316486/log_20221130_083350.txt)
[log_20221201_235005.txt](https://github.com/xunkong/xunkong/files/10316487/log_20221201_235005.txt)
[log_20221202_151257.txt](https://github.com/xunkong/xunkong/files/10316488/log_20221202_151257.txt)
[log_20221202_151416.txt](https://github.com/xunkong/xunkong/files/10316489/log_20221202_151416.txt)
[log_20221202_151733.txt](https://github.com/xunkong/xunkong/files/10316490/log_20221202_151733.txt)
[log_20221202_155550.txt](https://github.com/xunkong/xunkong/files/10316492/log_20221202_155550.txt)
[log_20221203_233409.txt](https://github.com/xunkong/xunkong/files/10316493/log_20221203_233409.txt)
[log_20221207_234630.txt](https://github.com/xunkong/xunkong/files/10316494/log_20221207_234630.txt)
[log_20221208_135510.txt](https://github.com/xunkong/xunkong/files/10316495/log_20221208_135510.txt)
[log_20221208_155902.txt](https://github.com/xunkong/xunkong/files/10316496/log_20221208_155902.txt)
[log_20221209_011826.txt](https://github.com/xunkong/xunkong/files/10316497/log_20221209_011826.txt)
[log_20221209_155151.txt](https://github.com/xunkong/xunkong/files/10316498/log_20221209_155151.txt)
[log_20221210_151154.txt](https://github.com/xunkong/xunkong/files/10316499/log_20221210_151154.txt)
[log_20221212_122901.txt](https://github.com/xunkong/xunkong/files/10316500/log_20221212_122901.txt)
[log_20221216_195725.txt](https://github.com/xunkong/xunkong/files/10316501/log_20221216_195725.txt)
[log_20221226_001144.txt](https://github.com/xunkong/xunkong/files/10316502/log_20221226_001144.txt)
[log_20221227_051534.txt](https://github.com/xunkong/xunkong/files/10316503/log_20221227_051534.txt)
[log_20221228_044011.txt](https://github.com/xunkong/xunkong/files/10316504/log_20221228_044011.txt)
[log_20221229_044336.txt](https://github.com/xunkong/xunkong/files/10316505/log_20221229_044336.txt)
[log_20221117_022935.txt](https://github.com/xunkong/xunkong/files/10316506/log_20221117_022935.txt)
[log_20221117_145926.txt](https://github.com/xunkong/xunkong/files/10316507/log_20221117_145926.txt)
[log_20221118_132558.txt](https://github.com/xunkong/xunkong/files/10316508/log_20221118_132558.txt)
[log_20221118_133427.txt](https://github.com/xunkong/xunkong/files/10316509/log_20221118_133427.txt)
[log_20221118_134512.txt](https://github.com/xunkong/xunkong/files/10316510/log_20221118_134512.txt)
[log_20221118_214232.txt](https://github.com/xunkong/xunkong/files/10316511/log_20221118_214232.txt)
[log_20221118_214847.txt](https://github.com/xunkong/xunkong/files/10316512/log_20221118_214847.txt)
[log_20221119_205835.txt](https://github.com/xunkong/xunkong/files/10316513/log_20221119_205835.txt)
[log_20221121_000144.txt](https://github.com/xunkong/xunkong/files/10316514/log_20221121_000144.txt)
[log_20221121_150241.txt](https://github.com/xunkong/xunkong/files/10316515/log_20221121_150241.txt)
[log_20221124_122532.txt](https://github.com/xunkong/xunkong/files/10316516/log_20221124_122532.txt)
[log_20221128_161650.txt](https://github.com/xunkong/xunkong/files/10316517/log_20221128_161650.txt)

**Comment by yjc20061008** [comment]
应该是放错文件了吧，这GitHub里的Assets和备用链接都是侧载版，供开发者使用的。
微软商店更新正常，微软商店的更新包可以从https://store.rg-adguard.net这个网址解析得到
@Scighost 你放错文件了

**Comment by Scighost** [comment]
> 应该是放错文件了吧，这GitHub里的Assets和备用链接都是侧载版，供开发者使用的。 微软商店更新正常，微软商店的更新包可以从https://store.rg-adguard.net 这个网址解析得到 @Scighost 你放错文件了

没错，备用链接中就是侧载版的文件，商店版因为审核会滞后发布，不适合做自动化更新。
