### ISSUE TITLE
祈愿获取失败

### ISSUE THREAD

**Issue by stevened7246** [xunkong/xunkong#347]
### 问题描述

国际服使用从缓存获取失败

### 复现步骤

安装国际服后使用从缓存文件获取记录

### 截图

![image](https://user-images.githubusercontent.com/97885306/210060768-3eea4cdc-d8fe-422d-9e54-d171be47ff17.png)

### 系统版本

Windows 11 工作站 22H2 

### 寻空版本

1.2.5.0侧载版

### 日志

未有相关日志出现

**Comment by sirarikako** [comment]
国服同样问题
Windows 11 22H2，从商店安装~
商店更新最新版，选择国服也还是有问题。错误信息还是-101

**Comment by stevened7246** [comment]
> 国服同样问题 Windows 11 22H2，从商店安装~ 商店更新最新版，选择国服也还是有问题。错误信息还是-101

我现在不知道为什么又好了，可以尝试一下更新最新版看看

**Comment by sirarikako** [comment]
> > 国服同样问题 Windows 11 22H2，从商店安装~ 商店更新最新版，选择国服也还是有问题。错误信息还是-101
> 
> 我现在不知道为什么又好了，可以尝试一下更新最新版看看

刚刚更新的。。明天重启一下再试试好了。

**Comment by sirarikako** [comment]
依然不行。。奇怪了。。

**Comment by Scighost** [comment]
<img width="253" alt="image" src="https://user-images.githubusercontent.com/61003590/213728189-479bb8f3-ebf3-4f6f-9747-b7ced909ccf1.png">
点击启动游戏，能不能正常启动

**Comment by sirarikako** [comment]
> 

可以启动。

**Comment by Scighost** [comment]
尝试按照这个步骤做一下
https://github.com/xunkong/xunkong/issues/220#issuecomment-1383074044
