### ISSUE TITLE
角色越来越多了，希望卡池历史页面能增加自适应或添加横向滚动条

### ISSUE THREAD

**Issue by zgh323** [xunkong/xunkong#353]
### 你的建议

右侧已经显示不全了
![image](https://user-images.githubusercontent.com/46866448/211025882-47204fe6-8a55-4ce4-a9a0-b2d89f5e3579.png)

**Comment by Trrrrw** [comment]
鼠标左键按住可以左右拖动

**Comment by zgh323** [comment]
> 鼠标左键按住可以左右拖动

谢谢，刚知道
