### ISSUE TITLE
添加账号cookie出错

### ISSUE THREAD

**Issue by jiuerd** [xunkong/xunkong#355]
### 问题描述

本来用得好好的，今天点了一下更新之后就发现账号清空了，然后登录不上去了

### 复现步骤

添加账号
网页登录/输入Cookie

### 截图

![1](https://user-images.githubusercontent.com/4180650/211344057-234c0091-cc0e-454d-8258-ea4d1ddd883e.png)

### 系统版本

win11 21H2

### 寻空版本

1.2.5.0

### 日志

[log_20230109_232338.txt](https://github.com/xunkong/xunkong/files/10374399/log_20230109_232338.txt)

**Comment by Scighost** [comment]
数据库已损坏，在备份文件夹（Xunkong\Backup\Database）中找最新的文件替换一下。
