### ISSUE TITLE
2022 年度总结建议贴

### ISSUE THREAD

**Issue by Scighost** [xunkong/xunkong#356]
点子有限，想不到更多更好的内容了，欢迎提出建议。

## 数据来源

用户个人报告中的内容均来自本地已保存的 **祈愿记录、旅行札记、深境螺旋** 的数据，各数据包含以下信息：

### 祈愿记录

每次记录的

- 时间
- 卡池类型
- 物品名称
- 物品类型
- 物品星级

### 旅行札记

每次奖励的

- 时间
- 类别（原石或摩拉）
- 奖励来源
- 数值

### 深境螺旋

- 第几期
- 开始结束时间
- 战斗次数
- 战斗胜利次数
- 最深抵达
- 获取星星
- 战斗数据榜（最多击破、最强一击...）
- 每次战斗开始时间
- 最后一次战斗的阵容
- 出战角色等级

**Comment by pbxs666** [comment]
我先来说吧：之前在记事本上写了一大堆我自己对寻**空**的“规划”，没保存，时间长了，缓存丢了，哎。重新码一遍。
之前甚至还打算自己完成一些功能的开发，把**寻空**的源码放在电脑上很久了，因为忙，一直没动手，哈哈。
![1](https://user-images.githubusercontent.com/47630168/211532894-725be8cf-f01d-4cae-be81-68919b56bca3.jpg)

既然作者开口了，我就说说，有的提议就纯属口嗨，还望作者多多包含。

1.皮肤换装功能。
我之前翻过缓存文件夹，发现寻空下载的图片缓存其实是包含了角色所有皮肤素材（闲替时装也有），包括抽卡立绘、正面侧面的头像。就想着是不是之前有过规划出一个换装功能，之后成废案了。
我设想的是在**角色图鉴**板块不是可以查看皮肤装扮吗，在该板块下切换装扮，软件会保存该角色的皮肤状态，之后在**寻空**里凡是有关该角色的图片素材全部换成对应的皮肤图片素材（包括抽卡立绘，正面侧面的头像）。

2.每期卡池的角色展示方式
在软件的自带素材文件夹里发现了几张至今未用上的图
![2](https://user-images.githubusercontent.com/47630168/211535756-d8d2f1d8-4577-4eb0-81ab-87fafeeadb56.jpg)
我猜测这又是废案吗？哈哈，有几张图片是卡池的背景图，猜测作者可能开始要做成游戏里那样根据UP的角色属性，用相应的卡池背景+角色立绘动态生成卡池角色图？纯粹猜测，猜测，哈哈。倒是武器卡池那张图现在在**武器图鉴**里用上了。

3.单独增加语音的缓存清理
之前的缓存是分成两个文件夹的：成就相关图片素材和角色语音缓存是一处，另一处是其余所有图片。现版本把缓存放在一起了。图片缓存很重要，属于基本数据。但是语音缓存就非必须了，试听一句就缓存一句，时间长了也挺大的。
所以能否增加一个单独清理语音缓存的功能。

4.取消缓存的时间限制
图片缓存经常失效也挺头疼的，可能跟我每周清理一次电脑有关。而且从xunkong服务器下载有时候会突然断线，只能重下、之前旧版本我记得是写了缓存30天清除，不知道现版本是不是还是这样设定，没仔细翻代码，看到有几句写了delay30什么的，不知道是不是跟这个有关。不知道这个跟版权或者Windows缓存什么的有关么，如果不行那就算了，要是没有风险的话我觉得这个限制没必要吧。
隔壁的HuTao也在用，之前好几个版本就没有缓存图片的功能，最近更新就加上了，软件里不用等待图片加载用着就很顺畅，也不知道用没有缓存失效的问题，毕竟刚更新没多久。他们家的上代Snap Genshin也是这样，图片缓存后就没失效过。

5.**养成计划**里的_天赋培养_和_武器突破_改动
这个要说的挺多的
①这个板块里的2个自板块的数据和图片我感觉都是从米游社来的，既然**寻空**本地已经缓存所有图片素材了，可以使用本地的图片吗？就像_周本掉落_那样。米游社的角色正面图不好看，跟大头照一样。而且天赋素材和武器突破材料的图片边角有白色空隙
https://uploadstatic.mihoyo.com/ys-obc/2020/04/10/15568211/fc803239634f9035664b818f08e42f08_1318047034254957238.png
https://uploadstatic.mihoyo.com/ys-obc/2021/08/22/6381993/36f61a67d9edcb783ded72744e5a0e8d_5670435633782694630.png
②副本的时间是乱的，_天赋培养_还好，顺序是123 123 321 321，_武器突破_的顺序就乱完了。我建议是：一种方案是提前手动编辑好周几哪个天赋本材料本可打，按照周一二三顺序排好，角色按照数据库GenshinData.db里CharacterInfo的SortID顺序筛选材料，对号加入队列就好了（就跟_周本掉落_那样，材料和角色排序就很完美，材料是按照游戏里的物品ID排序的，角色按照数据库排序），另一种方案干脆在数据库里加入相应项，全部交给数据库算了，不过效率要慢一点，也比第一种方案麻烦，还要建表。
③埃洛伊的背景色还是红的

6.**角色图鉴**板块微调下顺序
这个没大问题，只是里面角色的顺序和游戏里的有点不一样，游戏里排序规则是：按照入池顺序排序，在此基础上5星4星排序，5星在前。**寻空**的数据库GenshinData.db里排序刚好反了，4星在前，5星在后。本质问题是数据库里CharacterInfo的SortID有问题，这个微调下就好了。例如：3.3版本应该是流浪者排在珐露珊前面
之前我自己都调好了，一直没发帖子，不知道作者的数据库的数据是全部自动生成的还是其他，看到之前1.2.3版本更新公告里说过“原神数据库 [GenshinData](https://github.com/Dimbreath/GenshinData) 因 DMCA 停止更新”，**寻空**的数据库数据要是是从其他地方自动调取生成的，那我这边手动改了SortID也没用，更新后就有变回去了。
这个从其他地方也有佐证，角色语音是从米游社来的，之前雷电将军语音有问题，角色收到赠礼之类的语音缺失，后来米游社更新了，这边也就更新了，应该是用程序直接爬的吧，这要是手动写入数据库太慢了。

7.**祈愿记录**和**深境螺旋**能够手动增加记录
**祈愿记录**倒是有个管理记录功能，也可以导出，修改后再导入，也许能达到增加记录的效果（猜测，没试过😂。或者暴力点，直接改数据库🤣）。
开服玩家，想把很久之前的记录都导入到寻空里，虽然详细记录游戏里也找不到了，但可以根据角色的入队时间和命座情况大概推测下，把空白补上，我自己的**祈愿记录**2.2以前版本的记录都是空的，想大概编几个数据填进去，最起码不空，我的公子1命，现在软件只记录出了1个公子。

8.各元素旅行者的天赋，求求了
这个往简单了做可以把不同元素的旅行者当成不同角色，类似安柏Wiki(https://ambr.top/chs)那样
![3](https://user-images.githubusercontent.com/47630168/211547805-5c4121b3-ce17-4a66-9fc6-ab439e214530.jpg)
往复杂了做就得添加元素切换按钮了，麻烦了。

9.软件内的连接可否其他增加跳转方式
调用系统默认浏览器打开，这样也能用浏览器的插件什么的，比如米游社地图就可以用椰羊的油猴脚本——志琼，锄大地挺舒服的。
软件自带的webview不好用，而且打开的窗口看似关了，其实进程都在后台。

10.软件每打开一个板块，就占一些内存，内存不回收，内存管理有问题。用的时间长了，内存占用暴涨，这个应该不是**寻空**的问题，可能是框架问题？

11.最后再碎碎念一下，**实时便笺**还有办法吗
现版本**磁贴**还是时不时抽风，更新不了，当然前提是没有触发风控，就单纯的点击了不会更新。所以我电脑还一直保留_1.X_版本的**寻空**，当然只是使用**磁贴**功能，旧版本的功能正常。
顺便问一下，磁贴里的图片素材是从米游社来的吧，我意思是以后游戏里派遣了新的角色，磁贴应该能正常显示角色的头像吧。
我看现在旧版寻空不维护了，角色信息只能显示到提纳里，如果我派遣纳西妲会怎样？图片能正常显示否？今晚自己先试试。
![4](https://user-images.githubusercontent.com/47630168/211550357-b5695c89-f786-47d8-befa-016ff4a011dc.jpg)
对了，我现在浏览器在用一个插件，挺好用的，类似**实时便笺**，即便触发风控，也能自己解决安全验证，不用到手机米游社验证。我意思作者看看能从这里有什么借鉴或者启发，能自己过安全验证，这样就不怕米游社风控了。
https://github.com/daidr/paimon-webext
![5](https://user-images.githubusercontent.com/47630168/211551538-566470f8-e780-4ba3-aa87-c6b5d1242fe2.jpg)


就这么多，谢谢作者这么长时间的付出，**寻空**是个很好用的软件，以后还会一直使用的。尤其是UI很不错。成就统计是寻空、椰羊，HuTao这仨里做的最好看的，成就导出要不要更新下支持HuTao，椰羊那边现已经支持HuTao了。现在软件里还显示的是隔壁上代软件——Snap Genshin，这个已经停止更新了。
![6](https://user-images.githubusercontent.com/47630168/211553511-c648aecf-f238-45a7-9bca-4875d1ad1093.jpg)
因为这个建议不影响软件本身的功能，就放在这里说啦。
虽然HuTao有深渊、圣遗物、武器、队友搭配等等统计数据，但那是建立在有庞大数据的前提下的，这两个软件我觉得方向定位不一样，作者只需坚持自己的软件定位就可以了，有了不同才能体现出各有各的亮点，不是吗？哈哈。

最后作者一定要注意安全，谨防新冠啊。

**Comment by Scighost** [comment]
@pbxs666 
哇，写了这么多！不过这里是仅给**2022年度总结**这个功能收集建议用的，我把你的评论移动到新 issue 了。
