### ISSUE TITLE
关于寻空提供的segoe fluent icons版本过低

### ISSUE THREAD

**Issue by GUANXINPENG** [xunkong/xunkong#358]
### 你的建议

如题，寻空提供的segoe fluent icons字体为1.00，我是在win10的时候安装的寻空，之后我升级了win11随后任务管理器部分图标和请勿打扰图标显示异常——如图
![image](https://user-images.githubusercontent.com/89452691/211774188-b7cd84f4-dff3-41d6-b5a4-6e131f484af6.png)
发现问题后我想起曾经安装过该字体，重新安装无果。去设置中找到该字体，发现含有两个版本1.00和1.06，卸载1.06后显示正常
![image](https://user-images.githubusercontent.com/89452691/211774622-8532aeb7-45a5-480d-879d-55a94a85b1c1.png)
希望作者能够提供更新版本的字体包

**Comment by Scighost** [comment]
1.00 是从[微软网站](https://learn.microsoft.com/zh-cn/windows/apps/design/downloads/#fonts)下载的，1.06 应该是 Windows 更新提供的。
