### ISSUE TITLE
祈愿记录页面的性能优化

### ISSUE THREAD

**Issue by Scighost** [xunkong/xunkong#359]
众所周知，祈愿记录页面的性能一直是寻空的大问题，经常会出现卡死的情况。为了弄清楚问题所在，首先得知道在转圈或卡死的时候，程序在干嘛。（以下分析基于 1.2.5 版本）

> 可能存在部分名词或术语错误，别在意，又不是不能看.jpg

## 性能分析

忽略一些小的开销，从点击祈愿记录页面到可以操作这段时间，大致可分为四个阶段：解析、延迟、计算、渲染。

在性能探查器中分析这一段时间的帧率，中间这一段曲线低谷就是 UI 卡死的地方。使用绿竖线分割的四块区域大致对应上述的四个阶段。

<img width="344" alt="image" src="https://user-images.githubusercontent.com/61003590/211777180-a5a3ffbc-ffd7-429d-b91f-816500d38d2d.png">

### 解析页面

从 11.9s 到 12.5s 这第一个低谷是解析页面的时间，解析+布局大致用了 450ms，这段时间有页面切换时的过渡动画，所以很少会感觉到卡顿的存在。

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/61003590/211769816-11ba7930-8f2b-405c-af5b-7c9e3c4375bc.png">

### 延迟

解析（切换）页面和计算阶段之间，我加了 800ms 的延迟。这个延迟不应该存在，不过没有办法，不加甚至加的少了都有可能造成程序卡死的情况（不是转圈，是卡死）。这一阶段也存在帧数波动，但是感知不强。

### 计算

计算阶段是指结合祈愿记录、角色和卡池信息，计算出展示页面所需要的数据，这一部分尽管写得也不太行，但是绝大多数人不会超过 500ms，就算是几万抽的氪佬也不会超过 1000ms。

### 渲染

这一阶段对资源消耗最大的是布局，渲染反而没有多少压力。布局是解析界面元素生成可视化树的过场，如果元素越多嵌套越复杂，消耗的时间越长。

<img width="705" alt="image" src="https://user-images.githubusercontent.com/61003590/211775824-3cf28748-fdc1-4571-825a-6bc67921aa69.png">

这里截取了布局过程的一部分，在 1.13s 的布局过程中，同一时间的下面全是解析CachedImage，太多了数不清，大概有几百个吧，可以说解析 CachedImage 是造成页面卡顿的罪魁祸首。而最后帧率上升的那一段则是渲染图片的过程，真正渲染图片的时间反而没多少。

## 原因探究

为了优化图片的加载时间，我封装了 CachedImage 这个东西，它能从网络下载并缓存图片文件，并能直接读取本地已缓存的文件，减少网络开销。CachedImage 在寻空中的用途非常广泛，基本上显示的每张图片背后都有它。

之前的某个版本中，为了加入复制图片的功能，大幅度增加了 CachedImage 的复杂度，如下图所示，每张图片都可以通过右键打开这样一个菜单。相关代码 https://github.com/xunkong/xunkong/blob/1.2.5/App/Controls/CachedImage.xaml

<img width="174" alt="image" src="https://user-images.githubusercontent.com/61003590/211779278-1fa53213-0dbc-4853-9b15-b46557a3be7f.png">

光是复杂度提高还不至于卡到如此地步，使用量也是关键。还是以上面那只可莉为例，其中可莉头像、火元素、五星背景都使用了 CachedImage，也就是每一个角色或武器都对应了三个 CachedImage，整个页面总共有两三百个 CachedImage，卡成这样也不奇怪了。

接下来把自己封装的 CachedImage 替换成开销最小最基础的 Image，对比测试一下二者的性能。结果如下图绿色线段内的部分，替换前需要约 4s，替换后仅需要约 2s 。

<img width="219" alt="image" src="https://user-images.githubusercontent.com/61003590/211796157-b203ffd1-c295-4c9b-8176-c53ae608c1b0.png">

## 改进方向

一是优化图片控件，应用内的大部分图片替换成更简单的控件，也就不能再打开右键菜单了。

二是拆分原有祈愿记录页面的功能，在下图所示的三个标签之间切换的时候能感受到明显卡顿，事实上这三个标签同样增加了页面元素的复杂程度，改进后此功能将由左侧导航栏的二级菜单切换。

<img width="300" alt="image" src="https://user-images.githubusercontent.com/61003590/211797312-6ca69313-a362-44da-946d-97df0daefe9d.png">

**Comment by Lightczx** [comment]
右键菜单不影响UI的速度吧，在不打开菜单的情况下应该是没有UI负荷的

**Comment by Scighost** [comment]
> 右键菜单不影响UI的速度吧，在不打开菜单的情况下应该是没有UI负荷的

确实是这样，刚才测试了一遍，Flyout 只有在显示的时候才加入到可视化树，并且图片加入右键菜单后没有发生明显的 UI 变慢现象。

经过你的提醒，我猜测因为之前的 CachedImage 继承自 UserControl，才出现了大量解析的步骤。

**Comment by Lightczx** [comment]
应该是winui的XamlParser性能比较差导致的

**Comment by SkoomaEngine** [comment]
原来是用这种方式来解决的吗？太厉害了…（艾琳并感）
