### ISSUE TITLE
获取米友社信息时提示不知道这样的主机

### ISSUE THREAD

**Issue by hkkkkk** [xunkong/xunkong#361]
### 问题描述

![6E~CNJGM_2_$(%AVVT}83%9](https://user-images.githubusercontent.com/9104088/212478110-1b3abecf-2c60-4571-bb5d-467989c03410.png)

### 复现步骤

获取角色信息 札记 都会出现这个问题

### 系统版本

Windos 10 21H2

### 寻空版本

1.2.5.0

### 日志

[log_20230114_225637.txt](https://github.com/xunkong/xunkong/files/10417964/log_20230114_225637.txt)

**Comment by Scighost** [comment]
把系统代理关掉

**Comment by Yue-cn** [comment]
是否联网,DNS是否能解析
