### ISSUE TITLE
相册图片浏览界面底部的水平缩略图拖条，如果没有初始定位到预览图片的位置，感觉没啥用啊。

### ISSUE THREAD

**Issue by HyBoxwood** [xunkong/xunkong#364]
### 你的建议

![QQ截图20230115220248](https://user-images.githubusercontent.com/87700780/212545540-798262fb-c96e-4797-adfe-5eedc7c76c04.png)
下面这个真的能用吗，我点进来后它的初始位置是最新的图片，切换图片也不会跟随变动，我拖拽导航条到中间直接无响应闪退。
是还没写功能嘛，还是不打算做了，建议隐藏或者暂时删掉吧。

**Comment by Scighost** [comment]
我这儿没有问题，可能是设备不同的问题

**Comment by pbxs666** [comment]
> 我这儿没有问题，可能是设备不同的问题

我这里也有问题，底下的缩略图列表不会随着大图的切换滚动。相册页面是这样，角色图鉴页面查看立绘时也是这样

**Comment by Scighost** [comment]
先点一张小图，再滚动鼠标

**Comment by HyBoxwood** [comment]
我的意思是 这个东西
一 不能反映我在看那张图的位置 默认位置是拖条最左侧 
二 我左右换图片与这个东西无关 它加载图片还得吃内存导致卡崩什么的
三 如果它不能正确指示我在看的图和它的上张下张图片的话 它有什么用

**Comment by Scighost** [comment]
https://user-images.githubusercontent.com/61003590/215487318-ec423462-fc1d-48be-b6b5-be2f6bff0b27.mp4

**Comment by Lightczx** [comment]
![image](https://user-images.githubusercontent.com/36357191/215651993-4b02cd29-71d6-4fd6-8bef-8b8f411cf77a.png)

应该是这个原因，WinUI3的渲染层是默认Inactive的
@Scighost

**Comment by HyBoxwood** [comment]
![QQ截图20230204130505](https://user-images.githubusercontent.com/87700780/216749713-0c6cc36e-c456-4cbf-8f64-ff6cd020c9f0.png)
点下面能滚动 但是我如果从中间某张开始浏览 您让我点第一张图开始看吗 多一个我第一次点进来的时候代替我点一次我看的图的位置就好了

**Comment by Lightczx** [comment]
@Scighost [UIElement.StartBringIntoView](https://learn.microsoft.com/zh-cn/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.uielement.startbringintoview?f1url=%3FappId%3DDev16IDEF1%26l%3DZH-CN%26k%3Dk(Microsoft.UI.Xaml.UIElement.StartBringIntoView)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=windows-app-sdk-1.2)

**Comment by Scighost** [comment]
> @Scighost [UIElement.StartBringIntoView](https://learn.microsoft.com/zh-cn/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.uielement.startbringintoview?f1url=%3FappId%3DDev16IDEF1%26l%3DZH-CN%26k%3Dk(Microsoft.UI.Xaml.UIElement.StartBringIntoView)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=windows-app-sdk-1.2)

虽然没看懂这个api的文档，但是再滚动后调用它，不起作用。

**Comment by Lightczx** [comment]
Noting happen?

**Comment by Scighost** [comment]
> Noting happen?

无事发生。

其实是焦点元素的问题，解决方法是在切换图片前用 `Focus` 把底部的小图片预览区域设置为当前焦点。
