### ISSUE TITLE
请问能否增加米游社地图探索率等相关功能的查看？

### ISSUE THREAD

**Issue by living-alive** [xunkong/xunkong#365]
### 你的建议

如题，偶尔会有查看探索率、宝箱数的需求，这个功能目前只能去米游社手机端犄角旮旯里翻出来，或者将数据导入到一些不稳定的站点查看，如果寻空能增加这类功能的话就更好了。

**Comment by Scighost** [comment]
我知道你说的是什么，但是你先别急。

**Comment by living-alive** [comment]
> 我知道你说的是什么，但是你先别急。

ok，不急
![image](https://user-images.githubusercontent.com/63293483/212701637-defb1d2f-218a-4939-a42b-cd6aa1a8e09d.png)
