### ISSUE TITLE
主页实时便笺的验证账号功能似乎并不可用

### ISSUE THREAD

**Issue by wdw1007** [xunkong/xunkong#366]
### 问题描述

当米游社账户出现 1034 错误后, 点击主页实时便笺的验证账号按钮弹出新窗口, 随后在米游社界面跳转至登录页面

### 复现步骤

当出现 1034 错误后, 点击实时便笺卡片的验证账号功能即可复现

### 截图

![](https://user-images.githubusercontent.com/87262434/212606672-da90679b-0fd4-4924-a343-2980637f89d9.gif)

### 系统版本

Windows 10 22H2 19045.2130

### 寻空版本

1.2.5.2

### 日志

[log_20230116_134235.txt](https://github.com/xunkong/xunkong/files/10422864/log_20230116_134235.txt)

**Comment by Scighost** [comment]
<img width="98" alt="image" src="https://user-images.githubusercontent.com/61003590/212636940-6ac076e0-9928-4233-8ae5-c683ca8898e8.png">

Please login

重新登陆后呢？

**Comment by wdw1007** [comment]
还是不行, 点击登录仍无任何响应
![](https://user-images.githubusercontent.com/87262434/212666825-c7dd5de3-35be-4e06-a274-62513ffa216f.gif)

**Comment by Scighost** [comment]
当然没反应啦，因为没做这个功能。

<img width="185" alt="image" src="https://user-images.githubusercontent.com/61003590/212668113-846ce555-3fb1-4126-af35-e94affa4733c.png">

**Comment by wdw1007** [comment]
试了几次输入 cookie 后没用, 但网页登陆之后再验证账号就可以出验证了
![](https://user-images.githubusercontent.com/87262434/212674521-0614b9fd-61f8-4f34-9d45-20067ca8e88e.png)
