### ISSUE TITLE
建议为主窗口加上最小宽度。

### ISSUE THREAD

**Issue by Yue-cn** [xunkong/xunkong#368]
### 你的建议

(我是Wpf开发者，更多请看我个人的项目。)

如题，
窗口宽度过小会导致UI布局混乱。（如NavigaitonView在Minimal模式下，展开钮会无法使用。）
由于Windows App SDK的原因，自定义窗口变得困难，原版窗口不自带MinWidth等属性。

以下代码请不要挂Debugger，否则会有报错。
借鉴于 https://github.com/DGP-Studio/Snap.Hutao/blob/main/src/Snap.Hutao/Snap.Hutao/Core/Windowing/WindowSubclassManager.cs
附解决方案：
```
using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.UI.WindowsAndMessaging;

// 这些Using由Microsoft.Windows.CsWin32包动态生成。需在运行目录下创建NativeMethods.txt，标明需要使用的。

PInvoke.SetWindowSubclass(new(HWND), new(HwndSourceHook), 101, 0);

private unsafe LRESULT HwndSourceHook(HWND hwnd, uint uMsg, WPARAM wParam, LPARAM lParam, nuint uIdSubclass, nuint dwRefData)
{
    switch (uMsg)
    {
        case PInvoke.WM_GETMINMAXINFO:
            {
                double scale = Math.Round((double)Win32Helper.GetDpiForWindow(hwnd) / 100, 2);
                ProcessMinMaxInfo((MINMAXINFO*)lParam.Value, scale);
            }; break;
        case PInvoke.WM_NCRBUTTONDOWN:
        case PInvoke.WM_NCRBUTTONUP:
            {
                return new(0);
            }
    }
    return PInvoke.DefSubclassProc(hwnd, uMsg, wParam, lParam);
}

public unsafe void ProcessMinMaxInfo(MINMAXINFO* pInfo, double scalingFactor)
{
    pInfo->ptMinTrackSize.X = (int)Math.Max(848 * scalingFactor, pInfo->ptMinTrackSize.X);
    pInfo->ptMinTrackSize.Y = (int)Math.Max(300 * scalingFactor, pInfo->ptMinTrackSize.Y);
}


```
对了，我没有添加RemoveWindowSubclass，不过功能没什么大同小异。
在当前目录下创建 NativeMethods.txt，内容为：
```
// Const value
INFINITE
WM_GETMINMAXINFO
WM_NCRBUTTONDOWN
WM_NCRBUTTONUP

// Type definition
MINMAXINFO

// COMCTL32
DefSubclassProc
SetWindowSubclass
```

**Comment by Scighost** [comment]
你不说我还不知道 NavigationView 最小化时的 Bug 竟然还没修。

<img width="160" alt="image" src="https://user-images.githubusercontent.com/61003590/212712370-0c5279a5-7977-47ef-b912-c0b8523615f6.png">
<img width="161" alt="image" src="https://user-images.githubusercontent.com/61003590/212712434-30110076-758c-4696-af6f-dc599a1f91d3.png">

Frame 中的内容拓展到了标题栏上

加上最小宽度限制后也没有用，因为我在设计界面的时候以大屏为基准，没有考虑过小屏的体验，布局混乱的情况不可避免。

**Comment by Scighost** [comment]
补充一下：小屏高缩放率在最大化窗口后可能仍会出现宽度不够的情况

**Comment by Yue-cn** [comment]
的确有可能，在768x1366这样的能开125%吧？
不过最小宽度我也本机测试过了，没啥大问题（1080p 125%）

**Comment by Yue-cn** [comment]
试试 [WinUIEX](https://github.com/dotMorten/WinUIEx) 这个库？
