### ISSUE TITLE
3.2八重神子复刻卡池名写错了

### ISSUE THREAD

**Issue by living-alive** [xunkong/xunkong#374]
### 问题描述

写成了八重神子的称号“浮世笑百姿”，实际应为“华紫樱绯”。
http://b23.tv/usQ5AbW

### 复现步骤

点击查看角色活动祈愿

### 截图

![image](https://user-images.githubusercontent.com/63293483/213905082-5da1ba08-083f-4995-8542-82a3b4995918.png)
![Screenshot_20230122_151352](https://user-images.githubusercontent.com/63293483/213905086-b7142690-def6-4eb4-976f-68b0d92744b9.jpg)

### 系统版本

Windows 11 22H2 Dev Channel 25281.1000

### 寻空版本

1.3.0.0

### 日志

[log_20230122_150310.txt](https://github.com/xunkong/xunkong/files/10473899/log_20230122_150310.txt)

### 备注

2.5的是正确的；手动更新本地原神数据无法修复。

**Comment by Scighost** [comment]
已修改
