### ISSUE TITLE
丰富相册功能 & 更新相关 & 游戏启动按钮有点怪

### ISSUE THREAD

**Issue by modenicheng** [xunkong/xunkong#377]
## 建议：相册支持多目录

我的情况如下：
- 原神游戏内截屏是一个文件夹
- 录屏软件一个输出文件夹
- 寻空壁纸一个文件夹

我在想能不能做一个多目录统合，这样我就可以不用打开很多窗口就可以浏览 游戏内截图/同人图/录屏软件输出 三类输出啦！

然后图片可以按照文件夹归类

> 貌似没啥用？

~原神启动器~
- [x] 图片浏览器

---

## 建议：有更新时自动下载

每次都需要打开全球最大的同性交友社区才能下载，能不能针对侧载版做一个下载渠道直接应用内下载然后自动更新（或者自动打开下载的文件，用户只需要点两下就好）？

> 不好做就算了，手动下载也还行。要是我有刚需的话就自己写脚本吧（但是大概没有人觉得自动下载是刚需？

~或者像 PCL2 （那个 Minecraft 启动器）一样直接集成进去个多线程下载器~

---

## 建议：修改下游戏启动按钮（账号管理功能部分

这个账号管理确实挺好用，但是有的时候不太方便……

我的建议是增加一个设置项，填入默认登录账户，然后在侧边加一个下拉菜单，切换用户启动在这里设置

主要是现在每次启动都需要点两下鼠标，我比较懒（bushi

> 不是刚需，都是细节类的，不改也挺不错的
> ~别改完了更不好用了（bushi~

**Comment by Scighost** [comment]
回复一下更新的建议：
使用商店版可以获得最好的更新体验，只是更新时间滞后几小时到几天。侧载版则有一个备用下载链接，一直保持最新，你可以针对这个链接写个脚本。
https://file.xunkong.cc/download/Xunkong.Desktop.Package_latest_x64.msixbundle
https://file.xunkong.cc/download/Xunkong.Desktop.Package_latest_x64.zip

其他两个建议有待考虑

**Comment by modenicheng** [comment]
ok
