### ISSUE TITLE
在获取我的角色和旅行札记时出现-100

### ISSUE THREAD

**Issue by LYBXshive** [xunkong/xunkong#379]
### 问题描述

如题，重复进行了登陆也没有解决

### 复现步骤

登陆账号后切换到对应选项就出现报错

### 截图

![image](https://user-images.githubusercontent.com/53547530/214383312-35c123a9-a75f-46f0-9ed5-84c3e036f28e.png)

### 系统版本

windows 10 22H2

### 寻空版本

1.3.1.0

### 日志

[log_20230125_023911.txt](https://github.com/xunkong/xunkong/files/10493135/log_20230125_023911.txt)

### 备注

感谢大佬的贡献

**Comment by LYBXshive** [comment]
重装重新登录以后解决了（问题千千万，重装少一半）

**Comment by ldm0715** [comment]
> 以后解决了（问题千千万，重装少一半）

貌似是用cookie登陆有这个问题，网页登陆就没事
