### ISSUE TITLE
右上角选项卡按钮颜色问题

### ISSUE THREAD

**Issue by xkYZI** [xunkong/xunkong#382]
### 问题描述

深色主题右上角的三个【最小化】【最大化】【关闭】选项卡按钮不变色

### 复现步骤

切换到深色主题

### 截图

![image](https://user-images.githubusercontent.com/123715656/215012933-a896bb4a-ee81-4cbc-8822-2aea71568e2e.png)

### 系统版本

Windows 10 21H2

### 寻空版本

1.3.1.0

**Comment by Yue-cn** [comment]
正常来讲,在ActualTheme被更改时需要对操控钮进行一次颜色更新(不是DynamicResourecs)
