### ISSUE TITLE
寻空1.3.1.0版本祈愿记录导出无法使用缓存文件

### ISSUE THREAD

**Issue by Knave-akaya** [xunkong/xunkong#383]
### 问题描述

寻空1.3.1.0版本祈愿记录导出无法使用缓存文件。在“获取记录”按钮中，原有的“从缓存文件获取”不见了。启用代理后抓取游戏中的祈愿记录链接本地无法使用。

### 复现步骤

在“祈愿记录”标签中的“获取记录”按钮中，原有的“从缓存文件获取”功能消失

### 截图

![image](https://user-images.githubusercontent.com/115982010/215821231-da8533bb-9f2d-4e95-b3dc-cc1aaa4e6f2d.png)

### 系统版本

Windows 11 22H2

### 寻空版本

1.3.1.0

**Comment by Scighost** [comment]
你可以试试点击**国服**或**国际服**按键
