### ISSUE TITLE
侧栏图标

### ISSUE THREAD

**Issue by gongfuture** [xunkong/xunkong#386]
### 问题描述

如图，我也不知道这是啥问题，也不知道咋解决，寻空文档查了，issue查了，网上资料也找了，不知道咋解决（可能是我描述的不对？），只隐约觉得和Unicode有关
好像是早期寻空我就有这个问题，最近装了同样winUI的胡桃发现也有这问题，才想起来这个问题

### 复现步骤

这估计是个别现象吧？

### 截图

![image](https://user-images.githubusercontent.com/60888755/216286906-1f07c8a8-ac0c-4c39-be88-2f21e030252f.png)

### 系统版本

Windows 10 22h2 专业版

### 寻空版本

1.3.1.0

**Comment by Lightczx** [comment]
Segoe Fluent Icons

**Comment by gongfuture** [comment]
> Segoe Fluent Icons

谢谢
