### ISSUE TITLE
希望能够移动应用位置，不强制C盘

### ISSUE THREAD

**Issue by BT332** [xunkong/xunkong#387]
### 你的建议

我C盘分的比较小，老放C盘太容易红了
![QQ截图20230202190036](https://user-images.githubusercontent.com/70246659/216307887-796a34fc-330d-4ad1-92a9-0180b2a87026.png)

**Comment by BT332** [comment]
![QQ截图20230202190036](https://user-images.githubusercontent.com/70246659/216320501-503b85cd-78ed-43bc-a122-1a446c424384.png)

**Comment by Scighost** [comment]
很遗憾，因为开发框架限制，无法做到。
UWP 默认可以移动到其他磁盘，而 WinUI3 默认不能，也没有给出允许移动的设置项。
