### ISSUE TITLE
能否关闭启动游戏时的参量仪提醒？

### ISSUE THREAD

**Issue by qiuqiu-2** [xunkong/xunkong#389]
### 你的建议

可以是给个开关选择关闭开启，因为不是所有人都想用参量仪，比如没有什么资源的小号或新号，或者是我这种一点资源都不缺的大号，一点用参量仪的想法都没有，但是每次启动都要看一次弹窗觉得很烦

**Comment by Scighost** [comment]
<img width="473" alt="image" src="https://user-images.githubusercontent.com/61003590/216756402-b7ce9594-c30d-471e-8368-03d74157bc96.png">

**Comment by qiuqiu-2** [comment]
![image](https://user-images.githubusercontent.com/67945933/216766349-f653775e-6e2d-42cb-aa3c-e15afcb50d56.png)
谢谢，但是我在windows商店下载的寻空并没有此选项，系统是win11，版本1.3.1.0

**Comment by Scighost** [comment]
新版本还没过审呢
