### ISSUE TITLE
无法导入胡桃的祈愿记录

### ISSUE THREAD

**Issue by Danmo04** [xunkong/xunkong#390]
### 问题描述

显示导入的数据中存在uid为0的项，但实际上并没有

### 复现步骤

胡桃导出为uigf.json，寻空导入

### 截图

![屏幕截图 2023-02-04 125402](https://user-images.githubusercontent.com/90637804/216749363-dcd8576c-c1ea-4a38-b3df-7d4b8819b4da.png)

### 系统版本

Windows 11 22H2

### 寻空版本

1.3.1.0

**Comment by Scighost** [comment]
<img width="248" alt="image" src="https://user-images.githubusercontent.com/61003590/216749583-11e6e51e-c00b-4383-8bde-67b191a66f74.png">

**Comment by Danmo04** [comment]
![image](https://user-images.githubusercontent.com/90637804/216753794-ec90b19e-8e1d-456e-95be-468fadaf6bd9.png)
