### ISSUE TITLE
B服

### ISSUE THREAD

**Issue by lizhengyi3003** [xunkong/xunkong#394]
### 你的建议

能增加一下B服这个渠道服吗？

**Comment by Scighost** [comment]
需要什么功能支持B服

**Comment by lizhengyi3003** [comment]
你在电脑上能看原神战绩？

飞船

发件人: Scighost
发送时间: 2023年2月6日 13:57
收件人: xunkong/xunkong
抄送: Airship; Author
主题: Re: [xunkong/xunkong] B服 (Issue #394)

需要什么功能支持B服

**Comment by Scighost** [comment]
原神战绩是和米游社绑定的，部分官B服

**Comment by lizhengyi3003** [comment]
我说的是寻空不是自带一个启动游戏功能吗？有时点开它是官服有时是B服。
飞船

发件人: Scighost
发送时间: 2023年2月6日 14:06
收件人: xunkong/xunkong
抄送: Airship; Author
主题: Re: [xunkong/xunkong] B服 (Issue #394)

原神战绩是和米游社绑定的，部分官B服

**Comment by Scighost** [comment]
没用过B服，请问B服的启动程序是哪个

**Comment by lizhengyi3003** [comment]
就这个，如果不是通过这个启动器点，而是通过寻空点有时点出来再点开始游戏后弹出来的就不是登录哔哩哔哩账号而是米忽悠账号。
飞船

发件人: Scighost
发送时间: 2023年2月6日 14:09
收件人: xunkong/xunkong
抄送: Airship; Author
主题: Re: [xunkong/xunkong] B服 (Issue #394)

没用过B服，请问B服的启动程序是哪个

**Comment by Scighost** [comment]
我没看到你说的 **“这个”**

**Comment by lizhengyi3003** [comment]
![原神 2023_2_6 14_11_28](https://user-images.githubusercontent.com/81514724/216958551-15a0c2a3-2949-4d37-bde4-3d8bef8abc33.png)


> 我没看到你说的 **“这个”**

**Comment by Scighost** [comment]
看来B服启动器启动游戏本体的时候带了一个特定的参数，当前版本无法通过修改设置做到这一点。

**Comment by k89452** [comment]
TypelnitializationException-添加Cookie
The type initializer for 'Xunkong.Desktop.Helpers.DatabaseProvider'threw
an exception.
原出错是这样的，上面是翻译过的

**Comment by k89452** [comment]
就是登录不了

**Comment by Fachep** [comment]
B服和官服启动器几乎没区别，
启动什么服是游戏客户端根据客户端目录下的config.ini判断的
我目前是一个客户端手动切换双服玩，这是我的config：
- 官服：
```ini
[General]
channel=1
cps=mihoyo
game_version=3.4.0
plugin_sdk_version=3.5.0
sub_channel=1
```
- B服：
```ini
[General]
channel=14
cps=bilibili
game_version=3.4.0
plugin_sdk_version=3.5.0
sub_channel=0
```
楼主是不是同时装了俩服务器的客户端&启动器

**Comment by Fachep** [comment]
哦我也复现了这个问题，似乎是启动时没有指定开始路径（类似快捷方式这个东西和cmd的当前目录）导致的
![image](https://user-images.githubusercontent.com/31302548/217130866-b75b3708-0a7c-47ac-87ed-2a5673b15c56.png)
客户端无法在当前目录找到config.ini

**Comment by lizhengyi3003** [comment]
> 哦我也复现了这个问题，似乎是启动时没有指定开始路径（类似快捷方式这个东西和cmd的当前目录）导致的 ![图像](https://user-images.githubusercontent.com/31302548/217130866-b75b3708-0a7c-47ac-87ed-2a5673b15c56.png) 客户端无法在当前目录找到config.ini

怎么指定

**Comment by Fachep** [comment]
> 怎么指定

已经提交修改了，等下次更新就行

**Comment by lizhengyi3003** [comment]
好的，谢谢！

飞船

发件人: 羊撅撅
发送时间: 2023年2月7日 12:29
收件人: xunkong/xunkong
抄送: Airship; Comment
主题: Re: [xunkong/xunkong] B服 (Issue #394)

怎么指定
已经提交修改了，等下次更新就行
