### ISSUE TITLE
角色祈愿出错——优菈、甘雨识别为了常驻角色

### ISSUE THREAD

**Issue by living-alive** [xunkong/xunkong#398]
### 问题描述

2.3up的优菈、2.4up的甘雨显示为常驻角色所拥有的灰色。

### 复现步骤

点击查看“祈愿记录”中的“数据统计”和“角色活动祈愿”。

### 截图

- “数据统计”界面：

![image](https://user-images.githubusercontent.com/63293483/216951918-791c4e8b-c487-4fd0-a309-bd355572119b.png)
![image](https://user-images.githubusercontent.com/63293483/216952647-f09fe2e9-2caf-46f2-b34e-9b679c30f579.png)

- “角色活动祈愿”界面：

![image](https://user-images.githubusercontent.com/63293483/216952892-663ececb-d343-4020-a25c-ac8856ae11b4.png)

### 系统版本

Windows 11 22H2 Dev Channel 25290.1000

### 寻空版本

1.3.2.0

### 日志

[log_20230124_183056.txt](https://github.com/xunkong/xunkong/files/10662253/log_20230124_183056.txt)
[log_20230124_183027.txt](https://github.com/xunkong/xunkong/files/10662254/log_20230124_183027.txt)

### 备注

“手动更新本地原神数据”无效。

**Comment by Scighost** [comment]
请提供**系统的时区**和**抽中优菈和甘雨的时间**；
在下图界面双击优菈和甘雨的头像，截图出现的内容。
<img width="156" alt="image" src="https://user-images.githubusercontent.com/61003590/216955973-db3b3b02-51ce-42a9-82d5-0a8e68ab870c.png">

**Comment by living-alive** [comment]
- 时区：

![image](https://user-images.githubusercontent.com/63293483/216968279-08706921-471d-4846-8533-e595e3ed2755.png)

- 抱歉未找到含有“角色一览”的界面，以下截图来自“我的角色”：

![image](https://user-images.githubusercontent.com/63293483/216968559-c1be9985-2161-45ec-b608-e07c9195b23b.png)
![image](https://user-images.githubusercontent.com/63293483/216968626-fa609108-69f8-4256-8caf-085a0be08cfd.png)

**Comment by Scighost** [comment]
问题找到了，神秘之息和陵薮市朝是阿贝多和钟离的卡池

**Comment by living-alive** [comment]
啊这……所以，请问要如何解决呢？

**Comment by living-alive** [comment]
> 问题找到了，神秘之息和陵薮市朝是阿贝多和钟离的卡池

啊，我明白了，这两个卡池恰好是同时up两个角色的前几个卡池，由于数据久远不符合标准（缺少某些列），上面的`gacha_type`我未经审查自行填写成了301……
_幸好这两个池子抽的不多，改起来也方便（）_

问题来自于自身疏忽，很抱歉麻烦到了作者。

**Comment by Scighost** [comment]
> 以下内容仅适用于本次情况，无普遍性

祈愿记录页面右上角点击**管理记录**，再点击右上角的**导入导出**；

<img width="314" alt="image" src="https://user-images.githubusercontent.com/61003590/216978304-f1d2e8de-8e74-45cb-86cf-24cffe73870c.png">

导出记录后打开**原始数据**这一栏，找到优菈和甘雨；

<img width="317" alt="image" src="https://user-images.githubusercontent.com/61003590/216978581-dba5b011-7dd0-425d-bd30-6b1eb6cc567e.png">

把相应记录的 `gacha_type` 修改为 `400`

<img width="104" alt="image" src="https://user-images.githubusercontent.com/61003590/216978785-0b92e685-015c-4582-83fb-c1ead2c51972.png">

**Comment by Scighost** [comment]
忘了一点，修改后导入时需要打开**覆盖已有数据**
