### ISSUE TITLE
祈愿记录，小保底不歪数，为负数

### ISSUE THREAD

**Issue by zb7777** [xunkong/xunkong#400]
### 问题描述

祈愿记录，小保底不歪数，为负数

### 复现步骤

祈愿记录-获取记录

### 截图

![image](https://user-images.githubusercontent.com/106429521/217130857-30919f41-8456-4bf1-91cd-7bc5e51efa88.png)

### 系统版本

windows11 21h2

### 寻空版本

1.3.2.0

### 日志

[log_20230205_223022.txt](https://github.com/xunkong/xunkong/files/10670910/log_20230205_223022.txt)

### 备注

bug有好几个月了

**Comment by Scighost** [comment]
应该是和 #398 一样的错误，你检查一下

**Comment by zb7777** [comment]
uigf_gacha_type，，是否需要一并修改

**Comment by zb7777** [comment]
> 应该是和 #398 一样的错误，你检查一下

uigf_gacha_type，，是否需要一并修改

**Comment by Scighost** [comment]
不需要

**Comment by zb7777** [comment]
> 不需要
[Wishlog_100976915_20230207_102450.xlsx](https://github.com/xunkong/xunkong/files/10671000/Wishlog_100976915_20230207_102450.xlsx)
修改完成导入，还是负数

**Comment by Scighost** [comment]
珊瑚宫心海还没有修改
导入时勾选**覆盖已有数据**没有

**Comment by zb7777** [comment]
覆盖了，心海改完导入，还是负数

**Comment by zb7777** [comment]
坏了，我把原纪录删除，再导入心海改完的记录，不为负数，但心海后的数据不见了

**Comment by zb7777** [comment]
![image](https://user-images.githubusercontent.com/106429521/217134787-d3390791-9103-4546-9153-2826eb8792e0.png)

**Comment by zb7777** [comment]
已解决
