### ISSUE TITLE
【祈愿记录】获取记录后，uid选项卡未切换到相应的账号

### ISSUE THREAD

**Issue by Fachep** [xunkong/xunkong#404]
RT，多uid情况下，选项卡为uid1时，通过“获取记录”-“官服”更新uid2的祈愿记录，更新完成后uid选项卡保持在uid1
![image](https://user-images.githubusercontent.com/31302548/217252338-bdc614ff-7694-4c23-9d9e-d09af2264d1a.png)
![image](https://user-images.githubusercontent.com/31302548/217252550-6f8d9be2-aaab-4951-b60a-1b01cc4abc9a.png)

**Comment by Scighost** [comment]
确实
