### ISSUE TITLE
1.3.2.0的原石和莫拉显示有误

### ISSUE THREAD

**Issue by ShallowLone** [xunkong/xunkong#408]
### 问题描述

好奇怪捏，单抽出护膜了（大保底，69抽），原石只剩下80
寻空界面显示397？？
莫拉数也不对

### 复现步骤

看图

### 截图

<img width="1106" alt="0377854be00102dbddbf8c85512b9ff" src="https://user-images.githubusercontent.com/86985230/217826941-0a1c6d07-b3b1-4e0f-879c-f280e0c721b8.png">
<img width="963" alt="a115eafb163a890b2f9eb2588352bff" src="https://user-images.githubusercontent.com/86985230/217826953-e3752a0a-99e3-4a10-ad18-7a1ee25626ee.png">

### 系统版本

Win10 21H2

### 寻空版本

1.3.2.0

**Comment by Scighost** [comment]
这个是当天获取到的原石和摩拉
