### ISSUE TITLE
你的标题

### ISSUE THREAD

**Issue by silvikid** [xunkong/xunkong#417]
### 问题描述

添加磁贴后过一段时间会弹出通知,刷新磁贴是遇到错误
![image](https://user-images.githubusercontent.com/79353674/219823897-106847f6-d620-4cb3-be3b-15d5d37f4b9d.png)

### 复现步骤

添加磁贴

### 截图

![image](https://user-images.githubusercontent.com/79353674/219823907-3220c3f3-7969-43ad-bed1-145fc67bd1f8.png)

### 系统版本

Windows 10 21H2

### 寻空版本

1.3.2.0

### 日志

[log_20230217_193812.txt](https://github.com/xunkong/xunkong/files/10772736/log_20230217_193812.txt)
[log_20230218_085815.txt](https://github.com/xunkong/xunkong/files/10772737/log_20230218_085815.txt)

**Comment by Scighost** [comment]
账号被风控，需要打开主程序或米游社验证一下。
