### ISSUE TITLE
心海与温迪被显示为常驻角色

### ISSUE THREAD

**Issue by Zenitica** [xunkong/xunkong#421]
### 问题描述

2.5下半的心海与2.6上半的温迪显示为常驻角色，并且算入了“小保底歪”的计数中。

### 复现步骤

祈愿记录->记录备份->从云端恢复

### 截图

![1](https://user-images.githubusercontent.com/45645664/221340728-570ac2be-128a-4b88-ad8e-f7f32ca8c214.PNG)

### 系统版本

win10专业版，22H2

### 寻空版本

1.3.2.0

**Comment by Scighost** [comment]
参考 #398

**Comment by Zenitica** [comment]
> 参考 #398

问题已解决，感谢
