### ISSUE TITLE
我的角色部分建议保留之前版本的那个精美的画面

### ISSUE THREAD

**Issue by Lin928rain** [xunkong/xunkong#428]
### 希望我的角色建面能保留老版本那个精美的版本

我个人还是比较喜欢老的那个版本，希望能给个切换老版本的选项

**Comment by King-Nameless** [comment]
建议+1，旧版本明显比新版本酷炫多了，而且新版本筛选功能都没了，完全可以当成旧版本的表格模式

**Comment by pbxs666** [comment]
+1，很喜欢之前的**我的角色**界面，新版虽然简洁，信息一目了然，但是总感觉不太习惯，新版界面就可以按楼上的说法，做成旧版页面的一个表格模式。

**Comment by ShingekinoTerebikun** [comment]
臣附议

**Comment by Scighost** [comment]
下个版本会通过设置选项切换新老版本

**Comment by ShingekinoTerebikun** [comment]
> 下个版本会通过设置选项切换新老版本

好诶
