### ISSUE TITLE
主页实时便签显示未登录

### ISSUE THREAD

**Issue by 13947312448** [xunkong/xunkong#437]
### 问题描述

主页实时便签显示未登录

### 复现步骤

打开软件主页

### 截图

![image](https://user-images.githubusercontent.com/52241086/223775249-17e26049-6e0a-48dc-9eae-881a31ad1890.png)

### 系统版本

Windows 11 21H2

### 寻空版本

1.3.3.0

**Comment by u81668899** [comment]
同样遇到，就算再次删除登录也会提示未登录，用手机在便签里进行验证后才能重新获取

**Comment by 13947312448** [comment]
> 同样遇到，就算再次删除登录也会提示未登录，用手机在便签里进行验证后才能重新获取
删了重新登录确实解决问题了
