### ISSUE TITLE
公告里的活动时间有误

### ISSUE THREAD

**Issue by balh55y** [xunkong/xunkong#446]
### 问题描述

坐标2023年3月18日19:56:21
游戏公告内容
![image](https://user-images.githubusercontent.com/85926883/226104532-b90e18ef-5ede-460a-b629-667fc30cf6da.png)
实际开始时间应为
2023/03/21 18:00:00

### 复现步骤

操作系统win11 22H2 22621.1413
从商店下载的寻空

### 系统版本

win11 22H2 22621.1413

### 寻空版本

1.3.30

### 日志

[log_20230314_193815.txt](https://github.com/xunkong/xunkong/files/11008432/log_20230314_193815.txt)

**Comment by Scighost** [comment]
第一个时间是公告发布的时间，不是活动开始的时间。
