### ISSUE TITLE
【已解决】祈愿记录将限定角色“申鹤”判定为常驻角色的问题

### ISSUE THREAD

**Issue by CNliaoM** [xunkong/xunkong#450]
### 问题描述

导出抽卡记录后，寻空内判定申鹤为常驻角色，导致申鹤计入常驻相关数据，剩余抽数计算为大保底。影响使用。

### 复现步骤

2023年3月21日晚22:00:55进行的抽卡抽出当期限定UP角色申鹤。2023年3月22日上午11点左右导出抽卡记录，查看后直接显示申鹤为常驻角色。

### 截图

![QQ截图20230322130149](https://user-images.githubusercontent.com/128569968/226806747-2903490f-58f2-4e36-8f1a-93cb649cdd02.jpg)

### 系统版本

Windows10 22H2

### 寻空版本

1.3.3.0

### 日志

[log_20230322_114833.txt](https://github.com/xunkong/xunkong/files/11036484/log_20230322_114833.txt)

### 备注

望尽快修复。

**Comment by CNliaoM** [comment]
问题已解决。系寻空的时间未同步电脑时间导致卡池信息未能及时更新，仍然停留在胡桃夜兰池所致。重启寻空即可解决。

**Comment by Scighost** [comment]
不是时间问题，如果再次碰到这种问题，你需要点击这个：
<img width="382" alt="image" src="https://user-images.githubusercontent.com/61003590/229010846-f575ff84-b957-4c2b-aaff-2570674d44dc.png">
