### ISSUE TITLE
使用祈愿数据导入功能，将限定角色“甘雨”“珊瑚宫心海”判定为常驻角色的问题（重启软件无效）

### ISSUE THREAD

**Issue by Syuedem** [xunkong/xunkong#455]
### 问题描述

导入Json或者Excel格式的数据后，将甘雨和心海判断为常驻角色，但即使按这个算法小保底不歪数量也应该是7个才对，但软件显示6个，另外将数据导入胡桃app也同样出现此问题，但导入yunzai机器人和诺艾尔酱V5数据正常。重启软件无效。

### 复现步骤

祈愿记录-管理记录-导入导出-导入UIGF Excel v2.2或UIGF Json v2.2-我的角色(因为没办法点保存)-祈愿记录

### 截图

![QQ截图20230330023455](https://user-images.githubusercontent.com/66299764/228635228-da426a66-7d41-476f-b0e6-6169d29cabe3.png)

### 系统版本

Windows 10 21H2

### 寻空版本

1.3.3.0

### 备注

抽卡记录是通过非小酋导出Excel，通过[https://lijialong1313.github.io/UIGFConvert/](url) 转换得来。

**Comment by Scighost** [comment]
在你截图页面的下方找到甘雨和心海的头像，然后双击她们，把这两条记录的详细内容截个图。

**Comment by Syuedem** [comment]
> 在你截图页面的下方找到甘雨和心海的头像，然后双击她们，把这两条记录的详细内容截个图。
![ganyu](https://user-images.githubusercontent.com/66299764/228760710-640ad1b1-f113-4a3a-9655-4887c5c34a82.png)
![kokomi](https://user-images.githubusercontent.com/66299764/228760755-82b914db-1187-4f2c-8acc-73c44888c51a.png)
发现复现方式有误，改正一下
祈愿记录-获取记录-官服（获取6个月内的记录，统计判段正常）-祈愿记录-管理记录-导入导出-填写UID及lang--导入UIGF Excel v2.2或UIGF Json v2.2-我的角色-祈愿记录（出现将心海&甘雨识别为常驻的情况）
若不通过寻空先获取一遍记录直接导入，会将神里绫华也识别为常驻角色
![1](https://user-images.githubusercontent.com/66299764/228770428-d67df5fb-1042-4bfb-93ec-649555c5d4f8.png)

**Comment by Scighost** [comment]
导入的数据出错了，陵薮市朝对应钟离，浮生孰来对应甘雨，解决办法参考 #398

**Comment by Syuedem** [comment]
> 导入的数据出错了，陵薮市朝对应钟离，浮生孰来对应甘雨，解决办法参考 #398

啊这- -实在是抱歉因为自己数据错误的问题麻烦到作者了
