### ISSUE TITLE
寻空成就管理导入bug

### ISSUE THREAD

**Issue by 157152816** [xunkong/xunkong#465]
### 问题描述

在椰羊网页端口进行成就导入寻空工具箱之后，会发现在寻空成就管理上会多出一个成就“非必要需求”，但是实际上玩家并没有完成（仅限本人账号如此，不知道其他账号情况）

### 复现步骤

1、打开椰羊网页端
2、进行成就导出至寻空
3、打开寻空成就管理进行查看

### 截图

<img width="873" alt="屏幕截图 2023-04-06 144600" src="https://user-images.githubusercontent.com/130037682/230305349-8bbf00e9-4db6-429a-9eb5-d230fdad40eb.png">
<img width="1280" alt="屏幕截图 2023-04-06 144711" src="https://user-images.githubusercontent.com/130037682/230305368-50f6d2f2-de51-4ee1-8508-a0bc99f00455.png">

### 系统版本

Windows 11 22h2

### 寻空版本

1.3.5.0

**Comment by Scighost** [comment]
如图二，因为你在椰羊中选择完成了**非必要需求**这个成就，寻空只是接收了椰羊传来的数据。

**Comment by 157152816** [comment]
并没有选择非必要需求成就哦，图片二上截图并没有选择


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月13日(周四) 上午10:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xunkong/xunkong] 寻空成就管理导入bug (Issue #465)




 
如图二，因为你在椰羊中选择完成了非必要需求这个成就，寻空只是接收了椰羊传来的数据。
 
&mdash;

**Comment by Scighost** [comment]
我看错了，但是这个成就右边有一个进度 **1/1**，这代表着已完成。

**Comment by 157152816** [comment]
另外还有一个问题，就是最近寻空一直需要米游社认证，但是认证之后主页实时便签也不会刷新。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月13日(周四) 上午10:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xunkong/xunkong] 寻空成就管理导入bug (Issue #465)




 
如图二，因为你在椰羊中选择完成了非必要需求这个成就，寻空只是接收了椰羊传来的数据。
 
&mdash;

**Comment by 157152816** [comment]
哦哦，我又看了，已修改呢，谢谢耐心解答！


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月13日(周四) 晚上9:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xunkong/xunkong] 寻空成就管理导入bug (Issue #465)




 
我看错了，但是这个成就右边有一个进度 1/1，这代表着已完成。
 
&mdash;
