### ISSUE TITLE
更新之后首页的公告没有了

### ISSUE THREAD

**Issue by Grizzly-hash** [xunkong/xunkong#472]
### 你的建议

日志里没有呀。。
要是就是这样的，能不能也加一个开关，我就是冲这个功能用的555

**Comment by Scighost** [comment]
主页只会显示**三天内**将要结束的活动的活动，所有的公告内容需要到**公告页面**查看。
把所有的公告放在主页里好吗，这不好，太占空间了。

**Comment by Grizzly-hash** [comment]
🤔好吧好吧，那应该是我刚好卡在那个时间段开始用的了，临期会显示也行，我还以为去掉了，谢谢
