### ISSUE TITLE
寻空账号重复米游社验证无效

### ISSUE THREAD

**Issue by 157152816** [xunkong/xunkong#476]
### 问题描述

经常出现要求米游社登录，但是登陆之后，实时便签依旧无法使用！！！但是除了便签功能以外，其他可以正常使用。

### 复现步骤

1、点击寻空首页，点击便签刷新，要求验证
2、进入网页登录。登陆完成后，点击网页旁的提示勾选
3、返回寻空主页，刷新便签无效，还是要求登录

### 截图

<img width="949" alt="Snipaste_2023-04-15_12-10-25" src="https://user-images.githubusercontent.com/130037682/232182241-d6e78127-6e73-49a9-8339-0d30d853a95e.png">

### 系统版本

Windows 10 22H2

### 寻空版本

1.3.7.0

### 备注

该情况时常出现

**Comment by Scighost** [comment]
每隔几天到十几天出现验证账号属于正常情况，你点击**验证账号**就行了。

**Comment by 157152816** [comment]
好的，我试一试吧


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月17日(周一) 晚上11:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xunkong/xunkong] 寻空账号重复米游社验证无效 (Issue #476)




 
每隔几天到十几天出现验证账号属于正常情况，你点击验证账号就行了。
 
&mdash;
