### ISSUE TITLE
出现问题 SQLite Error 1

### ISSUE THREAD

**Issue by szyspirit** [xunkong/xunkong#480]
### 问题描述

 SQLite Error 1:cannot start a transcation within transacation

### 复现步骤

添加账号或者更新祈愿记录时会出现这个提示

### 系统版本

window 11 22H2

### 寻空版本

1.3.7.0

**Comment by Scighost** [comment]
`cannot start a transcation within transacation` 这种问题应该是因为线程冲突，有点难定位在哪出错的。第一次使用可以直接删除 `Database` 文件夹，如果后续仍出现数据库的相关的错误，需要在 `Backup\Database` 文件夹中找最新的数据库文件替换原文件。

**Comment by szyspirit** [comment]
嗯嗯就是这么做的然后修复了
