### ISSUE TITLE
寻空添加账号失败，提示"SQLite Error 1"错误

### ISSUE THREAD

**Issue by jun0x50** [xunkong/xunkong#481]
### 问题描述

点击添加账号网页登录完成后，点击“✓”后提示错误，卸载后再次安装问题依旧。

### 复现步骤

第一次下载安装网页登录成功添加账号，在多次点击左侧首页等多个选项后，界面卡死，结束任务进程后，再次打开还需要添加账号。

### 截图

<img width="1120" alt="1" src="https://user-images.githubusercontent.com/127495661/232386826-0f1b58ea-a3db-421d-9805-71cac5b8b654.png">
<img width="829" alt="2" src="https://user-images.githubusercontent.com/127495661/232386861-0f68e67a-490f-4984-9f81-982424336c70.png">
<img width="829" alt="3" src="https://user-images.githubusercontent.com/127495661/232386876-ce02d406-9f67-4902-823c-cb3d0acd0f55.png">
<img width="829" alt="4" src="https://user-images.githubusercontent.com/127495661/232386921-2bb5ce94-1072-4307-9ad3-db1b25d42951.png">
<img width="829" alt="5" src="https://user-images.githubusercontent.com/127495661/232386938-811a2308-9050-49b3-ad5e-aaf20fff53e0.png">

### 系统版本

版本:Windows 11 专业版 22H2; 操作系统版本:22621.1555; 体验:Windows Feature Experience Pack 1000.22640.1000.0

### 寻空版本

1.3.7.0

### 日志

[log_20230417_131422.txt](https://github.com/xunkong/xunkong/files/11246462/log_20230417_131422.txt)
[log_20230417_121910.txt](https://github.com/xunkong/xunkong/files/11246463/log_20230417_121910.txt)
[log_20230417_111150.txt](https://github.com/xunkong/xunkong/files/11246465/log_20230417_111150.txt)

### 备注

侧载版没试过

**Comment by Czh00311** [comment]
https://github.com/xunkong/xunkong/issues/453
你试试这个，我删掉Database文件夹也好了qwq

**Comment by Scighost** [comment]
`cannot start a transcation within transacation` 这种问题应该是因为线程冲突，有点难定位在哪出错的。第一次使用可以直接删除 `Database` 文件夹，如果后续仍出现数据库的相关的错误，需要在 `Backup\Database` 文件夹中找最新的数据库文件替换原文件。
