### ISSUE TITLE
崩坏星穹铁道纳入寻空

### ISSUE THREAD

**Issue by yan32020** [xunkong/xunkong#488]
### 你的建议

催一下作者大大更新支持崩坏星穹铁道相关功能，ps：抽卡

**Comment by Scighost** [comment]
你可以关注一下这个项目
https://github.com/Scighost/StarRailTool

**Comment by Scighost** [comment]
寻空中不会加入星穹铁道的功能
上面那个项目已停止维护，现在应该去这里 https://github.com/Scighost/Starward
