### ISSUE TITLE
礼貌问下会考虑做星穹铁道的功能么

### ISSUE THREAD

**Issue by wao158** [xunkong/xunkong#489]
### 你的建议

这个软件用着太舒服了

**Comment by xunun** [comment]
同希望

**Comment by imgradeone** [comment]
https://github.com/Scighost/StarRailTool 可以看看

**Comment by HongyuS** [comment]
[Scighost/Starward](https://github.com/Scighost/Starward) 大佬做的星铁启动器，内置抽卡历史功能，简单试了一下，挺好用

**Comment by Scighost** [comment]
就是这个 https://github.com/Scighost/Starward
