### ISSUE TITLE
关于多账号保存切换文件名或扩展名太长的问题

### ISSUE THREAD

**Issue by Leeiiiii** [xunkong/xunkong#490]
### 问题描述

切换账号提示文件名或扩展名过长。过程是这样的，以前没用过寻空，一直用的胡桃工具箱，前几天重装了系统（笔记本自带原版系统，Windows11 家庭版 22H2）,然后就发现了问题，寻空提示文件名过长，胡桃提示未开启长路径（此时都只添加了几个账号做测试），胡桃的情况是一个都打不开，寻空是国服提示文件名长问题，云原神切换正常。然后我就开始折腾长路径的问题，修改了注册表，策略组等方法都试过，甚至怀疑是PowerShell版本问题也替换过，始终都解决不了。最后索性重装了，为了怕是因为其他软件或者运行库版本的问题造成的，重装后都尽量不装新库。重装过后，添加国服和云原神几个账号测试，都一切正常。此时装的是ReviOS（封装的一个Windows11专业版 22H2）。我就开始大量添加账号，因为我是个代肝嘛，手上很多资源号，想着一次输入完以后方便切换。问题就出现了，当我添加了账号到70多个的时候，就出现文件名过长的问题了。我是在添加到账号075的时候无意中发现的，我点切换启动账号就出错误提示了，心里一凉，以为又要重装了（但是我确实不知道问题出在哪啊，还以为是新装的什么软件冲突了），结果我发现前面的账号并没有问题，还是可以正常切换。为了测试，我又下载了胡桃工具箱，也不提示长路径问题，说明应该不是未开启长路径的原因（为了保险，我又策略组注册表都检查开启了一遍）。重启后问题依旧，就是前面的账号可以正常切换，后面的就不行。

### 复现步骤

正常切换的账号国服5个，云原神70个（下面有图）第70个（编号069）就不行了
尝试删除添加账号，排序69以后都不行，68能正常。

### 截图

<img width="764" alt="Xunkong Desktop_OxDDayFuI9" src="https://user-images.githubusercontent.com/38080054/235303039-0a587e9a-6633-49bb-8706-1367527d158f.png">
<img width="764" alt="Xunkong Desktop_lasli3RfgI" src="https://user-images.githubusercontent.com/38080054/235303046-c2a420b1-2432-496a-86bd-5a756dfd09db.png">

### 系统版本

Windows 11 22H2 专业版

### 寻空版本

1.3.7.0

### 日志

[log_20230429_203813.txt](https://github.com/xunkong/xunkong/files/11359193/log_20230429_203813.txt)
[log_20230429_190850.txt](https://github.com/xunkong/xunkong/files/11359195/log_20230429_190850.txt)
[log_20230429_185924.txt](https://github.com/xunkong/xunkong/files/11359196/log_20230429_185924.txt)
[log_20230429_185303.txt](https://github.com/xunkong/xunkong/files/11359197/log_20230429_185303.txt)
[log_20230429_114158.txt](https://github.com/xunkong/xunkong/files/11359198/log_20230429_114158.txt)

**Comment by Leeiiiii** [comment]
https://www.it1352.com/2251331.html
感觉这个有点参考价值。当然我也不太清楚具体账号保存切换的实现方式，感觉有点想不通啊，为什么前面几十个就没问题，到了一定数量就有问题，照理说路径长度应该都是一样的啊。

**Comment by Leeiiiii** [comment]
https://www.it1352.com/2251331.html
感觉这个有点参考价值。当然我也不太清楚具体账号保存切换的实现方式，感觉有点想不通啊，为什么前面几十个就没问题，到了一定数量就有问题，照理说路径长度应该都是一样的啊。

**Comment by Scighost** [comment]
这场面我真没见过.jpg
因为寻空使用了 msix 的安装方式，不能直接读写注册表，所以使用了 PowerShell 绕过这个限制。即便如此，也不适合用来保存大量账号，建议你寻找其他的工具。

**Comment by Leeiiiii** [comment]
工具我自己改写了一个支持云原神的版本，用的文本方式保存数据，应该不会有这个问题。我只是很纳闷，为什么会出现这么神奇的BUG，没想明白原理。估计原神存多了也会出现这个，没测试过（要手动再输这么多次账号受不了）。
