### ISSUE TITLE
对 寻空 关于的建议

### ISSUE THREAD

**Issue by j1-2r** [xunkong/xunkong#491]
### 你的建议

最近《崩坏：星穹铁道》公测了，能不能支持一下《崩坏：星穹铁道》的跃迁（抽卡）系统呢？
《崩坏：星穹铁道》的光锥和角色系统也能支持一下就更好了

**Comment by Scighost** [comment]
抽卡已经有了，角色和光锥不太可能会支持
https://github.com/Scighost/Starward

**Comment by j1-2r** [comment]
为什么，原神就能做到，至少把角色武器技能介绍之类的能支持就好，我觉得可以不用与账号同步角色信息

从 Windows 版邮件发送

发件人: Scighost
发送时间: 2023年5月20日 17:12
收件人: xunkong/xunkong
抄送: jlc; Author
主题: Re: [xunkong/xunkong] 对 寻空 关于的建议 (Issue #491)

抽卡已经有了，角色和光锥不太可能会支持
https://github.com/Scighost/Starward
