### ISSUE TITLE
无法添加账号

### ISSUE THREAD

**Issue by Color-More** [xunkong/xunkong#496]
### 问题描述

无法添加账户，弹窗报错内容如下：

SqliteException -添加 Cookie
SQLite Error 1: 'cannot start a transaction within a transaction'.

### 复现步骤

正常的添加账号步骤，我是参考官网的网页登录流程，点击打钩之后弹窗报错

### 截图

![Snipaste_2023-05-15_18-26-23](https://github.com/xunkong/xunkong/assets/75207643/590b53f3-a2f9-428f-97fa-6e7ed593ab3a)
![2](https://github.com/xunkong/xunkong/assets/75207643/31e01a01-6b01-4cf9-a230-51018e1656dd)

### 系统版本

Windows 10 企业版 LTSC 21H2

### 寻空版本

微软商店最新版

### 日志

[log_20230515_180424.txt](https://github.com/xunkong/xunkong/files/11476768/log_20230515_180424.txt)

**Comment by Scighost** [comment]
#481
