### ISSUE TITLE
寻空添加游戏路径不弹出选择文件夹的界面

### ISSUE THREAD

**Issue by Lemoncc2** [xunkong/xunkong#498]
### 问题描述

寻空添加游戏路径不弹出选择文件夹的界面，点击选择文件就会卡住，点击就会有系统错误音

### 复现步骤

咋办咋办

### 系统版本

Windows 11 22H2

### 寻空版本

最新版

### 日志

[log_20230523_140611.txt](https://github.com/xunkong/xunkong/files/11543947/log_20230523_140611.txt)

**Comment by Scighost** [comment]
参考 #291 的方法，其中键这一栏应填写
国服 `GameExePathCN`
国际服 `GameExePathGlobal`
云原神 `GameExePathCNCloud`
值这一栏填写 exe 文件的完整路径

**Comment by Lemoncc2** [comment]
牛哇牛哇！谢谢大佬！
