### ISSUE TITLE
帧率解锁

### ISSUE THREAD

**Issue by Meterstream** [xunkong/xunkong#499]
### 问题描述

3.7版本的帧数解锁是失效了嘛，更新完就锁六十了

### 复现步骤

寻空设置的144，进游戏但是只有60

### 截图

![image](https://github.com/xunkong/xunkong/assets/129191100/89ad1777-2116-46c6-8f15-cfc83d65c033)
![image](https://github.com/xunkong/xunkong/assets/129191100/5ab0b9e1-27a9-409f-acc3-32f87e7b7cba)

### 系统版本

Windows 10 22H2

### 寻空版本

1.3.8.0

**Comment by Scighost** [comment]
请参考 #509 ，此 issue 将被关闭。
