### ISSUE TITLE
原神解锁高帧率更新3.7以后没了

### ISSUE THREAD

**Issue by forEN13** [xunkong/xunkong#501]
### 问题描述

原神解锁高帧率更新3.7以后没了

### 复现步骤

原神解锁高帧率更新3.7以后没了

### 系统版本

Windows 11 22H2

### 寻空版本

1.3.8.0

### 日志

[log_20230430_223138.txt](https://github.com/xunkong/xunkong/files/11553722/log_20230430_223138.txt)
[log_20230503_000739.txt](https://github.com/xunkong/xunkong/files/11553723/log_20230503_000739.txt)
[log_20230503_115109.txt](https://github.com/xunkong/xunkong/files/11553724/log_20230503_115109.txt)
[log_20230504_184057.txt](https://github.com/xunkong/xunkong/files/11553725/log_20230504_184057.txt)
[log_20230504_234405.txt](https://github.com/xunkong/xunkong/files/11553726/log_20230504_234405.txt)
[log_20230505_084723.txt](https://github.com/xunkong/xunkong/files/11553727/log_20230505_084723.txt)
[log_20230506_235417.txt](https://github.com/xunkong/xunkong/files/11553728/log_20230506_235417.txt)
[log_20230512_004231.txt](https://github.com/xunkong/xunkong/files/11553736/log_20230512_004231.txt)
[log_20230512_084954.txt](https://github.com/xunkong/xunkong/files/11553737/log_20230512_084954.txt)
[log_20230513_001610.txt](https://github.com/xunkong/xunkong/files/11553738/log_20230513_001610.txt)
[log_20230513_084231.txt](https://github.com/xunkong/xunkong/files/11553739/log_20230513_084231.txt)
[log_20230513_193200.txt](https://github.com/xunkong/xunkong/files/11553740/log_20230513_193200.txt)
[log_20230514_223412.txt](https://github.com/xunkong/xunkong/files/11553741/log_20230514_223412.txt)
[log_20230515_124537.txt](https://github.com/xunkong/xunkong/files/11553742/log_20230515_124537.txt)
[log_20230516_080944.txt](https://github.com/xunkong/xunkong/files/11553743/log_20230516_080944.txt)
[log_20230516_084152.txt](https://github.com/xunkong/xunkong/files/11553744/log_20230516_084152.txt)
[log_20230520_223701.txt](https://github.com/xunkong/xunkong/files/11553745/log_20230520_223701.txt)
[log_20230523_082809.txt](https://github.com/xunkong/xunkong/files/11553746/log_20230523_082809.txt)
[log_20230523_191353.txt](https://github.com/xunkong/xunkong/files/11553747/log_20230523_191353.txt)
[log_20230523_235617.txt](https://github.com/xunkong/xunkong/files/11553748/log_20230523_235617.txt)
[log_20230524_185645.txt](https://github.com/xunkong/xunkong/files/11553749/log_20230524_185645.txt)
[log_20220816_182342.txt](https://github.com/xunkong/xunkong/files/11553750/log_20220816_182342.txt)
[log_20220816_182727.txt](https://github.com/xunkong/xunkong/files/11553751/log_20220816_182727.txt)
[log_20220822_001706.txt](https://github.com/xunkong/xunkong/files/11553752/log_20220822_001706.txt)
[log_20220823_001606.txt](https://github.com/xunkong/xunkong/files/11553754/log_20220823_001606.txt)
[log_20220826_000240.txt](https://github.com/xunkong/xunkong/files/11553755/log_20220826_000240.txt)
[log_20220827_000248.txt](https://github.com/xunkong/xunkong/files/11553756/log_20220827_000248.txt)
[log_20220828_130121.txt](https://github.com/xunkong/xunkong/files/11553757/log_20220828_130121.txt)
[log_20220831_001711.txt](https://github.com/xunkong/xunkong/files/11553758/log_20220831_001711.txt)
[log_20220831_125740.txt](https://github.com/xunkong/xunkong/files/11553760/log_20220831_125740.txt)
[log_20220831_150145.txt](https://github.com/xunkong/xunkong/files/11553761/log_20220831_150145.txt)
[log_20220831_191418.txt](https://github.com/xunkong/xunkong/files/11553762/log_20220831_191418.txt)
[log_20220901_000700.txt](https://github.com/xunkong/xunkong/files/11553763/log_20220901_000700.txt)
[log_20220908_162353.txt](https://github.com/xunkong/xunkong/files/11553764/log_20220908_162353.txt)
[log_20220908_182030.txt](https://github.com/xunkong/xunkong/files/11553765/log_20220908_182030.txt)
[log_20220911_201535.txt](https://github.com/xunkong/xunkong/files/11553766/log_20220911_201535.txt)
[log_20220914_153931.txt](https://github.com/xunkong/xunkong/files/11553768/log_20220914_153931.txt)
[log_20220927_182327.txt](https://github.com/xunkong/xunkong/files/11553770/log_20220927_182327.txt)
[log_20221007_173347.txt](https://github.com/xunkong/xunkong/files/11553771/log_20221007_173347.txt)
[log_20221015_120232.txt](https://github.com/xunkong/xunkong/files/11553772/log_20221015_120232.txt)
[log_20221021_152214.txt](https://github.com/xunkong/xunkong/files/11553773/log_20221021_152214.txt)
[log_20221023_123410.txt](https://github.com/xunkong/xunkong/files/11553774/log_20221023_123410.txt)
[log_20221023_234730.txt](https://github.com/xunkong/xunkong/files/11553775/log_20221023_234730.txt)
[log_20221111_205247.txt](https://github.com/xunkong/xunkong/files/11553776/log_20221111_205247.txt)
[log_20221114_115613.txt](https://github.com/xunkong/xunkong/files/11553777/log_20221114_115613.txt)
[log_20221124_190841.txt](https://github.com/xunkong/xunkong/files/11553778/log_20221124_190841.txt)
[log_20221202_114503.txt](https://github.com/xunkong/xunkong/files/11553779/log_20221202_114503.txt)
[log_20221204_123511.txt](https://github.com/xunkong/xunkong/files/11553780/log_20221204_123511.txt)
[log_20221205_121715.txt](https://github.com/xunkong/xunkong/files/11553781/log_20221205_121715.txt)
[log_20221208_193320.txt](https://github.com/xunkong/xunkong/files/11553784/log_20221208_193320.txt)
[log_20221209_115254.txt](https://github.com/xunkong/xunkong/files/11553785/log_20221209_115254.txt)
[log_20230102_182934.txt](https://github.com/xunkong/xunkong/files/11553787/log_20230102_182934.txt)
[log_20230110_191909.txt](https://github.com/xunkong/xunkong/files/11553788/log_20230110_191909.txt)
[log_20230110_193307.txt](https://github.com/xunkong/xunkong/files/11553790/log_20230110_193307.txt)
[log_20230115_204232.txt](https://github.com/xunkong/xunkong/files/11553792/log_20230115_204232.txt)
[log_20230117_135251.txt](https://github.com/xunkong/xunkong/files/11553793/log_20230117_135251.txt)
[log_20230117_135340.txt](https://github.com/xunkong/xunkong/files/11553794/log_20230117_135340.txt)
[log_20230119_003049.txt](https://github.com/xunkong/xunkong/files/11553795/log_20230119_003049.txt)
[log_20230119_203335.txt](https://github.com/xunkong/xunkong/files/11553796/log_20230119_203335.txt)
[log_20230209_004813.txt](https://github.com/xunkong/xunkong/files/11553797/log_20230209_004813.txt)
[log_20230210_083540.txt](https://github.com/xunkong/xunkong/files/11553798/log_20230210_083540.txt)
[log_20230212_110803.txt](https://github.com/xunkong/xunkong/files/11553799/log_20230212_110803.txt)
[log_20230212_123158.txt](https://github.com/xunkong/xunkong/files/11553801/log_20230212_123158.txt)
[log_20230308_002632.txt](https://github.com/xunkong/xunkong/files/11553802/log_20230308_002632.txt)
[log_20230328_233913.txt](https://github.com/xunkong/xunkong/files/11553803/log_20230328_233913.txt)
[log_20230331_005126.txt](https://github.com/xunkong/xunkong/files/11553804/log_20230331_005126.txt)
[log_20230401_122501.txt](https://github.com/xunkong/xunkong/files/11553805/log_20230401_122501.txt)
[log_20230406_115309.txt](https://github.com/xunkong/xunkong/files/11553806/log_20230406_115309.txt)
[log_20230407_093330.txt](https://github.com/xunkong/xunkong/files/11553807/log_20230407_093330.txt)
[log_20230429_145925.txt](https://github.com/xunkong/xunkong/files/11553808/log_20230429_145925.txt)

### 备注

[log_20230507_231800.txt](https://github.com/xunkong/xunkong/files/11553730/log_20230507_231800.txt)
[log_20230508_224201.txt](https://github.com/xunkong/xunkong/files/11553731/log_20230508_224201.txt)
[log_20230509_224608.txt](https://github.com/xunkong/xunkong/files/11553732/log_20230509_224608.txt)
[log_20230510_084815.txt](https://github.com/xunkong/xunkong/files/11553733/log_20230510_084815.txt)
[log_20230511_002940.txt](https://github.com/xunkong/xunkong/files/11553734/log_20230511_002940.txt)
[log_20230511_235702.txt](https://github.com/xunkong/xunkong/files/11553735/log_20230511_235702.txt)

**Comment by Scighost** [comment]
请参考 #509 ，此 issue 将被关闭。
