### ISSUE TITLE
祈愿记录页面Exception LiteDB ENSURE: page type must be data page

### ISSUE THREAD

**Issue by HyBoxwood** [xunkong/xunkong#534]
### 问题描述

能更新祈愿记录，管理记录里面有记录，能恢复云端记录，就是一页也显示不出来。

### 复现步骤

祈愿记录-空白页面-刷新页面-Exception LiteDB ENSURE: page type must be data page

### 截图

![QQ截图20230723012330](https://github.com/xunkong/xunkong/assets/87700780/b1955920-4a92-4419-90e9-4392c3e1beb0)
![QQ截图20230723012339](https://github.com/xunkong/xunkong/assets/87700780/26fec817-4785-48e6-9b66-cfb47635d1b6)

### 系统版本

Windows 11 22H2

### 寻空版本

1.3.9.0

### 日志

[log_20230523_080452.zip](https://github.com/xunkong/xunkong/files/12136917/log_20230523_080452.zip)

**Comment by HyBoxwood** [comment]
啊好像不止这一页呢，“我什么都做不到”?
![QQ截图20230723013200](https://github.com/xunkong/xunkong/assets/87700780/43bffafe-ec87-4f42-a6cf-44a2339a64be)

**Comment by Scighost** [comment]
把 `GenshinData.db` 删掉就行

**Comment by HyBoxwood** [comment]
那 行
