### ISSUE TITLE
林尼和琳妮特在“祈愿记录”和“角色图鉴”中无法正常显示

### ISSUE THREAD

**Issue by living-alive** [xunkong/xunkong#542]
### 问题描述

如题，同时在旧版“我的角色”同样不显示，在新版该界面正常。
点击“设置”中的“预缓存所有图片”和“手动更新本地原神数据”，完成后上述问题仍存在。

### 复现步骤

分别点击“祈愿记录”、“角色图鉴”和“我的角色”界面。

### 截图

- 无法正常显示的“祈愿记录”界面：
![image](https://github.com/xunkong/xunkong/assets/63293483/d65b6992-2a9c-4c10-9792-2881d79f0101)

- 可以正常显示的“我的角色”界面：
![image](https://github.com/xunkong/xunkong/assets/63293483/0030ce69-9454-4914-b70b-c20c1d3dac63)
![image](https://github.com/xunkong/xunkong/assets/63293483/0379c9d1-a528-412c-9690-c997a7eda1af)

### 系统版本

Windows 11 23H2 Canary Channel 25931.1000

### 寻空版本

1.4.0.0

### 日志

[log_20230819_130039.txt](https://github.com/xunkong/xunkong/files/12385349/log_20230819_130039.txt)
[log_20230819_112552.txt](https://github.com/xunkong/xunkong/files/12385350/log_20230819_112552.txt)
[log_20230819_155106.txt](https://github.com/xunkong/xunkong/files/12385351/log_20230819_155106.txt)

**Comment by yuaniyuan** [comment]
我猜因为没更新4.0的数据吧，4.0的角色和武器我都不显示的

**Comment by zhfun** [comment]
> 

正解，作者的精力好像放在另外一个启动器上了

**Comment by living-alive** [comment]
![image](https://github.com/xunkong/xunkong/assets/63293483/0fc11328-3cbf-4f74-a4a0-16bc0227a7ff)

**Comment by proanddec** [comment]
同 同样的问题还有武器界面没有大魔术弓和新月卡武器 希望修复
