### ISSUE TITLE
你的标题

### ISSUE THREAD

**Issue by MO77799** [xunkong/xunkong#543]
### 问题描述

成就系统用YaeAchievement没发更新 安装了.net 可以用YaeAchievement导到椰羊和UIAF 但是不能直接选择5寻空直接导入

### 复现步骤

选择成就 获取 接受风险 寻空5 退出

### 系统版本

Windows 11 22H2

### 寻空版本

1.4.0.0

**Comment by Lightczx** [comment]
难道是我改炸了？
@Scighost 你有空能看看这个PR么，我动过你的部分
https://github.com/HolographicHat/YaeAchievement/pull/62

**Comment by MO77799** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Scighost** [comment]
> 难道是我改炸了？
> @Scighost 你有空能看看这个PR么，我动过你的部分
> https://github.com/HolographicHat/YaeAchievement/pull/62

你这都两个月前的pr了，我前几天才用过一次，没有任何问题。

**Comment by Scighost** [comment]
因为创建者的邮箱存在自动回复，现锁定此 issue。
