### ISSUE TITLE
【求教】寻空主数据更新问题

### ISSUE THREAD

**Issue by soulgazor** [xunkong/xunkong#550]
### 问题描述

Scighost大大，一直都用的您开发的作品，从早期的刻晴牛杂店，到现在的寻空，对您的能力与分享精神都深感佩服。
我最开始用的是刻记牛杂店，虽然当时很快出了其他竞品，但最喜欢的依然是刻记牛杂店，在它停更后还舍不得卸载。
然后我自己摸索着找到了它的配置文件，靠手动添加新的祈愿信息，角色图等来维持使用。
这样坚持了很久才尝试寻空，新作功能更强大，除了图片加载会比刻记慢，其他都很好用。然而现如今寻空也转为**消极维护状态**了。

在最近一次更新中，修复了之前的部分问题，但还是缺乏了新角色和新武器的信息。
所以我想自己试着手动更新本地的数据，但有点无从下手。
目前只知道，XunkongData.db 是存放用户数据的，这个是SQLite数据库，我用datagrip或dbeaver都可以解析其中的数据并修改。
而我想更新的数据，是在GenshinData.db中，这个文件我不懂该怎么解析维护，可以请问一下要使用什么格式或什么软件才能修改它么？

### 复现步骤

我用datagrip或dbeaver以SQLite格式解析GenshinData.db，连接失败，提示“[SQLITE_NOTADB] File opened that is not a database file (file is not a database)”

### 系统版本

win10

### 寻空版本

1.4.1

**Comment by living-alive** [comment]
![image](https://github.com/xunkong/xunkong/assets/63293483/b1fc00fe-c129-44cd-bc5b-f1feb95f41ae)
使用十六进制文件编辑器打开文件，文件头显示“this is a litedb file”

（别的不懂💦）

**Comment by yuaniyuan** [comment]
> > 莱特数据库工作室
> 
> > ![图像](https://user-images.githubusercontent.com/63293483/268314451-b1fc00fe-c129-44cd-bc5b-f1feb95f41ae.png)使用十六进制文件编辑器打开文件，文件头显示“这是一个litedb文件”。
> > ![图像](https://user-images.githubusercontent.com/63293483/268314891-be5bb993-83be-4a46-becd-e76f2fe54c70.png)使用litedb studio打开文件，如图所示。
> > （其他不懂💦）
> 
> 十分感谢

老哥能否分享一下更新过得文件呀，这个看不懂啦，现在没有最新的数据
