### ISSUE TITLE
【反馈】 小地图无法显示在游戏主体上

### ISSUE THREAD

**Issue by YangAoLib** [xunkong/xunkong#67]
### 问题描述

新增加的小地图(打开小地图时, 没有右上角的齿轮)功能无法正确显示在游戏主体上, (无法透明, 悬浮显示)

### 复现步骤

打开小地图, 打开游戏(无边框)

### 预期行为

小地图透明显示在游戏中

### 截图

提交截图有助于分析问题

### 系统及寻空版本

- 系统：win10
- 寻空：0.1.5.0

### 日志

日志位于 `我的文档\Xunkong\Log`，上传前注意**删除个人信息**

**Comment by Scighost** [comment]
请补充以下信息：
显示器分辨率
系统缩放大小

**Comment by YangAoLib** [comment]
显示器分辨率: 1920 x 1080
系统缩放大小: 125%

**Comment by Scighost** [comment]
Alt+S 打开设置界面，按键找不到我真不知道啥情况

**Comment by YangAoLib** [comment]
点击覆盖原神窗口后还是无法显示悬浮窗
![image](https://user-images.githubusercontent.com/59254083/161308955-a8fa4a03-ae01-437e-9e06-66d13b506f6f.png)
在任务栏中呈现这样的状态

**Comment by thomas-chain** [comment]
类似问题反馈，首次使用小地图时可以正常显示，第二次使用开始无法悬浮显示在游戏界面之上，点击覆盖原神窗口后未显示。
屏幕3840*2160，缩放200%

**Comment by Scighost** [comment]
点击**覆盖原神窗口**时原神的窗口不能为最小化状态。

**Comment by YangAoLib** [comment]
开启小地图并且原神全屏显示, 使用快捷键时 会从原神主体切换出去

**Comment by Scighost** [comment]
暂时无法做到像Xbox小组件那样覆盖全屏运行的游戏

**Comment by YangAoLib** [comment]
使用**无边框**运行时, 也是同样的现象
