### ISSUE TITLE
【反馈】 祈愿记录统计出错

### ISSUE THREAD

**Issue by DavideSOGG** [xunkong/xunkong#79]
完整的反馈信息可以帮你快速解决问题

### 问题描述

祈愿记录的数据统计部分存在错误 小保底不歪显示为负数。对照导出的祈愿记录可发现问题（祈愿记录管理导出祈愿正常）

统计错误导致之后的角色活动祈愿部分卡池记录出错。

### 复现步骤

先进行日志更新后（抽卡记录需超过6个月）再导入原本保存的抽卡记录excel 总条数正确 但软件里记录显示错乱（增量与全量都错乱）大概----具体也记不清了。总之个人是登录cookies之后就用日志全量更新了，结果发现祈愿记录出错后导入了之前刻晴牛杂的祈愿记录（记录是从游戏第一次抽卡的全部记录）后来发现问题并没有得到修正 我想大概是和超过了6个月的几天有关，虽然通过导入完全的记录得到了全部抽卡结果，但软件在进行数据计算时仍未将超过6个月的部分加入计算。所以即使记录完全也会出现对应卡池统计的错误之类的，大概这样吧。

### 预期行为

记录正常 更新正常 统计正常 增量/全量更新不错乱

### 截图
![bandicam 2022-04-15 19-30-43-652](https://user-images.githubusercontent.com/28831997/163603503-88cb4b23-cbf5-439e-a8d2-6bbf6666c4f7.jpg)
![bandicam 2022-04-15 19-31-25-808](https://user-images.githubusercontent.com/28831997/163603530-8ede5262-40f9-459c-9384-c20d2e710808.jpg)

### 系统及寻空版本

- 系统：Windows 10 专业工作站版 版本号 20H2 内部版本 19042.928
- 寻空：0.1.7.1预览版

### 日志

【已被删除】

### 补充信息

导出的祈愿记录

【已被删除】

**Comment by Scighost** [comment]
问题的原因是抽卡记录时间出错了。
以申鹤为例，你的记录中的时间是 `2022-01-05 05:19:02`，官服对应时区 `UTC+8`，此纪录导入后在数据库中的数据即为 `2022-01-05 05:19:02+08:00`，这个时间不在申鹤池子的范围内，所以会出现上图中的统计错误。

我不能保证软件一定没问题，建议你先做如下测试：
- 备份并删除本地数据库的记录
- 重新从游戏中获取近6个月的记录
- 比较申鹤池子中抽卡记录的时间

如果上述测试中的抽卡记录没有问题，那么是你之前导入的记录中的时间出错了，应该再加8小时，但是我不能确定是某个范围记录的时间有问题，还是全部都有，这个只能靠你自己判断。

**Comment by DavideSOGG** [comment]
> 问题的原因是抽卡记录时间出错了。 以申鹤为例，你的记录中的时间是 ，官服对应时区 ，此记录导入后在数据库中的数据即为 ，这个时间不在申鹤池子的范围内，所以会出现上图中的统计错误。`2022-01-05 05:19:02``UTC+8``2022-01-05 05:19:02+08:00`
> 
> 我不能保证软件一定没问题，建议你先做如下测试：
> 
> * 备份并删除本地数据库的记录
> * 重新从游戏中获取近6个月的记录
> * 比较申鹤池子中抽卡记录的时间
> 
> 如果上述测试中的抽卡记录没有问题，那么是你之前导入的记录中的时间出错了，应该再加8小时，但是我不能确定是某个范围记录的时间有问题，还是全部都有，这个只能靠你自己判断。

确实是海外国服玩家。对照了两份Excel，确实部分时间错乱。祈愿时差直接隔了6小时，新导出的表格是国内标准时而非电脑设定的本地时间。【两时区正好相隔6小时】PC并未更改过时区（本人电脑商店选的美区用着欧洲标准时玩着国服......)米哈游的服务器端是按时间同步的话，国服应该是北京标准时。不过还是发现给不知道算不算BUG的问题。
巡空的祈愿记录管理显示表格的祈愿记录时间和导出的祈愿记录时间不同。以下有截图
![bandicam 2022-04-17 23-25-02-449](https://user-images.githubusercontent.com/28831997/163732852-da8d47b3-67a9-41a4-b87d-79d0a652f813.jpg)

另外如果感兴趣我附了两份wishlist (20220415旧版的2627行对应20220417新版的2390行 新版比旧版多更新6条记录)
[Wishlog_201923365_20220415_185833.xlsx](https://github.com/Scighost/Xunkong/files/8502485/Wishlog_201923365_20220415_185833.xlsx)
[Wishlog_201923365_20220417_225638.xlsx](https://github.com/Scighost/Xunkong/files/8502486/Wishlog_201923365_20220417_225638.xlsx)

还有一个软件UI上的问题。寻空的滚动条必须用鼠标左键按住拖动的嘛。软件内基本所有页面的鼠标滚轮操作都不生效。

**Comment by DavideSOGG** [comment]
**编辑Excel相关条目的时间后重新导入软件，现在祈愿记录及各卡池记录皆正常显示。问题大抵算是解决了。但是软件中**祈愿记录管理**的**显示表格**** 所有时间依然是本地时间而并非导出记录的Excel所用的中国区时间。这会不会和记录错乱有关呢？另外我猜想欧洲标准时的夏令时冬令时切换也是导致抽卡记录错乱的诱因之一。（冬令时与中国时差为7小时 夏令时与中国时差为6小时）否则解释不通刻晴牛杂统计的正常抽卡数据导入寻空出现错乱.....毕竟二者格式一样的，且在更改时区之前刻晴牛杂的抽卡记录也未发生过错乱

**Comment by Scighost** [comment]
导出文件中时间的时区是 uid 所在服务器的时区，软件中的时区是系统时区。
时间错误有可能是在某次导入时没有识别出 uid，使用了系统时区。
没有出现过鼠标滚轮操作不生效的情况，你是第一个遇到这种问题的。

**Comment by DavideSOGG** [comment]
好的，我新开一个Issue反馈一下鼠标和签到问题。滚轮是真的不生效，可是这个没有日志记录，也没法录GIF。
