### ISSUE TITLE
【建议】 做做原神战绩(米游社-我的-我的角色)呗

### ISSUE THREAD

**Issue by HyBoxwood** [xunkong/xunkong#81]
### 问题描述

没有原神战绩

### 解决方案

做出来了我就彻底不需要米游社了（笑）
主要就是数据总览那一块还有世界探索那一块 生成个截图来分享会十分的舒服

**Comment by Scighost** [comment]
没办法设计出一个美观简洁的页面，截图后还没米游社的好看，不如不做。

**Comment by HyBoxwood** [comment]
![QQ截图20220418155401](https://user-images.githubusercontent.com/87700780/163777351-52660c0a-94aa-4883-9a80-f8b6777bc59e.jpg)
貌似也不是不可以
