### ISSUE TITLE
【建议】旅行札记历史数据的月趋势可以多显示几个月份嘛 现在这个月可以多个估计值以参考吗

### ISSUE THREAD

**Issue by HyBoxwood** [xunkong/xunkong#82]
### 问题描述

月趋势只会显示这个月和上个月 但这个月没过完 我只有月末最后一天有机会看完这两个月的变化趋势 然后下个月又成谷底

### 解决方案

有多少信息就显示多少信息吧 或者加个调整宽度的条子放大缩小 或者用滚轮控制 如同收入记录一般
当月估计值就以当前月的日均收入计算整个月的收入来估计 显示在当月实际收入的旁边或后面即可 用虚线折线即可

**Comment by Scighost** [comment]
有没有一种可能是 你获取的数据太少了
月趋势会显示所有的数据，只有这两个月说明只有这两个月数据。
获取记录那儿有一个**近三月**的按键。。。

**Comment by HyBoxwood** [comment]
并没有，已经获取过近三月的记录了，旅行礼扎生成器都有2.4-2.6的信息。我第一次使用就是按三个月的，显示仍然是只有近两个月的信息撒。

**Comment by Scighost** [comment]
现在用的是哪个版本，如果不是最新版先升级到最新版

**Comment by HyBoxwood** [comment]
已更新。原先的版本应该是原神2.6之前的版本，点击获取三个月记录显示二月新增0条记录之后才展示了二月。
我仍建议有几个月就显示几个月，毕竟存下来的信息仅用于生成旅行礼扎图片是不是不太够。（美好幻想ing）

**Comment by Scighost** [comment]
你看到的月份少是因为存的数据不够多，你只有234月的数据，我还能把1月的变出来不成？
至于本月收入预测，没必要也不想做。

**Comment by HyBoxwood** [comment]
![QQ截图20220418182613](https://user-images.githubusercontent.com/87700780/163795652-2a527c7b-a866-4ede-a015-8e78719847d1.png)
1月也不是没有...
还得是按您意愿来咯。

**Comment by Scighost** [comment]
这就很奇怪，你既然有一月份的部分数据，为什么没统计出来？
月趋势的图是没有限制月份的，所有数据都会纳入统计。
你自己翻一翻数据库吧，月趋势对应的表是 `TravelRecord_MonthDatas` 。

**Comment by HyBoxwood** [comment]
![QQ截图20220420022018](https://user-images.githubusercontent.com/87700780/164070520-db5ce7f4-300d-4a6a-8e33-48e80211b5a0.png)
![QQ截图20220420022253](https://user-images.githubusercontent.com/87700780/164070526-bbe456c5-678b-4341-bad6-f23c0478e549.png)
确实是有一月的一部分

**Comment by Scighost** [comment]
![image](https://user-images.githubusercontent.com/61003590/164142523-9dd12a13-8d5f-474a-a7b2-ababd8e84b88.png)
确实只有234月的数据

**Comment by HyBoxwood** [comment]
那我手算加上吧 哎

**Comment by HyBoxwood** [comment]
原因是按月记录的每个数据非空，二月的数据里面存在上月原石和上月摩拉，所以记录下来了，而一月里没有十二月的记录，不完整，所以生成不了。所以我第一次点三个月的时候，只有二三两月的柱子，到四月份再点，加了四月份的柱子才是三个柱子。
