### ISSUE TITLE
【反馈】使用小地图和启动游戏报错

### ISSUE THREAD

**Issue by Zhuang277** [xunkong/xunkong#85]
### 问题描述

使用小地图和启动游戏报错
InvalidCastException Specified cast is not valid.

### 截图

![Q4](https://user-images.githubusercontent.com/22053122/163790805-7756cde5-2575-467e-adb6-134b9e15d376.png)

### 系统及寻空版本

- 系统：WIN10 1903版本
- 寻空：0.1.7.1

**Comment by Scighost** [comment]
此版本已不是最新版本，如果还有问题，请重新发布新 issue。
