### ISSUE TITLE
祈愿武器/角色名称语言错误

### ISSUE THREAD

**Issue by Crypton-miku** [xunkong/xunkong#97]
### 问题描述

祈愿记录由于获取记录是根据客户端语言导出不同语言的记录，导致同一把武器或角色会在记录中出现不同的语言种类名称

### 复现步骤

```plain text
在获得新五星角色或武器后，修改与原记录不同的语言，上传即出现
```

### 截图

![1](https://user-images.githubusercontent.com/73842800/166116711-5a5eb7c8-ed61-4ab6-b92b-f1d02d255e59.png)

### 系统版本

Windows 10 21H2

### 寻空版本

0.2.0.0正式版

**Comment by Scighost** [comment]
仅支持识别简体中文的祈愿记录

**Comment by Crypton-miku** [comment]
但并没有从程序方面禁止其他语言，或者做兼容，虽然是个小的问题，不过这个不同语言出现之后，无法修改记录了，导致有些功能比如移到上面会高亮同一件的功能就没了，就有点影响体验

**Comment by adldeez** [comment]
> 仅支持识别简体中文的祈愿记录

祈愿记录的url自带语言参数，能否加入读取url时自动修改成lang=zh-cn的功能呢
